"""Climate-impact manuscript supported by the completed census and pooled scores."""
import pandas as pd
from .data import HERE,ROOT,GRID,DERIVED,CANOPY,SEVERITY,ONSET,FREQUENCY,YIELD,SCENARIOS,REGIONS,pooled,grid_data
from analysis.paper_study.nature_food_submission_20261008.sections import (
    sections as previous_sections,AUTHOR,AFFILIATION,EMAIL)

TITLE='Wheat phenology partly offsets projected increases in Septoria damage across Europe'


def sections():
    old=previous_sections();_,regions,countries=grid_data()
    def regional(name,metric,scenario='ssp585',period='2071-2100'):
        return regions[regions.environment_region.eq(name)&regions.metric.eq(metric)&regions.scenario.eq(scenario)&regions.period.eq(period)].iloc[0]
    def national(name,metric,scenario='ssp585'):
        return countries[countries.country.eq(name)&countries.metric.eq(metric)&countries.scenario.eq(scenario)&countries.period.eq('2071-2100')].iloc[0]
    europe=regional('Europe',CANOPY)
    severity=regional('Europe',SEVERITY);onset=regional('Europe',ONSET);frequency=regional('Europe',FREQUENCY)
    symptomatic=regional('Europe','F1_symptomatic_grain_fill_days');grain=regional('Europe','grain_fill_days')
    calendar_onset=regional('Europe','F1_symptom_day_after_sowing')
    symptom_fraction=regional('Europe','F1_symptomatic_grain_fill_fraction')
    env=regions[regions.environment_region.isin(REGIONS)&regions.metric.eq(CANOPY)&regions.scenario.eq('ssp585')&regions.period.eq('2071-2100')].sort_values('mean_change')
    lowest=env.iloc[0];highest=env.iloc[-1]
    country_names=countries.drop_duplicates('country').sort_values('reference_area_ha',ascending=False).head(12).country.tolist()
    country_had=countries[countries.country.isin(country_names)&countries.metric.eq(CANOPY)&countries.scenario.eq('ssp585')&countries.period.eq('2071-2100')].sort_values('mean_change')
    low_country=country_had.iloc[0];high_country=country_had.iloc[-1]
    def country_label(name):return name.replace('United Kingdom of Great Britain and Northern Ireland','United Kingdom')
    regional_clauses=[f'{regional(name,CANOPY).mean_change:+.2f} days in the {name} region' for name in ['Atlantic','Continental','Boreal','Mediterranean','Steppic']]
    regional_summary=', '.join(regional_clauses[:-1])+', and '+regional_clauses[-1]
    signs=pd.read_csv(GRID/'canopy_change_sign_area_shares.csv')
    signs=signs[signs.scenario.eq('ssp585')&signs.period.eq('2071-2100')].set_index('classification')
    model_onset=pooled('symptom_onset','model');benchmark_onset=pooled('symptom_onset','benchmark')
    onset_difference=pooled('symptom_onset','difference')
    model_severity=pooled('severity','model_rmse');benchmark_severity=pooled('severity','benchmark_rmse')
    severity_difference=pooled('severity','rmse_difference');bias=pooled('severity','model_bias')
    abstract=(
        'Septoria tritici blotch threatens European wheat production as climate change alters conditions for disease. '
        'How shifts in leaf emergence, flowering and grain filling modify future disease damage remains poorly quantified. '
        'We linked wheat phenology and Septoria disease models to project canopy damage across Europe using three climate models and three emissions pathways. '
        f'Under SSP5–8.5 in 2071–2100, normalized loss of healthy-area duration during grain filling increased by {europe.mean_change:.2f} days relative to 1991–2020, '
        f'with greater damage across {signs.loc["positive_ensemble","landuse_area_share_percent"]:.1f}% of reference wheat area. '
        f'Regional changes ranged from {lowest.mean_change:+.2f} days in the Mediterranean to {highest.mean_change:+.2f} days in the Boreal region. '
        f'The fraction of healthy-area duration lost increased by {100*severity.mean_change:.2f} percentage points. '
        'Shifts in wheat phenology offset an estimated 71% of the increase in canopy damage attributable to weather. '
        'These projections show that crop timing strongly modifies climate-driven disease damage, with contrasting regional priorities for protecting European wheat production.')
    if len(abstract.split())>150:raise ValueError('Abstract exceeds 150 words.')
    text={'abstract.txt':[abstract]}
    text['introduction.txt']=[
        'Wheat production under climate change depends on both crop performance and losses caused by disease. Septoria tritici blotch (STB), caused by Zymoseptoria tritici, damages wheat leaves and can reduce grain yield. Temperature, rainfall and humidity affect disease development, while changing climate also alters the crop that the pathogen infects. Understanding these linked effects is important for maintaining European wheat production. [[Savary2019|Parker2004|Silva2026]]',
        'Weather favourable for infection does not by itself determine yield loss. Wheat phenology, including the timing of upper-leaf emergence, flowering and grain filling, determines which leaves are exposed and when they support grain growth. Disease progression determines when those leaves become damaged. A shift in either process changes the amount of healthy canopy available during grain filling. Climate assessments based only on infection conditions can therefore miss changes in the timing of damage relative to crop phenology. [[Chaloner2021|Pequeno2024|ShawRoyle1989|LovellCanopy2004|Lovell2004]]',
        'For Septoria tritici blotch, symptoms follow a period of infection and disease development within the leaf. Rainfall, moisture conditions, inoculum availability and canopy development influence the seasonal epidemic. Upper-leaf appearance and unfolding are relevant because damage to these leaves can affect the canopy supporting grain filling. Healthy-area duration (HAD), the integral of healthy leaf area over time, provides a measure linking disease damage to crop function. Its relationship with grain yield varies among cultivars and depends on the leaves and growth stages included in the calculation. [[SuffertSache2011|Baccar2011|Parker2004|Foulkes2006|vanDenBerg2017|Bryson1997]]',
        'The unresolved question is how climate effects on wheat phenology modify Septoria damage across European growing regions. A linked wheat-phenology and disease model quantifies changes in symptoms and canopy damage across the complete wheat land-use grid under three emissions pathways. Environmental-region and country summaries describe where these changes occur. A separate analysis distinguishes weather effects on disease from the effects of changing wheat phenology. Published canopy–yield relationships provide conditional estimates of the disease-related component of yield change, while field observations establish the limits of model prediction accuracy.',
    ]
    late_values=[regional('Europe',CANOPY,s).mean_change for s in SCENARIOS]
    mid_values=[regional('Europe',CANOPY,s,'2031-2060').mean_change for s in SCENARIOS]
    climate=[
        'Results','Regional differences in projected Septoria damage',
        f'Projected Septoria-related canopy damage varied across European wheat-growing grids and emissions pathways (Fig. 1). By 2071–2100, the harvested-area-weighted normalized disease-induced loss of healthy-area duration (HAD) changed by {late_values[0]:+.2f}, {late_values[1]:+.2f} and {late_values[2]:+.2f} days under SSP1–2.6, SSP2–4.5 and SSP5–8.5, respectively, relative to 1991–2020. The corresponding mid-century changes were {mid_values[0]:+.2f}, {mid_values[1]:+.2f} and {mid_values[2]:+.2f} days. Normalized HAD loss is the time-integrated loss of healthy leaf area divided by maximum reference upper-canopy leaf area index (LAI), expressed as equivalent days of reference canopy function lost to disease. Larger values indicate greater accumulated damage. The averages combine areas of increasing and declining damage (Supplementary Table S9).',
        f'Under late-century SSP5–8.5, the European normalized HAD loss changed from {europe.reference_on_common:.2f} to {europe.future_on_common:.2f} days; the three-climate-model change range was {europe.gcm_min:+.2f} to {europe.gcm_max:+.2f} days. The ensemble mean indicated increasing damage across {signs.loc["positive_ensemble","landuse_area_share_percent"]:.1f}% of the available reference wheat area. All three models agreed on greater damage across {signs.loc["positive_all_three_gcm","landuse_area_share_percent"]:.1f}% of area and less damage across {signs.loc["negative_all_three_gcm","landuse_area_share_percent"]:.1f}%; model predictions differed in sign across {signs.loc["mixed_gcm_sign","landuse_area_share_percent"]:.1f}%. The continental increase thus coexisted with areas of declining damage (Supplementary Fig. S19; Supplementary Table S15).',
        'Disease symptoms and canopy damage during grain filling',
        f'Symptom frequency changed little despite increasing canopy damage (Fig. 2). The area-weighted frequency of flag-leaf symptoms before soft dough was {100*frequency.reference_on_common:.3f}% in 1991–2020 and {100*frequency.future_on_common:.3f}% under late-century SSP5–8.5, a change of {100*frequency.mean_change:+.3f} percentage points. Symptoms were predicted in almost every complete season in both periods. The mean fraction of reference HAD lost during grain filling increased from {100*severity.reference_on_common:.2f}% to {100*severity.future_on_common:.2f}%, or {100*severity.mean_change:+.2f} percentage points, with a climate-model range of {100*severity.gcm_min:+.2f} to {100*severity.gcm_max:+.2f} points. Relative HAD loss describes accumulated canopy-function loss; observed lesion percentage measures a different quantity (Supplementary Tables S9 and S13b).',
        f'Flag-leaf symptoms appeared {abs(onset.mean_change):.2f} days '+('earlier' if onset.mean_change<0 else 'later')+f' relative to flowering, with model-specific changes of {onset.gcm_min:+.2f} to {onset.gcm_max:+.2f} days. The interval from the fixed sowing date to first symptoms shortened by {abs(calendar_onset.mean_change):.2f} days, spanning {calendar_onset.gcm_min:+.2f} to {calendar_onset.gcm_max:+.2f} days across climate models (Fig. 2b,d). Flag-leaf symptoms were present during {100*symptom_fraction.reference_on_common:.2f}% of grain-fill days in 1991–2020 and {100*symptom_fraction.future_on_common:.2f}% in the future. The number of grain-fill days with symptoms changed by {symptomatic.mean_change:+.2f} days, alongside a {grain.mean_change:+.2f}-day change in the flowering-to-soft-dough interval. The large advance in symptoms after sowing accompanied earlier flowering and soft dough, with little change in the duration of grain filling. Timing estimates include symptoms detected in both paired seasons; frequency estimates also include complete seasons without symptoms (Supplementary Figs. S12 and S14).',
        'Differences among environmental regions and countries',
        'Environmental-region means differed substantially (Fig. 3a; Table 1). Under late-century SSP5–8.5, normalized HAD-loss changes were '+regional_summary+f'. Among the eight named environmental regions, the largest mean increase occurred in the {highest.environment_region} region and the largest decrease in the {lowest.environment_region} region. The {highest.environment_region} change spanned {highest.gcm_min:+.2f} to {highest.gcm_max:+.2f} days across climate models, compared with {lowest.gcm_min:+.2f} to {lowest.gcm_max:+.2f} days in the {lowest.environment_region} region. Alpine, Pannonian and Black Sea cells were included alongside the five larger regions (Supplementary Tables S13a–c and S16).',
        f'Country summaries also showed increasing and declining damage. Among the twelve country groups with the largest reference wheat area, late-century SSP5–8.5 HAD changes ranged from {low_country.mean_change:+.2f} days in {country_label(low_country.country)} to {high_country.mean_change:+.2f} days in {country_label(high_country.country)}. Yield changes inferred from their canopy damage differed in sign and magnitude (Fig. 3b). The full set of country means and climate-model ranges includes all country-assigned wheat cells within the study domain, with calendar eligibility and valid-season coverage reported for each group (Supplementary Table S14).',
        'Yield changes inferred from canopy damage',
        f'Applying the reference HAD–yield coefficient converted the late-century SSP5–8.5 HAD change into an estimated disease-related yield change of {-1000*europe.mean_change*.018:+.1f} kg ha⁻¹ per unit reference upper-canopy LAI. The three-climate-model range was {-1000*europe.gcm_max*.018:+.1f} to {-1000*europe.gcm_min*.018:+.1f} kg ha⁻¹ per reference LAI. At coefficients of 0.0141–0.0207 t ha⁻¹ per green-leaf-area-index day (GLAI-day), the same canopy response produced a conversion range of {-1000*europe.mean_change*.0207:+.1f} to {-1000*europe.mean_change*.0141:+.1f} kg ha⁻¹ per reference LAI. A negative change indicates greater estimated disease-related yield loss. These estimates depend on the assumed canopy area and linear HAD–yield relationship (Fig. 3b; Supplementary Fig. S13).',
        'Evaluation of the canopy–yield relationship showed limited prediction accuracy across genetic backgrounds. Eight treatment-mean contrasts across five genetic backgrounds gave leave-one-background-out relative-yield RMSE of 5.16 percentage points and R² of 0.247, but absolute-yield RMSE of 0.617 t ha⁻¹ and R² of −0.432. Two contrasts concerned STB alone; the other six involved yellow rust or mixed diseases. The grid estimates provide a disease-related yield index under specified assumptions. Total wheat yield and national production changes require additional crop-yield modelling and validation (Supplementary Figs. S9–S11; Supplementary Tables S5–S8). [[Parker2004|Foulkes2006]]',
        'Severity-based yield responses transfer poorly across field environments. In five Nordic trials, 62 treated–untreated contrasts gave trial-held-out RMSE of 4.83 percentage points for severity regression and 5.02 for the training mean. Adding assessment stage reduced error to 3.99 points in the four-trial subset with recorded stages, but the paired difference interval included zero and three of four conditional severity slopes opposed a monotone damage response. In Tunisia, flag- and lower-leaf severity gave cross-year yield RMSE of 3.32 t ha⁻¹, compared with 3.24 for the training mean across 82 plot-season yields (Supplementary Figs. S22 and S23; Supplementary Tables S17–S19). [[NFTS2026|BenMbarek2020]]',
        'German field data provided a broader test across 3,264 cultivar–management comparisons in 16 site-years at five locations. Endpoint Septoria severity had geographic-site-held-out yield-response RMSE of 18.51 percentage points, compared with 18.48 for the training mean. Nitrogen and water regime reduced forward-transfer error from 19.56 to 17.55 points; adding severity changed it to 17.51 points. These responses concerned protection against multiple diseases. Endpoint severity supplied little additional predictive information beyond crop management, and none of the field comparisons validated the conversion from simulated HAD loss to grain yield (Supplementary Fig. S24; Supplementary Table S20). [[BRIWECS2025]]',
        'Wheat phenology offsets part of the increase in disease damage',
        'Changes in wheat phenology offset 70.6% of the increase in canopy damage attributable to weather under late-century SSP5–8.5 (Fig. 4). The weather contribution increased normalized HAD loss by 9.00 days, while wheat phenology reduced it by 6.36 days, giving a net increase of 2.64 days. All three climate models showed these opposing effects, with offsets of 63.6–80.3%. The decomposition uses 5,731 valid season pairs from 62 wheat-growing grid cells. Its net estimate is close to the full-grid increase of 2.66 days, although the two calculations use different sets of cells and valid seasons (Supplementary Tables S12a,b).',
        'Flowering and soft dough advanced by 26.77 and 26.64 days after sowing, while mean grain-fill duration changed little. The wheat-phenology contribution combines changes in upper-leaf appearance and unfolding with shifts in flowering and soft-dough dates. These changes alter leaf availability and the seasonal weather experienced by the upper canopy. A −2.78-day weather–crop interaction was allocated equally between the two Shapley contributions. Twenty additional finite pairs were excluded because recombined weather and crop trajectories exceeded the accepted temperature range on an active day (Supplementary Fig. S16).',
        'Sensitivity and prediction accuracy',
        'All fourteen tested combinations of model structure, symptom detection and canopy assumptions gave earlier symptoms and increased HAD loss in all three climate models under late-century SSP5–8.5. Across these settings, mean symptom shifts spanned −5.46 to −1.54 days and HAD increases 0.63–2.80 days. These comparisons describe sensitivity to selected model assumptions and do not cover every source of uncertainty in future disease outbreaks (Supplementary Fig. S15; Supplementary Table S10).',
        f'Pooled field evaluation gave mean symptom-onset error outside the observation interval of {model_onset.value:.2f} days versus {benchmark_onset.value:.2f} days for the phenology benchmark across {int(model_onset.records)} histories. The paired difference was {onset_difference.value:+.2f} days (95% grouped-bootstrap interval {onset_difference.lower95:.2f}–{onset_difference.upper95:.2f}). Across {int(model_severity.records):,} disease assessments from {int(model_severity.fields)} field seasons, severity RMSE was {model_severity.value:.2f} versus {benchmark_severity.value:.2f} percentage points, with model bias {bias.value:+.2f} points. The paired RMSE difference was {severity_difference.value:+.2f} points (95% interval {severity_difference.lower95:.2f}–{severity_difference.upper95:.2f}). Wheat-stage predictions had station-held-out MAE of 8.02 days across 40,878 events. Disease prediction accuracy remains a major limitation on the interpretation of future damage magnitudes (Supplementary Figs. S18 and S20; Supplementary Tables S1–S4).'
    ]
    text['climate_results.txt']=climate
    text['field_results.txt']=[];text['baseline_results.txt']=[]
    text['discussion_field_and_limits.txt']=[
        'Discussion',
        'The simulations project increasing average Septoria damage across European wheat-growing areas, alongside decreases in some regions. These differences arise from weather effects on disease combined with changes in wheat phenology. Because symptoms were predicted in almost every season, symptom presence alone was a weak measure of the projected change. The timing of symptoms and the amount of healthy canopy lost during grain filling provided more information about the modelled disease impact.',
        'The analysis links three processes: weather affects wheat phenology and disease progression; wheat phenology determines the leaves and seasonal conditions available to the disease; and disease damage reduces the assumed healthy canopy contributing to grain filling. The opposing weather and phenology contributions show why favourable infection conditions do not translate directly into proportional increases in canopy damage. The crop–disease interaction is represented through leaf availability and timing. Disease damage is converted to a yield estimate after simulation, while disease feedback on wheat phenology and a complete crop carbon balance are absent. These distinctions separate the projected disease component from the total effect of climate change on wheat production. [[Chaloner2021|Pequeno2024|Silva2026]]',
        'The regional contrasts identify areas where crop and disease observations would be informative for adaptation trials. Greater projected damage in Boreal and Atlantic wheat-growing areas warrants testing disease resistance, crop calendars and canopy persistence together. Declining disease damage in the Mediterranean region also requires field verification because a decline in the disease component does not establish an increase in total grain yield. Country estimates describe the area included in the fixed wheat grid and imposed winter-wheat calendar. Differences in cultivar, irrigation, crop management and cross-border grid assignment limit their interpretation as national forecasts.',
        'The link from disease damage to grain yield is the least directly validated part of the analysis. Disease-assessment percentages, functional canopy loss and grain yield describe different quantities. The assumed conversion from disease damage to functional loss requires physiological measurements, and the published HAD–yield coefficients were fitted to a wider growth-stage interval than the main flowering-to-soft-dough calculation. The available treatment means span mixed diseases and give poor absolute-yield predictions across genetic backgrounds. Canopy-based yield estimates remain conditional indices, with actual production losses requiring compatible measurements of leaf area, canopy function and grain yield. [[Parker2004|Foulkes2006|vanDenBerg2017]]',
        'A physiological yield calculation requires crop condition as well as disease severity. Layer-specific green leaf area determines light interception, while grain formation depends on pre-anthesis reserves, grain number and assimilate supply during grain filling. Published damage frameworks represent these pathways within crop-growth models, including WOFOST and DSSAT formulations. The field comparisons support this distinction: lower regression error alone does not establish a physiological loss function, and observations without compatible leaf area and timing cannot identify its parameters. Crop-growth calibration and evaluation of disease-related yield loss require separate field environments. [[Bancal2007|Bancal2015|Bregaglio2021]]',
        'Disease-model performance adds substantial uncertainty. The model had greater symptom-onset error than the phenology benchmark and underestimated measured disease severity. High symptom-detection sensitivity with low specificity is consistent with the near-universal symptom occurrence in the simulations. Added developmental stages, including the end of the grain-filling interval, have limited informative field observations. Agreement among climate models cannot establish epidemic prediction accuracy. Reconstructed humidity, fixed inoculum assumptions, cultivar resistance and future pathogen adaptation also affect the applicability of the projected changes.',
        'Regional adaptation assessments for European wheat need to consider disease resistance alongside crop phenology and canopy persistence. Coordinated observations of crop stages, disease symptoms, healthy leaf area and harvested grain would help identify whether adaptation reduces exposure, prevents damage or improves yield tolerance. Resistance and calendar trials across contrasting regions can evaluate these mechanisms under consistent measurement definitions. Intervention effectiveness and effects on production require validation in field trials. [[McDonald2022|ECVision2025]]',
    ]
    text['methods.txt']=[
        'Methods',
        'Wheat-growing area and climate data',
        'The European SPAM2020 all-wheat registry contains 14,941 cells with positive harvested wheat area at 0.25° resolution. A fixed GGCMI winter-wheat rainfed calendar is available for 14,932 cells; nine cells have unavailable simulation outcomes. The all-wheat area mask combined with a winter-wheat rainfed calendar defines the crop-management scenario. It is not a census of observed winter-wheat management. Harvested area provides fixed weights for spatial aggregation. Supplementary Fig. S21 shows the study area, field-observation locations and environmental regions. [[SPAM2020|GGCMIPhase32021]]',
        'Daily NEX-GDDP-CMIP6v2 data represent ACCESS-CM2, MPI-ESM1-2-HR and MRI-ESM2-0 under SSP1–2.6, SSP2–4.5 and SSP5–8.5. The harvest periods are 1991–2020, 2031–2060 and 2071–2100. The 810 model–scenario–year combinations cover 12,094,920 calendar-eligible grid-seasons. Monthly adjustment coefficients align climate variables with the reference weather data, with separate historical adjustments for each SSP continuation. Daily series include the preceding calendar year to represent overwintering seasons. Input files, adjustment coefficients and model configurations are identified by checksums. [[NEXGDDPCmip6V2]]',
        'Disease calculations use daily temperature, relative humidity and rainfall. A synthetic reconstruction of humidity within each day estimates moisture exposure from daily forcing; it does not supply measured leaf wetness. Missing weather and daily mean temperatures above 40 °C produce unavailable outcomes under the model input rules.',
        'Linking wheat phenology to Septoria disease',
        'A temperature–photoperiod–vernalization model calculates wheat phenological stages from sowing to soft dough. Additional ordered developmental thresholds determine upper-leaf appearance and unfolding, and a calibrated flowering threshold defines the start of the grain-filling interval. These crop trajectories determine which leaves are available to infection and the seasonal weather experienced by each leaf. The Septoria module calculates disease establishment, progression and visible damage using weather and these leaf trajectories. Disease damage does not alter the calculated crop-development trajectory. Model equations, parameter sources and observation definitions appear in the supplementary model specification and the 84-entry parameter inventory. [[SuffertSache2011|ShawRoyle1989|LovellCanopy2004|Baccar2011|Lovell2004]]',
        'Calibrated parameters remain fixed across climate scenarios. The maximum reference LAI of the upper three leaves is one, divided equally among leaves and scaled by unfolding. Cultivar-specific canopy area and future changes in resistance are not estimated. Soft dough marks season completion. Missing crop calendars, invalid weather and failure to reach the endpoint remain separate unavailable outcomes, rather than zero disease or zero loss.',
        'Symptoms, canopy damage and healthy-area duration',
        'Symptom frequency is the fraction of complete simulated seasons with detectable flag-leaf symptoms before soft dough. First-symptom timing is measured relative to flowering or sowing and is unavailable when symptoms are not detected. Symptomatic grain-fill days count days with detectable flag-leaf symptoms between flowering and soft dough. Symptoms are visible model states following disease development; their dates are distinct from the modelled dates of initial infection.',
        'The disease-damage fraction after symptom detection is treated as the fraction of reference leaf area that has lost function. This assumption connects modelled disease to canopy damage. HAD loss integrates this fraction multiplied by daily reference leaf area across the flag leaf and two leaves below it. The primary interval is flowering to soft dough (GS65–85), with GS31–85 used for sensitivity analysis. HAD and disease-induced HAD loss have units of green leaf area index multiplied by days (GLAI-days). Normalized HAD loss divides the time-integrated functional loss by maximum reference upper-canopy LAI and expresses it as equivalent days of reference canopy function lost. With reference LAI equal to one, normalization leaves numerical values unchanged. Relative HAD loss is HAD loss divided by reference HAD, expressed as a percentage; it describes average accumulated canopy-function loss, not instantaneous lesion percentage. [[Parker2004|vanDenBerg2017]]',
        'Flowering provides a reference for grain filling rather than the start of disease simulation or a universal crop-protection threshold. Disease calculations begin during crop establishment and include upper-leaf appearance and unfolding before flowering. Stem extension and upper-leaf emergence define earlier exposure relevant to canopy protection. The GS65–85 integral describes grain-filling canopy damage; it does not quantify every effect of pre-flowering disease on grain number or assimilate reserves. [[Parker2004|Bancal2007]]',
        'Historical–future comparisons and spatial summaries',
        'Each future harvest year is paired with the corresponding position in the 30-year historical period for the same climate model and SSP. This indexing supports comparisons of period means without identifying historical and future years as the same physical event. A pair is included only when both metric values are finite. For grid i, x_i is the sum of valid paired differences divided by 30, and z_i is the number of valid pairs divided by 30. The grid mean change is x_i/z_i. Reference and future means use the same valid pairs. The valid seasons may differ among symptom timing, symptom frequency and canopy metrics.',
        'For domain indicator I_i and fixed harvested area w_i, the mean change is Σw_i I_i x_i / Σw_i I_i z_i. Separate estimates for each climate model give the reported three-model mean and range. EEA 2016 boundaries assign environmental regions from wheat-cell centroids. Country assignment uses the dominant SPAM source-country label of each cell; cross-border cells are not divided among countries. Country estimates apply only to represented wheat cells within the study domain. Source Data includes all eight named environmental regions, outside-region and unassigned cells, and all country groups. [[EEA2016]]',
        'Maps show model means at the native 0.25° grid resolution, without interpolation or filling unavailable cells. Area shares by direction of change use fixed harvested-area weights over cells with complete three-model estimates. Model ranges describe spread among three climate models and are not confidence intervals. All wheat cells are simulated, so full-grid estimates have no spatial-sampling Monte Carlo error. Other uncertainties include climate-model choice, model parameters, observations and the canopy–yield relationship. The twelve countries in Fig. 3 are selected by reference wheat area independently of the projected change.',
        'Estimating the disease-related yield response',
        'The estimated disease-related yield change is −b times the change in HAD loss. The reference coefficient b is 0.018 t ha⁻¹ per GLAI-day, with 0.0141 and 0.0207 used as fixed alternatives from the published upper-three-leaf study. Multiplication by 1,000 converts t ha⁻¹ to kg ha⁻¹. Results are expressed per unit reference upper-canopy LAI because actual canopy area is unspecified. The source relationship began at GS31, whereas the primary climate calculation covers GS65–85; its use in this shorter interval is an unvalidated adaptation. Coefficient alternatives represent cultivar differences, not statistical confidence limits. The calculation estimates a disease-related yield component under these assumptions, without modelling the direct effects of heat, water limitation, CO₂ or other stresses on total grain yield. Yield percentages and national production tonnages require independently validated canopy area and grain yield. [[Parker2004|Foulkes2006]]',
        'Separating weather and wheat-phenology effects',
        'The decomposition and fourteen-setting sensitivity analysis use 64 harvested-area-proportional draws at 62 unique cells. Four simulations combine historical or future disease weather with historical or future wheat-phenology trajectories. Their differences separate weather and wheat-phenology contributions, with one half of their interaction allocated to each Shapley contribution. Of 5,751 finite historical–future pairs, 20 have an active day outside the accepted temperature range in a recombined trajectory and are excluded, leaving 5,731 pairs. Spatial Monte Carlo standard errors apply to this sample and are separate from full-grid climate estimates.',
        'The phenology offset is −100 times the phenology contribution divided by the weather contribution, using identical valid pairs. The ensemble percentage is the ratio of three-model mean contributions. Sensitivity settings vary model structure, symptom detection, reference canopy area and damage-to-function conversion. These calculations assess model assumptions and do not represent trials of a sowing-date or cultivar intervention.',
        'Field evaluation',
        'Disease observations from the two public field archives are pooled after exclusion of calibration records and application of geographic eligibility criteria. The evaluation contains 2,033 assessments from 188 field seasons in 140 coordinate-years and 136 symptom-onset histories from 78 field seasons in 62 coordinate-years. Onset histories concern source-defined leaves 1–3 and have observations bracketing symptom appearance. Original identifiers, units and percentage denominators remain in the evidence files. Source leaf numbers do not establish a common final-leaf rank across archives. [[Holst2022BASF|HolstDonner2022Corteva]]',
        'Evaluation weights are equal among coordinate-years, fields within coordinate-years, source leaves within fields and assessments within leaves. Symptom-onset error measures distance outside the two-sided observation interval, with the predefined penalty for missed positive observations. Severity predictions are compared with the calibration-leaf-mean benchmark; timing and detection use the phenology benchmark selected on calibration data. Model and benchmark predictions are compared on identical records. The 95% intervals use 20,000 paired bootstrap resamples of entire coordinate-year groups. They describe uncertainty in these fixed predictions on reused retrospective observations and exclude parameter-selection uncertainty. Duplicate coordinate-year identities are grouped across archives.',
        'Wheat phenological stage dates are evaluated on 40,878 matched events from German stations held out of calibration, at BBCH 10, 31, 51 and 85. Added leaf stages use pooled field observation intervals, with calibration observations reported separately. Evaluation of the canopy–yield relationship uses eight published treatment-mean contrasts across five genetic backgrounds, including STB, yellow rust and mixed disease. Leaving each background out of fitting gives backgrounds equal evaluation weight. Severity-based yield models use their specified held-out trial or year comparisons and corresponding training-mean benchmarks. [[Foulkes2006]]',
        'Additional yield-response tests retain the measurement hierarchy of each public source. Nordic assessment dates sharing a treatment yield remain in the same trial fold; eight post-harvest assessments and three rows of a pooled-control alias are excluded. Stage zero remains missing. Tunisia supplies 82 unprotected plot-season yields with two leaf assessments per outcome and 40 protected references in 2019. Flag and lower leaves were assessed on different dates. Protected-plot severity is unobserved and is not assigned zero. Whole-year transfer tests absolute yield, while mixture and replicate holdouts test relative protected-reference gaps within 2019. [[NFTS2026|BenMbarek2020|TunisiaDryad2020]]',
        'German original site files supply protection comparisons matched by location, year, cultivar, nitrogen and source-coded water regime. Unsuffixed HN/LN × NF/WF treatments enter; drought-suffixed references remain separate. Original fractional disease scores and missing values are preserved. Harvest treatment means use all eligible positive yield observations; severity means use only recorded assessments, with their replicate coverage retained. The relative response is 1 − unprotected yield / protected yield. German dry-mass yields are not pooled with other sources for absolute-yield fitting. Entire site-years or geographic sites are excluded from fitting, and forward transfer fits 2015–2017 and evaluates 2018–2019. Cultivar identities may occur in both training and evaluation; these comparisons test environmental transfer rather than prediction for unseen cultivars. [[BRIWECS2025]]',
        'All prespecified candidate models are compared with their corresponding training-mean benchmark. Weights are equal among held-out trial, year or location groups and then among outcomes within groups. Ridge models standardize predictors using training data and use a fixed penalty of 0.1. Nordic model choice uses inner training-trial validation. Paired Nordic intervals resample entire trials conditional on fixed predictions; they exclude refitting uncertainty. The nonnegative assessment-stage model is a secondary diagnostic following inspection of the stage-regression slopes. Infection dates, functional canopy trajectories and cause-specific STB losses are not validation targets of these severity-based comparisons.',
        'Reproducibility',
        'Annual outputs record input-weather identities, model configurations, grid-cell order, numerical checks and output hashes. Aggregation records source hashes, counts of valid pairs and spatial coverage for each metric. Independent calculations check pooled field scores and selected full-grid regional means. Source Data contains figure and table values. The software archive regenerates documents from completed numerical evidence; a climate-driven model rerun additionally requires the external raw weather products.',
    ]
    text['supplementary_methods.txt']=[
        'Supplementary Methods',
        'Crop, disease and yield relationships',
        'Daily climate data drive wheat-phenology and Septoria-disease calculations. Wheat phenology determines leaf appearance, unfolding and the flowering-to-soft-dough interval. The disease model predicts damage on those leaves; its damage does not feed back into crop-development rates. After symptom detection, damage is mapped to an assumed loss of leaf function. Integration gives HAD loss, and a published coefficient converts HAD loss to a conditional disease-related yield estimate. This final calculation is separate from a complete crop-yield model.',
        'The reference upper-three-leaf canopy has maximum LAI of one. Disease-induced HAD loss integrates the assumed loss of functional green leaf area over time, with units of GLAI-days. Division by maximum reference LAI gives normalized HAD loss, expressed as equivalent days of reference canopy function lost. Numerical values are identical in the unit-LAI scenario. Relative HAD loss is the ratio of HAD loss to reference HAD and describes loss of assumed canopy function over the integration interval. Measured leaf-lesion percentage has a different denominator and temporal meaning.',
        'Full-grid climate estimates',
        'The experiment includes all 14,941 wheat land-use cells, with eligible calendars for 14,932 cells. Invalid seasons have unavailable outcomes. Symptom timing requires detection, while symptom frequency includes complete seasons without symptoms. Each metric has its own valid historical–future pairs. Corresponding positions in the two 30-year periods are paired within a climate model and SSP.',
        'Spatial means divide the harvested-area-weighted sum of paired changes by the harvested-area-weighted number of valid pairs. Historical and future means use these same pairs. Climate-model ranges span three independently aggregated estimates. The full-grid calculation has no spatial sampling error. Environmental regions follow EEA centroid assignment and countries follow dominant SPAM source-country labels; outside-region and unassigned cells remain explicit.',
        'Field observations and prediction scores',
        'Pooled disease evaluation excludes calibration records and combines geographically eligible records from both archives. Source identifiers and assessment definitions remain in the evidence files. Calibration and evaluation have no shared field identifiers. Coordinate-year identities define geographic bootstrap groups, with overlapping identities treated as the same group.',
        'An assessment weight is the reciprocal of the number of coordinate-years multiplied by the reciprocals of fields, source leaves and observations within successive groups. RMSE is the square root of the weighted mean squared error. Twenty thousand paired coordinate-year bootstrap resamples, with seed 20261008, give 95% percentile intervals. Every resample retains both predictions and all field, leaf and date records in a sampled group. The intervals exclude parameter-selection uncertainty and verification of independent biological-site identities.',
        'Symptom-onset comparisons use observed intervals bracketing first symptoms and specified penalties for missed positive observations. Crop-stage evaluation also uses two-sided observation intervals; plotted interval centres are display locations, not exact observed event dates. Calibration profiles and nested model selection are separate from pooled evaluation. German station observations evaluate the established phenology formulation; field support for added upper-leaf stages and soft dough remains limited.',
        'Canopy-based yield estimates',
        'Published protected and unprotected treatment means retain their leaf coverage, growth-stage interval, cultivar and disease exposure. The eight contrasts across five backgrounds include two with STB alone, two with yellow rust and four with mixed diseases. Absolute and relative yield scores describe aggregate treatment means when each genetic background is excluded from fitting. Raw plot variation and covariance are unavailable.',
        'The grid yield estimate is a linear conversion of HAD loss under the assumed upper-three-leaf canopy. Fixed coefficients and alternative GS31–85 and GS65–85 intervals assess dependence on these assumptions. The primary interval is shorter than the source coefficient interval, so the conversion requires field validation. Positive projected yield changes denote a decrease in the estimated disease-loss component; they do not establish a gain in total yield under future climate.',
        'Severity-based field yield comparisons',
        'The consolidated Tunisia/Nordic inventory contains 423 dated leaf or treatment assessments sharing 272 yield keys. Exclusion of a known control alias and post-harvest assessments leaves 412 assessments and 263 outcomes. These inventory counts do not denote independent environments. The Nordic predictive population contains 62 treated–untreated contrasts in five trials; subsets with known assessment stage and an earlier matched assessment contain 51 and 40 contrasts, respectively. Missing treated-plot stem-extension assessments remain unavailable. Growth-stage interactions use recorded ordinal GS, rather than elapsed time. The fixed stage-regression basis is severity reduction multiplied by (GS − 75)/10. The secondary nonnegative basis uses severity reduction multiplied by (85 − GS)/10. Neither basis represents observed infection timing.',
        'The Tunisian plot table contains incidence-weighted lesion area on flag and immediately lower leaves. Flag leaves were assessed at GS75 in both years; lower leaves were assessed at GS61 in 2018 and GS73 in 2019. The leaf-stage and year differences prevent separate identification of leaf-specific physiological coefficients. No same-leaf AUDPC or HAD is reconstructed. Cultivar proportions define composition predictors and shared mixture identities; treatment numbers are year-specific. Two-way whole-year transfer evaluates absolute yield on 82 outcomes. The 40 source-matched reference contrasts retain one negative response; within-year validation excludes entire mixture compositions or source replicate groups. These comparisons remain within one site-year and do not establish external environmental validity.',
        'German source harmonization preserves the original site-table precision and follows the documented source treatment coding, while excluding drought-suffixed WF references from unsuffixed NF/WF pairs. One nonnumeric severity token remains unavailable. Treatment means retain yield and severity replicate counts separately; missing protected severity is not imputed. The primary endpoint population contains 3,264 comparisons across 16 site-years and five locations. The subset with observed severity on both management groups contains 954 comparisons across seven site-years and four locations. Common-population benchmarks accompany each comparison. The primary and temporal comparisons give site-years equal weight; geographic transfer gives locations equal weight. Site-specific rating comparability and incomplete assessment timing remain limitations.',
        'The complete source inventory includes raw field observations, regional survey aggregates, published model-adjusted means, fitted curves and model inputs. Fitted response grids, duplicate archive copies and published parameter tables do not increase observational sample size. Older Nordic/Baltic yield and weather-derived recommendation tables do not provide observed severity–yield pairs. New data-source identities, eligibility, fixed protocols, held-out predictions and independent numerical checks are retained with the current source data.',
        'Weather and wheat-phenology contributions',
        'The separate decomposition uses four historical–future combinations of disease weather and wheat-phenology trajectories in the 64-draw sample. Twenty pairs exceeding the accepted temperature range in a recombined trajectory are excluded. The two Shapley contributions share the interaction equally and sum to the net change on the same valid pairs. Phenology offsets use the identical pair set in numerator and denominator. The three-model ensemble offset is a ratio of mean contributions.',
        'The main maps and regional estimates describe the completed full-grid experiment. Decomposition and structural sensitivity describe the separate sampled analysis. Field figures describe prediction errors on retrospective observations, and published yield figures describe treatment-mean contrasts. These datasets support different quantities and do not define a single overall model-accuracy percentage.',
    ]
    text['availability.txt']=[
        'Data availability',
        'Source data and numerical evidence supporting the findings are deposited at https://github.com/SmartAG-Team/paper_cc_impact_wheat_disease, with the manuscript-specific files in publication/european_wheat_stb. The repository is private during manuscript preparation. Dataset references identify the public disease archives, the Nordic Field Trial System, Tunisian cultivar-mixture observations, German multi-environment field data, NEX-GDDP-CMIP6v2 climate data, GGCMI calendars, SPAM2020 wheat area and EEA environmental boundaries. Source_Data.xlsx contains completed grid summaries, environmental-region and country statistics, area shares by direction of change, pooled field evaluation, published canopy–yield evidence and the additional grouped yield-response tests. Original labels and assessment definitions remain in the underlying records. [[Holst2022BASF|HolstDonner2022Corteva|NFTS2026|TunisiaDryad2020|BRIWECS2025|NEXGDDPCmip6V2|GGCMIPhase32021|SPAM2020|EEA2016]]',
        'The repository includes completed summaries, selected diagnostic outputs, input and output hashes, and numerical evidence for document regeneration. The complete raw climate and annual-output archives are external because of their size. Model reruns require the recorded climate products and adjustment files. Raw plot observations and physiological measurements unavailable in the source studies are not reconstructed.',
        'Code availability',
        'Simulation, statistical-analysis and document-generation code are deposited in the same repository, which remains private during manuscript preparation. The repository includes evidence manifests and an executed field-yield validation notebook. REPRODUCIBILITY.txt documents regeneration and model-rerun requirements. The supplementary model specification contains 29 numbered equations, and Parameter_inventory.csv records 84 fixed, fitted and scenario quantities.',
    ]
    text['declarations.txt']=old['declarations.txt']
    return text
