"""Climate-impact manuscript supported by the completed census and pooled scores."""
import pandas as pd
from .data import HERE,ROOT,GRID,DERIVED,CANOPY,SEVERITY,ONSET,FREQUENCY,YIELD,SCENARIOS,REGIONS,pooled,grid_data
from analysis.paper_study.nature_food_submission_20261008.sections import (
    sections as previous_sections,AUTHOR,AFFILIATION,EMAIL)

TITLE='Climate change redistributes simulated Septoria damage in European wheat'


def sections():
    old=previous_sections();_,regions,countries=grid_data()
    def regional(name,metric,scenario='ssp585',period='2071-2100'):
        return regions[regions.environment_region.eq(name)&regions.metric.eq(metric)&regions.scenario.eq(scenario)&regions.period.eq(period)].iloc[0]
    def national(name,metric,scenario='ssp585'):
        return countries[countries.country.eq(name)&countries.metric.eq(metric)&countries.scenario.eq(scenario)&countries.period.eq('2071-2100')].iloc[0]
    europe=regional('Europe',CANOPY)
    severity=regional('Europe',SEVERITY);onset=regional('Europe',ONSET);frequency=regional('Europe',FREQUENCY)
    symptomatic=regional('Europe','F1_symptomatic_grain_fill_days');grain=regional('Europe','grain_fill_days')
    calendar_onset=regional('Europe','F1_symptom_day_after_sowing')
    symptom_fraction=regional('Europe','F1_symptomatic_grain_fill_fraction')
    env=regions[regions.environment_region.isin(REGIONS)&regions.metric.eq(CANOPY)&regions.scenario.eq('ssp585')&regions.period.eq('2071-2100')].sort_values('mean_change')
    lowest=env.iloc[0];highest=env.iloc[-1]
    country_names=countries.drop_duplicates('country').sort_values('reference_area_ha',ascending=False).head(12).country.tolist()
    country_had=countries[countries.country.isin(country_names)&countries.metric.eq(CANOPY)&countries.scenario.eq('ssp585')&countries.period.eq('2071-2100')].sort_values('mean_change')
    low_country=country_had.iloc[0];high_country=country_had.iloc[-1]
    def country_label(name):return name.replace('United Kingdom of Great Britain and Northern Ireland','United Kingdom')
    regional_clauses=[f'{regional(name,CANOPY).mean_change:+.2f} days in the {name} region' for name in ['Atlantic','Continental','Boreal','Mediterranean','Steppic']]
    regional_summary=', '.join(regional_clauses[:-1])+', and '+regional_clauses[-1]
    signs=pd.read_csv(GRID/'canopy_change_sign_area_shares.csv')
    signs=signs[signs.scenario.eq('ssp585')&signs.period.eq('2071-2100')].set_index('classification')
    model_onset=pooled('symptom_onset','model');benchmark_onset=pooled('symptom_onset','benchmark')
    onset_difference=pooled('symptom_onset','difference')
    model_severity=pooled('severity','model_rmse');benchmark_severity=pooled('severity','benchmark_rmse')
    severity_difference=pooled('severity','rmse_difference');bias=pooled('severity','model_bias')
    abstract=(
        'Climate-driven crop disease threatens the stability of European wheat production. '
        'The spatial consequences of changing disease–crop timing for canopy damage remain poorly quantified. '
        'We coupled wheat and Septoria simulations across 14,932 land-use grids with fixed winter-wheat calendars, three climate models and three emissions pathways. '
        f'Under SSP5–8.5 in 2071–2100 relative to 1991–2020, the European healthy-area-duration deficit changed by {europe.mean_change:+.2f} days per reference leaf area. '
        f'Regional changes ranged from {lowest.mean_change:+.2f} in the {lowest.environment_region} region to {highest.mean_change:+.2f} days in the {highest.environment_region} region. '
        f'Mean canopy damage changed by {100*severity.mean_change:+.2f} percentage points, with a conditional yield change of {-1000*.018*europe.mean_change:+.1f} kg ha⁻¹ per reference leaf area. '
        'A diagnostic decomposition attributed a 71% offset of the disease-weather contribution to crop development. '
        'Yield consequences remained conditional on canopy–yield conversion, and disease prediction skill remained limited. '
        'These regional contrasts support joint evaluation of crop calendars, disease resistance and canopy function for resilient wheat production.')
    if len(abstract.split())>150:raise ValueError('Abstract exceeds 150 words.')
    text={'abstract.txt':[abstract]}
    text['introduction.txt']=old['introduction.txt'][:4]+[
        'The central hypothesis is that climate-driven wheat development modifies the timing and magnitude of disease-related canopy damage, producing spatially contrasting production consequences. A full-grid European analysis quantifies changes in symptom occurrence, disease–crop timing and canopy damage under three emissions pathways. Environmental-region and country summaries connect the spatial responses to wheat-growing areas, while a weather–crop decomposition examines their modeled drivers. Pooled field evaluation and independent canopy–yield evidence constrain the interpretation of conditional yield responses.'
    ]
    late_values=[regional('Europe',CANOPY,s).mean_change for s in SCENARIOS]
    mid_values=[regional('Europe',CANOPY,s,'2031-2060').mean_change for s in SCENARIOS]
    climate=[
        'Results','Spatially divergent climate impacts on wheat canopy damage',
        f'Projected Septoria-related canopy damage varied across European wheat-growing grids and emissions pathways (Fig. 1). By 2071–2100, the harvested-area-weighted healthy-area-duration (HAD) deficit changed by {late_values[0]:+.2f}, {late_values[1]:+.2f} and {late_values[2]:+.2f} days per unit reference leaf area under SSP1–2.6, SSP2–4.5 and SSP5–8.5, respectively, relative to 1991–2020. The corresponding mid-century changes were {mid_values[0]:+.2f}, {mid_values[1]:+.2f} and {mid_values[2]:+.2f} days. These averages combine areas with increasing and decreasing simulated damage rather than a uniform continental response (Supplementary Table S9).',
        f'Under late-century SSP5–8.5, the European HAD deficit changed from {europe.reference_on_common:.2f} to {europe.future_on_common:.2f} days per reference leaf area; the three-climate-model change range was {europe.gcm_min:+.2f} to {europe.gcm_max:+.2f} days. A positive ensemble change covered {signs.loc["positive_ensemble","landuse_area_share_percent"]:.1f}% of the available reference wheat area. All three models agreed on greater damage across {signs.loc["positive_all_three_gcm","landuse_area_share_percent"]:.1f}% of area and less damage across {signs.loc["negative_all_three_gcm","landuse_area_share_percent"]:.1f}%; mixed signs occupied {signs.loc["mixed_gcm_sign","landuse_area_share_percent"]:.1f}%. The full-grid comparison therefore distinguishes the magnitude of the continental mean from the spatial extent of consistent change (Supplementary Fig. S19; Supplementary Table S15).',
        'Changes in disease occurrence, timing and severity',
        f'Symptom occurrence and disease magnitude responded differently to future climate (Fig. 2). The area-weighted frequency of flag-leaf symptoms before soft dough was {100*frequency.reference_on_common:.3f}% in the reference and {100*frequency.future_on_common:.3f}% under late-century SSP5–8.5, a change of {100*frequency.mean_change:+.3f} percentage points. Occurrence remained close to saturation, whereas symptom timing and canopy damage showed spatial contrasts. Mean reference-area-weighted canopy damage during grain filling changed from {100*severity.reference_on_common:.2f}% to {100*severity.future_on_common:.2f}%, or {100*severity.mean_change:+.2f} percentage points, with a climate-model range of {100*severity.gcm_min:+.2f} to {100*severity.gcm_max:+.2f} points. This functional-loss measure represents simulated damage severity across the grain-fill window (Supplementary Tables S9 and S13b).',
        f'Flag-leaf symptoms shifted {abs(onset.mean_change):.2f} days '+('earlier' if onset.mean_change<0 else 'later')+f' relative to flowering, with model-specific changes of {onset.gcm_min:+.2f} to {onset.gcm_max:+.2f} days. Onset measured from the fixed sowing date advanced by {abs(calendar_onset.mean_change):.2f} days, spanning {calendar_onset.gcm_min:+.2f} to {calendar_onset.gcm_max:+.2f} days across climate models (Fig. 2b,d). Flag-leaf symptoms occupied {100*symptom_fraction.reference_on_common:.2f}% of grain-fill days in the reference and {100*symptom_fraction.future_on_common:.2f}% in the future. Symptomatic grain-fill duration changed by {symptomatic.mean_change:+.2f} days, alongside a {grain.mean_change:+.2f}-day change in the crop window. Earlier calendar onset and greater canopy damage therefore coexisted with a modest change in grain-fill duration. Timing estimates condition on detectable symptoms in both paired seasons; occurrence estimates include symptom-free complete seasons (Supplementary Figs. S12 and S14).',
        'Environmental-region and country contrasts',
        'Environmental-region averages resolved strong contrasts within the continental response (Fig. 3a; Table 1). Under late-century SSP5–8.5, HAD-deficit changes were '+regional_summary+f'. Among the eight named environmental regions, the largest mean increase occurred in the {highest.environment_region} region and the smallest response in the {lowest.environment_region} region. The {highest.environment_region} change spanned {highest.gcm_min:+.2f} to {highest.gcm_max:+.2f} days across climate models, compared with {lowest.gcm_min:+.2f} to {lowest.gcm_max:+.2f} days in the {lowest.environment_region} region. Alpine, Pannonian and Black Sea cells were included alongside the five larger domains (Supplementary Tables S13a–c and S16).',
        f'Country aggregation likewise retained contrasting outcomes. Among the twelve country groups with the largest reference wheat area, late-century SSP5–8.5 HAD changes ranged from {low_country.mean_change:+.2f} days in {country_label(low_country.country)} to {high_country.mean_change:+.2f} days in {country_label(high_country.country)}. Their conditional yield responses differed in both sign and magnitude (Fig. 3b). The full set of country means and climate-model ranges includes all country-assigned wheat cells within the study domain, with calendar eligibility and valid-season coverage retained for each group (Supplementary Table S14).',
        'Conditional disease-related yield response',
        f'The reference canopy–yield coefficient translated the late-century SSP5–8.5 HAD change into a conditional yield change of {-1000*europe.mean_change*.018:+.1f} kg ha⁻¹ per unit reference upper-canopy leaf area. The three-climate-model range was {-1000*europe.gcm_max*.018:+.1f} to {-1000*europe.gcm_min*.018:+.1f} kg ha⁻¹ per reference LAI. At coefficients of 0.0141–0.0207 t ha⁻¹ per GLAI-day, the same canopy response produced a conversion range of {-1000*europe.mean_change*.0207:+.1f} to {-1000*europe.mean_change*.0141:+.1f} kg ha⁻¹ per reference LAI. These quantities express the disease-related yield-loss index under alternative physiological conversion assumptions (Fig. 3b; Supplementary Fig. S13).',
        'Published canopy–yield evidence demonstrated substantial transfer limitations. Eight treatment-mean contrasts across five genetic backgrounds gave leave-one-background-out relative-yield RMSE of 5.16 percentage points and R² of 0.247, but absolute-yield RMSE of 0.617 t ha⁻¹ and R² of −0.432. Only two contrasts had STB-specific exposure; the remaining six had yellow rust or mixed disease exposure. Severity-based treatment-response models also exceeded their training-mean benchmark errors. The conditional grid yield indices consequently express canopy-conversion sensitivity rather than validated field-yield forecasts or national production tonnages (Supplementary Figs. S9–S11; Supplementary Tables S5–S8). [[Parker2004|Foulkes2006]]',
        'Crop development counteracts the disease-weather contribution',
        'The diagnostic weather–crop decomposition identified opposing contributions to the late-century SSP5–8.5 canopy response (Fig. 4). On 5,731 supported paired seasons from 64 spatial draws at 62 cells, the disease-weather contribution was +9.00 HAD days per reference LAI and the crop-development contribution −6.36 days, leaving a net +2.64-day change. Crop development offset 70.6% of the weather contribution; the model-specific fractions ranged from 63.6% to 80.3%. All three models retained a positive weather contribution and a negative crop-development contribution. These diagnostic estimates retain the sampled population and its spatial Monte Carlo error, separately from the full-grid impact statistics (Supplementary Tables S12a,b).',
        'In that diagnostic sample, flowering and soft dough advanced by 26.77 and 26.64 days after sowing, while mean grain-fill duration changed little. The compensating crop-development term therefore combined altered leaf availability with earlier crop-window placement. A −2.78-day weather–crop interaction was allocated equally between the two Shapley contributions. The excluded 20 finite pairs had hybrid active-day weather outside the supported temperature range; all retained contributions shared the same paired support (Supplementary Fig. S16).',
        'Sensitivity and empirical support',
        'Fourteen structural, detection and canopy-conversion settings retained earlier symptoms and increased HAD deficit in all three climate models under late-century SSP5–8.5. In this diagnostic sample, mean symptom shifts spanned −5.46 to −1.54 days and HAD increases 0.63–2.80 days per reference LAI. This consistency concerned the selected model and prespecified settings rather than comprehensive future-epidemic uncertainty (Supplementary Fig. S15; Supplementary Table S10).',
        f'Pooled field evaluation gave symptom-onset interval-excess error of {model_onset.value:.2f} days versus {benchmark_onset.value:.2f} days for the phenology benchmark across {int(model_onset.records)} histories. The paired difference was {onset_difference.value:+.2f} days (95% grouped-bootstrap interval {onset_difference.lower95:.2f}–{onset_difference.upper95:.2f}). Across {int(model_severity.records):,} disease assessments from {int(model_severity.fields)} field seasons, severity RMSE was {model_severity.value:.2f} versus {benchmark_severity.value:.2f} percentage points, with model bias {bias.value:+.2f} points. The paired RMSE difference was {severity_difference.value:+.2f} points (95% interval {severity_difference.lower95:.2f}–{severity_difference.upper95:.2f}). Retained crop-stage predictions had station-held-out MAE of 8.02 days across 40,878 events. These evaluations support explicit separation of simulated climate responses from empirically demonstrated epidemic and yield prediction skill (Supplementary Figs. S18 and S20; Supplementary Tables S1–S4).'
    ]
    text['climate_results.txt']=climate
    text['field_results.txt']=[];text['baseline_results.txt']=[]
    text['discussion_field_and_limits.txt']=[
        'Discussion',
        'Climate change produced contrasting disease-related canopy responses across the European wheat domain. Grid-level simulation resolved where a positive continental average combined increasing and decreasing damage, while environmental and country summaries connected those responses to wheat-growing areas. Disease occurrence was close to saturated under the specified model, so additional presence alone carried little information about crop consequences. The more informative changes concerned symptom timing relative to flowering, functional-canopy loss and exposure during grain filling.',
        'The opposing weather and crop-development contributions provide an explanation within the coupled model for this spatial complexity. Crop development changes the availability of leaves and the seasonal weather encountered during the productive canopy window. The diagnostic decomposition indicates that a substantial compensating crop term can accompany more favorable disease weather. Earlier crop development under warming therefore need not imply a proportional change in disease-related grain loss. Climate–pathogen and crop–disease assessments establish the relevance of this interaction, while European yield research emphasizes the joint contribution of climate, genetics and agronomic management. [[Chaloner2021|Pequeno2024|Silva2026]]',
        'The geographic contrasts support environmental stratification of adaptation evaluation. Regions with greater simulated damage require joint assessment of crop-calendar adjustment, resistance and tolerance; regions with declining damage require equivalent scrutiny of the crop and disease timing that generates that decline. Country summaries help define the spatial scope of monitoring, but their values depend on the fixed wheat mask, imposed winter-wheat calendar and source-country grid assignment. National intervention rankings additionally require compatible cultivar, management, canopy and harvest observations.',
        'The conditional yield calculation exposes a critical measurement gap. Functional-canopy loss and disease percentage have different physiological meanings, while the HAD–yield relationship varies with genotype, leaf scope and integration window. The available published contrasts provide evidence for a canopy–yield relationship, but their absolute-yield transfer performs poorly and their disease exposures are mixed. Reference leaf area and fixed transfer coefficients consequently remain scenario assumptions. Simulated disease-related yield indices identify a pathway requiring evaluation rather than a quantified change in wheat tonnage. [[Parker2004|Foulkes2006|vanDenBerg2017]]',
        'The pooled evaluation also limits confidence in future epidemic magnitudes. The current model has greater symptom-onset error than the phenology benchmark, and quantitative severity predictions have a substantial negative bias. The occurrence comparison indicates high sensitivity with poorer specificity, consistent with near-saturated simulated symptom occurrence. Added developmental stages have sparse two-sided observations, including limited evidence for the grain-fill endpoint. Climate-model agreement and numerical completeness cannot resolve these empirical limitations. Parameter identification, humidity reconstruction, cultivar resistance, changing source abundance and future pathogen adaptation remain additional sources of uncertainty.',
        'For agricultural policy, the evidence supports coordinated crop-development, disease, functional-canopy and harvest monitoring across contrasting environmental regions. Cultivar and calendar trials need shared canopy-area definitions and compatible observation windows to distinguish exposure avoidance, resistance and yield tolerance. Connecting these observations to harvested wheat area would improve the production relevance of future disease assessments. Such coordinated evaluation is consistent with European objectives for resilient and sustainable agriculture; the present simulations do not measure the effectiveness of any specific intervention. [[McDonald2022|ECVision2025]]'
    ]
    text['methods.txt']=[
      'Methods','Study domain and climate forcing',
      'The study domain contains every positive-wheat-harvested-area cell in the European SPAM2020 registry at 0.25° resolution: 14,941 cells. A fixed GGCMI winter-wheat rainfed calendar is available for 14,932 cells; the remaining nine retain unavailable outcomes. The all-wheat area mask and imposed calendar define a management scenario, rather than an observed distribution of winter-wheat management. SPAM2020 harvested area supplies fixed weights throughout the analysis. The study-area and observation-location maps are provided in Supplementary Fig. S21. [[SPAM2020|GGCMIPhase32021]]',
      'Daily NEX-GDDP-CMIP6v2 forcing covers ACCESS-CM2, MPI-ESM1-2-HR and MRI-ESM2-0 under SSP1–2.6, SSP2–4.5 and SSP5–8.5. Harvest periods are 1991–2020, 2031–2060 and 2071–2100. All 810 annual model–scenario–year combinations simulate the entire land-use mask, corresponding to 12,094,920 calendar-eligible grid-seasons. Forcing uses the existing local alignment coefficients, with separate historical alignment for each SSP continuation. Daily series include the preceding calendar year for overwintering crop seasons. Source files, alignment coefficients and runtime configurations retain their checksums. [[NEXGDDPCmip6V2]]',
      'Disease-weather exposure uses daily temperature, humidity and rainfall with the retained synthetic intraday humidity reconstruction. This reconstruction approximates exposure from daily forcing and does not represent measured leaf wetness. The observation-supported temperature range and missing-weather criteria retain their existing definitions in the model specification.',
      'Crop development and disease representation',
      'The retained temperature–photoperiod–vernalization model determines wheat development from sowing through soft dough. Additional ordered thresholds represent upper-leaf appearance and unfolding, and a calibrated flowering proxy defines the grain-fill window. Leaf availability, development and seasonal exposure connect daily weather to the existing Septoria source, establishment, progression and symptom states. Disease-related functional loss is gated by symptom detection in the climate reporting operator. Model equations, parameter provenance and observation definitions are provided in the supplementary model specification and the 84-entry parameter inventory. [[SuffertSache2011|ShawRoyle1989|LovellCanopy2004|Baccar2011|Lovell2004]]',
      'Models retain their existing calibrated parameters. The reference upper-three-leaf LAI is nominally one, divided equally among final leaf ranks and scaled by unfolding. No cultivar-specific canopy area, future resistance change or local absolute-yield calibration is inferred. Predicted soft dough defines season completion; missing calendars, unsupported forcing and unreached endpoints remain explicit statuses. Invalid outcomes are unavailable values rather than zero disease or zero loss.',
      'Disease and canopy outcomes',
      'Occurrence is the indicator of detectable flag-leaf symptoms before soft dough. Its multi-year mean is the frequency of symptomatic simulated grid-seasons. First-symptom timing is measured relative to flowering and is unavailable when symptoms are not detected. Symptomatic grain-fill days count days with detectable flag-leaf symptoms within the flowering-to-soft-dough window. These endpoints describe model states rather than observed infection dates or future disease probabilities.',
      'HAD deficit integrates daily reference green canopy area multiplied by the assumed functional-loss fraction across the flag leaf and two leaves below it. The main window is flowering to soft dough (GS65–85); GS31–85 provides a wider-window sensitivity. The mean functional-loss fraction is lost HAD divided by reference HAD and represents reference-area-weighted canopy damage severity. This integrated canopy quantity differs from instantaneous lesion percentage and retains the model’s damage-to-function assumptions.',
      'Paired grid and spatial aggregation',
      'Each future harvest year is paired with the reference year at the corresponding index of the same 30-year period, climate model and SSP. A metric-specific pair is retained only if both outcomes are finite. For grid i, x_i is the mean valid paired difference with unavailable pairs contributing zero to the numerator, and z_i is the fraction of valid pairs among 30 years. The grid estimate is x_i/z_i. Reference and future means share the same valid pairs. Timing, occurrence and canopy outcomes therefore have their own documented support.',
      'For a domain indicator I_i and fixed harvested area w_i, the aggregate paired change is Σw_i I_i x_i / Σw_i I_i z_i. Estimates are calculated separately for each climate model before their three-model mean and range are reported. EEA 2016 boundaries assign environmental regions by wheat-cell centroid intersection, retaining unassigned and outside-region categories. Country groups use each cell’s dominant SPAM source-country label; cross-border cells are not divided among countries. Country estimates refer only to the represented study domain. All eight named environmental regions and all country groups remain in Source Data. [[EEA2016]]',
      'Maps display complete three-climate-model estimates at native 0.25° pixels, with no interpolation or missing-value filling. Sign-area shares use the exact fixed harvested-area weights over cells with complete estimates. Three-model ranges describe deterministic scenario spread. A full land-use census has no spatial-sampling Monte Carlo error; climate-model choice, biological parameters, observation error and canopy–yield conversion remain separate uncertainties. The twelve country groups shown in Fig. 3 are selected by reference wheat area before considering projected effects.',
      'Conditional yield response',
      'Conditional disease-related yield change is −b times the paired HAD-deficit change. The reference coefficient is 0.018 t ha⁻¹ per GLAI-day, with 0.0141 and 0.0207 used as fixed conversion alternatives from the published top-three-canopy study. Reported kg ha⁻¹ values multiply the t ha⁻¹ result by 1,000 and retain the nominal reference LAI denominator. The coefficients span cultivar predictions rather than a probability interval. Actual field-yield percentage changes and national production tonnages require compatible canopy area and grain-yield validation and are not identified by this operator. [[Parker2004|Foulkes2006]]',
      'Diagnostic decomposition and sensitivity',
      'The weather–crop decomposition and fourteen-setting sensitivity analysis retain the prespecified 64 area-proportional draws at 62 unique cells. Four trajectories combine reference or future disease weather with reference or future crop-development trajectories. Shapley contributions share the weather–crop interaction equally and sum to the common-support net. The supported decomposition excludes 20 of 5,751 finite pairs with an active hybrid forcing day outside the supported temperature range, leaving 5,731 pairs. Its spatial Monte Carlo standard errors describe the sampled diagnostic population and are distinct from full-grid impact estimates.',
      'The crop-development offset is −100 times the crop Shapley contribution divided by the weather contribution on identical support. The ensemble percentage uses the ratio of three-model mean contributions. Sensitivity settings vary structural, detection, reference-canopy and functional-conversion assumptions within the selected model. These comparisons evaluate model-response dependence and do not estimate the efficacy of a management intervention.',
      'Pooled field evaluation',
      'Evaluation records from the two public field archives are pooled after the existing calibration and geographic eligibility restrictions. Calibration records retain their separate cohort. Evaluation contains 2,033 numerical assessments from 188 field seasons in 140 coordinate-years and 136 two-sided source-leaf-1–3 onset histories from 78 field seasons in 62 coordinate-years. Source identities, units, assessment conventions and leaf semantics remain in the evidence files. Source-defined percentages retain their original denominators, and source leaf numbers do not establish a universal final-rank mapping. [[Holst2022BASF|HolstDonner2022Corteva]]',
      'Scores give equal weight to coordinate-years, fields within coordinate-years, source leaves within fields and assessments within leaves. Symptom-onset error is distance outside the genuine two-sided observed interval, retaining the predefined missed-positive penalty. Disease magnitude is evaluated against the existing calibration-leaf-mean benchmark; symptom timing and detection use the calibration-selected phenology benchmark. Fixed model and benchmark predictions are paired on identical records. Bootstrap intervals use 20,000 intact coordinate-year resamples and describe uncertainty conditional on the fitted predictions and reused retrospective data. Duplicate coordinate-year identities are grouped together across archives.',
      'The retained crop-development formulation is evaluated on 40,878 matched German station-held-out events at BBCH 10, 31, 51 and 85. Added stages use pooled field observation intervals and separate calibration evidence. Published canopy–yield evaluation retains all eight treatment-mean contrasts across five genetic backgrounds, including STB, yellow-rust and mixed exposures; leave-one-background-out fitting gives backgrounds equal evaluation weight. Severity-based yield transfer retains its independent trial or year splits and training-mean comparators. [[Foulkes2006]]',
      'Reproducibility',
      'Each annual output retains its forcing identities, frozen-runtime configuration, land-use-cell order, numerical checks and output checksum. Aggregation records source hashes, metric-specific pair counts and domain coverage. Independent checks recompute pooled evaluation and selected full-grid domain ratios from the underlying records. Source Data contains the values displayed in figures and tables. The accompanying software archive regenerates the manuscript from completed numerical evidence; climate-forcing-based simulation additionally requires the external raw climate products.'
    ]
    text['supplementary_methods.txt']=[
      'Supplementary Methods','Numerical scope and outcome definitions',
      'Full-grid impact results retain 14,941 fixed wheat land-use cells and 14,932 eligible crop calendars. Disease occurrence, timing, damage severity, HAD deficit and conditional yield products use their respective paired valid populations. Invalid seasons retain unavailable outcomes. The full-grid reference registry includes SPAM dominant-country assignment and independent EEA centroid-region assignment; unassigned and outside-region cells remain explicit.',
      'The symptom-frequency indicator equals one for a detectable flag-leaf symptom before soft dough and zero for a symptom-free complete season. The canopy-severity proxy is the flowering-to-soft-dough HAD deficit divided by reference HAD, expressed as a percentage. It integrates reference-area-weighted functional loss and does not reproduce an observed lesion-area percentage. Mean timing conditions on detected symptoms, whereas frequency includes complete symptom-free seasons.',
      'Aggregation and coverage',
      'Grid paired means use corresponding harvest-year indices within each climate model and SSP. Domain means divide the exact harvested-area-weighted paired-change numerator by the valid area-time denominator. Reference and future means are computed on the same support. Model ranges span three independently aggregated domain estimates. Exact area weights remove spatial sampling error from the full-grid census; sampled diagnostic decompositions retain their separate Monte Carlo uncertainty.',
      'Pooled crop and disease evaluation',
      'The pooled evaluation contains only the existing noncalibration disease partitions and the geographically eligible external observations. Record membership and source conventions remain recoverable in the accompanying data. The original source labels are retained for traceability while evaluation tables and figures combine their eligible records. Calibration and evaluation share no field identifiers. Coordinate-year identities remain geographic grouping keys, so overlapping keys would not create independent replicates.',
      'For each endpoint, the evaluation weight is the reciprocal of the number of coordinate-years, multiplied by the reciprocals of fields, source leaves and records within each parent group. RMSE is the square root of the resulting weighted mean squared error. Paired bootstrap resampling draws entire coordinate-year groups, retaining both predictions and all field, leaf and date records. Twenty thousand resamples with seed 20261008 give 95% percentile intervals. These intervals exclude parameter-selection uncertainty and independently unverified biological-site identity.',
      'Upper-leaf onset comparisons retain genuine two-sided histories and predefined missing-positive penalties. Field developmental-stage evaluation retains two-sided observation intervals; their centers locate displayed symbols and are not used as exact observed dates. Calibration profiles and fully nested selection remain separate from pooled evaluation. Public station data evaluate the retained phenology formulation, while added upper-leaf stages and soft dough have limited informative field evidence.',
      'Conditional canopy–yield interpretation',
      'Published protected and unprotected canopy and yield means retain their leaf scope, integration window, cultivar and disease exposure. Eight means across five backgrounds remain in the top-five-canopy holdout; two are STB-specific, two yellow-rust-specific and four have mixed exposure. The absolute and relative response scores evaluate aggregate treatment means with shared published model fitting. No raw plots, covariance or unreported functional-area trajectories are reconstructed.',
      'The full-grid yield index is a deterministic conversion of HAD deficit under a nominal upper-three-leaf reference LAI. The three fixed coefficients and GS31–85 versus GS65–85 windows quantify scenario dependence. They are not confidence bounds or a validated estimate of total disease-related production loss.',
      'Diagnostic weather–crop contributions',
      'The four-corner weather–crop decomposition retains the existing sampled trajectories and their common valid-pair mask. Twenty unsupported hybrid-temperature pairs are excluded before the latest HAD decomposition. Weather and crop contributions include one half of the interaction each and sum to the supported net. Crop offsets use identical numerator and denominator populations. Regional decomposition outputs from the prior sampled analysis remain archived for provenance and are not substituted for full-grid regional impact statistics.',
      'Reporting populations',
      'The main climate figures summarize completed full-grid runs. The decomposition and structural sensitivity figures summarize the frozen 64-draw diagnostic sample. Pooled evaluation figures summarize reused retrospective field observations, and published yield figures summarize aggregate treatment contrasts. These populations evaluate distinct quantities; their counts and accuracy scores are not combined into an overall model-performance percentage.'
    ]
    text['availability.txt']=[
      'Data availability',
      'Public field disease archives, NEX-GDDP-CMIP6v2 forcing, GGCMI calendars, SPAM2020 wheat area and EEA environmental boundaries are identified by dataset references. Source_Data.xlsx contains the completed full-grid climate summaries, environmental and country statistics, exact sign-area shares, pooled evaluation populations and published canopy–yield evidence. Source labels and assessment conventions remain in the underlying records. [[Holst2022BASF|HolstDonner2022Corteva|NEXGDDPCmip6V2|GGCMIPhase32021|SPAM2020|EEA2016]]',
      'The software archive contains grid-level paired summaries, completion receipts, output hashes and numerical evidence required for publication regeneration. Raw daily climate products and all annual simulation outputs remain external because of their size; forcing-based reproduction requires the recorded source products and alignment files. Unavailable raw plot observations and functional-canopy measurements remain unavailable.',
      'Code availability',
      'Software_and_Evidence.zip contains the simulation and reporting source code, pooled-statistics code, document-generation code and evidence manifests. REPRODUCIBILITY.txt distinguishes document regeneration from forcing-based runtime execution. The supplementary model specification contains 29 numbered equations, and Parameter_inventory.csv records 84 fixed, fitted and scenario quantities.'
    ]
    text['declarations.txt']=old['declarations.txt']
    return text
