"""Climate-impact manuscript supported by the completed census and pooled scores."""
import pandas as pd
from .data import HERE,ROOT,GRID,DERIVED,CANOPY,SEVERITY,ONSET,FREQUENCY,YIELD,SCENARIOS,REGIONS,pooled,grid_data
from analysis.paper_study.nature_food_submission_20261008.sections import (
    sections as previous_sections,AUTHOR,AFFILIATION,EMAIL)

TITLE='Wheat phenology partly offsets projected increases in Septoria damage across Europe'


def sections():
    old=previous_sections();_,regions,countries=grid_data()
    from analysis.paper_study.food_security_exposure_20261009.exposure import read as read_exposure
    from .timing import read as read_timing
    exposure=read_exposure()['domain_summary'].query("analysis_mode == 'primary_any_paired_year'")
    late_exposure=exposure[exposure.scenario.eq('ssp585')&exposure.period.eq('2071-2100')]
    production=late_exposure[late_exposure.domain_type.eq('Europe')].iloc[0]
    production_low=exposure[exposure.domain_type.eq('Europe')&exposure.scenario.eq('ssp126')&exposure.period.eq('2071-2100')].iloc[0]
    production_regions=late_exposure[late_exposure.domain_type.eq('environment_region')].set_index('domain')
    timing=read_timing();timing=timing[timing.environment_region.eq('Europe')].set_index('event')
    def regional(name,metric,scenario='ssp585',period='2071-2100'):
        return regions[regions.environment_region.eq(name)&regions.metric.eq(metric)&regions.scenario.eq(scenario)&regions.period.eq(period)].iloc[0]
    europe=regional('Europe',CANOPY)
    severity=regional('Europe',SEVERITY);onset=regional('Europe',ONSET);frequency=regional('Europe',FREQUENCY)
    env=regions[regions.environment_region.isin(REGIONS)&regions.metric.eq(CANOPY)&regions.scenario.eq('ssp585')&regions.period.eq('2071-2100')].sort_values('mean_change')
    lowest=env.iloc[0];highest=env.iloc[-1]
    regional_clauses=[f'{regional(name,CANOPY).mean_change:+.2f} days in the {name} region' for name in ['Atlantic','Continental','Boreal','Mediterranean','Steppic']]
    regional_summary=', '.join(regional_clauses[:-1])+', and '+regional_clauses[-1]
    signs=pd.read_csv(GRID/'canopy_change_sign_area_shares.csv')
    signs=signs[signs.scenario.eq('ssp585')&signs.period.eq('2071-2100')].set_index('classification')
    model_onset=pooled('symptom_onset','model');benchmark_onset=pooled('symptom_onset','benchmark')
    onset_difference=pooled('symptom_onset','difference')
    model_severity=pooled('severity','model_rmse');benchmark_severity=pooled('severity','benchmark_rmse')
    severity_difference=pooled('severity','rmse_difference');bias=pooled('severity','model_bias')
    abstract=(
        'Septoria tritici blotch threatens European wheat production as climate change alters conditions for disease. '
        'How crop phenology modifies regional disease impacts and the wheat production exposed to them remains unresolved. '
        'We combined phenology–disease modelling, field evaluation and fixed wheat-production weights across Europe under three climate models and emissions pathways. '
        f'Under SSP5–8.5 in 2071–2100, normalized loss of healthy-area duration during grain filling increased by {europe.mean_change:.2f} days relative to 1991–2020, '
        f'with all three models agreeing on increasing damage in cells representing {production.all3positive_share_baseline_pct:.1f}% of baseline wheat production. '
        'Continental production exposure was nearly six times that of the Boreal region. '
        'Shifts in wheat phenology offset an estimated 71% of the increase in canopy damage attributable to weather. '
        'However, disease and yield-response predictions did not consistently outperform benchmarks. '
        'These conditional projections identify regional priorities for monitoring and field trials; harvested-yield losses and adaptation benefits require compatible canopy-function and grain-yield observations.')
    if len(abstract.split())>150:raise ValueError('Abstract exceeds 150 words.')
    text={'abstract.txt':[abstract]}
    text['introduction.txt']=[
        'Wheat production under climate change depends on both crop performance and losses caused by disease. Septoria tritici blotch (STB), caused by Zymoseptoria tritici, damages wheat leaves and can reduce grain yield. Temperature, rainfall and humidity affect disease development, while changing climate also alters the crop that the pathogen infects. Understanding these linked effects is important for maintaining European wheat production. [[Savary2019|Parker2004|Silva2026]]',
        'Weather favourable for infection does not by itself determine yield loss. Wheat phenology, including the timing of upper-leaf emergence, flowering and grain filling, determines which leaves are exposed and when they support grain growth. Disease progression determines when those leaves become damaged. A shift in either process changes the amount of healthy canopy available during grain filling. Climate assessments based only on infection conditions can therefore miss changes in the timing of damage relative to crop phenology. [[Chaloner2021|Pequeno2024|ShawRoyle1989|LovellCanopy2004|Lovell2004]]',
        'For Septoria tritici blotch, symptoms follow a period of infection and disease development within the leaf. Rainfall, moisture conditions, inoculum availability and canopy development influence the seasonal epidemic. Upper-leaf appearance and unfolding are relevant because damage to these leaves can affect the canopy supporting grain filling. Healthy-area duration (HAD), the integral of healthy leaf area over time, provides a measure linking disease damage to crop function. Its relationship with grain yield varies among cultivars and depends on the leaves and growth stages included in the calculation. [[SuffertSache2011|Baccar2011|Parker2004|Foulkes2006|vanDenBerg2017|Bryson1997]]',
        'The unresolved question is how climate-driven crop timing modifies disease damage and the production exposed to it. A linked phenology–disease model describes canopy responses across the complete European wheat grid under three emissions pathways. Field observations evaluate predictive support, fixed production weights identify regional exposure, and a weather–phenology decomposition separates opposing model responses. These quantities distinguish where disease pressure changes from how much wheat production those locations represent. Published canopy–yield relationships provide a supplementary conditional index; physiological grain loss remains a separate validation target.',
    ]
    late_values=[regional('Europe',CANOPY,s).mean_change for s in SCENARIOS]
    mid_values=[regional('Europe',CANOPY,s,'2031-2060').mean_change for s in SCENARIOS]
    climate=[
        'Results','Predictive support differs among model components',
        'The retained wheat-phenology formulation predicted 40,878 matched German station-test events with mean absolute error of 8.02 days, compared with 12.07 days for thermal time alone (Fig. 1a). The station split evaluates spatial transfer under observed weather and known sowing dates; calendar years were not held out. Support for the subsequently added upper-leaf stages and flowering-to-soft-dough window was more limited. The disease-field evaluation contained only five two-sided soft-dough observation intervals, with mean interval-excess error of 10.50 days (Supplementary Fig. S18; Supplementary Tables S1 and S2).',
        f'Disease predictions did not improve consistently on calibration-selected benchmarks (Fig. 1b,c). Mean symptom-onset error was {model_onset.value:.2f} days versus {benchmark_onset.value:.2f} days across {int(model_onset.records)} histories; the paired excess was {onset_difference.value:+.2f} days (95% coordinate-year bootstrap interval {onset_difference.lower95:.2f}–{onset_difference.upper95:.2f}). Severity RMSE was {model_severity.value:.2f} versus {benchmark_severity.value:.2f} percentage points across {int(model_severity.records):,} assessments from {int(model_severity.fields)} field seasons. Model bias was {bias.value:+.2f} points, and the paired RMSE-difference interval included zero ({severity_difference.lower95:.2f}–{severity_difference.upper95:.2f}). These retrospective comparisons exclude calibration records but retain uncertainty associated with prior model development (Supplementary Fig. S20; Supplementary Table S3).',
        'Independent field environments also showed limited transfer of severity-based yield responses (Fig. 1d). Across five Nordic trials, endpoint severity gave held-out RMSE of 4.83 percentage points versus 5.02 for the training mean. Across two Tunisian years, the two-leaf model gave 3.32 t ha⁻¹ versus 3.24. Across five German locations, endpoint severity gave 18.51 percentage points versus 18.48 on 3,264 cultivar–management comparisons. Assessment-stage information improved Nordic error in a smaller subset, but uncertainty included no improvement and three of four fitted conditional slopes opposed a monotone damage response. German management covariates explained more predictive variation than endpoint severity. These datasets evaluate yield associations or management responses and do not validate physiological STB-attributable grain loss (Supplementary Figs. S22–S24; Supplementary Tables S17–S20). [[NFTS2026|BenMbarek2020|BRIWECS2025]]',
        'An additional audit identified 948 unique plot harvests, comprising 724 Swiss plots from ten site-years at five locations and 224 French plots from one site-year. In an exploratory Swiss location-held-out analysis, ordinal STB ratings gave yield RMSE of 0.926 t ha⁻¹ versus 1.142 for the training mean. Adding STB ratings to cultivar-composition and management predictors reduced RMSE from 0.914 to 0.877 t ha⁻¹, but five-site resampling showed unstable improvement. The French source lacked independent environmental replication. Neither source contained a compatible functional-canopy time series or an identified STB-specific yield counterfactual. These results extend statistical yield evidence without establishing end-to-end grain-loss validation (Fig. 1d; Supplementary Tables S24 and S25). [[SwissMixtures2023|FrenchMixtures2021]]',
        'Published canopy–yield contrasts likewise provided partial support. Leaving each of five genetic backgrounds out of fitting gave relative-yield RMSE of 5.16 percentage points and R² of 0.247, but absolute-yield R² of −0.432 across eight treatment-mean contrasts. Only two contrasts involved STB alone. The linear conversion from normalized HAD loss to yield therefore remains a conditional index, retained in the supplementary evidence (Supplementary Figs. S9–S11 and S13; Supplementary Tables S5–S8). [[Parker2004|Foulkes2006]]',
        'Climate change redistributes canopy damage',
        f'Projected canopy damage increased on average while differing in sign among wheat-growing regions (Fig. 2). By 2071–2100, harvested-area-weighted normalized loss of healthy-area duration (HAD) changed by {late_values[0]:+.2f}, {late_values[1]:+.2f} and {late_values[2]:+.2f} days under SSP1–2.6, SSP2–4.5 and SSP5–8.5, respectively, relative to 1991–2020. Mid-century changes were {mid_values[0]:+.2f}, {mid_values[1]:+.2f} and {mid_values[2]:+.2f} days. Normalized HAD loss is the time-integrated loss of assumed functional green leaf area divided by maximum reference upper-canopy LAI, expressed as equivalent days of canopy function lost during flowering to soft dough (Supplementary Fig. S25; Supplementary Table S9).',
        f'Under late-century SSP5–8.5, European normalized HAD loss increased from {europe.reference_on_common:.2f} to {europe.future_on_common:.2f} days; climate-model changes spanned {europe.gcm_min:+.2f} to {europe.gcm_max:+.2f} days. The ensemble indicated increasing damage across {signs.loc["positive_ensemble","landuse_area_share_percent"]:.1f}% of available reference wheat area. All three models agreed on an increase across {signs.loc["positive_all_three_gcm","landuse_area_share_percent"]:.1f}% and a decrease across {signs.loc["negative_all_three_gcm","landuse_area_share_percent"]:.1f}%; signs differed across {signs.loc["mixed_gcm_sign","landuse_area_share_percent"]:.1f}% (Fig. 2b; Supplementary Table S15). Model agreement measures consistency among climate projections, rather than predictive validation.',
        f'Area-weighted regional changes were '+regional_summary+f'. The largest mean increase therefore occurred in the Boreal region. Relative HAD loss increased from {100*severity.reference_on_common:.2f}% to {100*severity.future_on_common:.2f}% across Europe, whereas symptom occurrence remained close to saturation ({100*frequency.reference_on_common:.2f}% and {100*frequency.future_on_common:.2f}%). Symptom presence alone consequently distinguished little of the projected change in accumulated canopy damage (Supplementary Figs. S14 and S27; Supplementary Tables S13 and S16).',
        'Crop timing moderates weather-driven damage',
        'First symptoms relative to flowering provide the primary timing reference because crop development determines the period in which damaged leaves support grain growth (Fig. 3a). The full-grid map describes this alignment; the sampled attribution distinguishes weather and phenology contributions to canopy damage.',
        f'On identical complete historical–future season pairs, symptoms advanced by {abs(timing.loc["symptom_days","change"]):.2f} days after sowing, flowering by {abs(timing.loc["flowering_days","change"]):.2f} days and soft dough by {abs(timing.loc["soft_dough_days","change"]):.2f} days under late-century SSP5–8.5 (Supplementary Fig. S26a). Symptoms therefore advanced by {abs(timing.loc["symptom_relative_flowering_days","change"]):.2f} days relative to flowering. The elapsed flowering-to-soft-dough interval changed by {timing.loc["grain_fill_elapsed_days","change"]:+.2f} days. The much larger advance after sowing mostly accompanied earlier crop development, rather than an equally large shift in disease timing within grain filling (Supplementary Table S22).',
        'In the separate 62-cell diagnostic sample, the weather contribution increased normalized HAD loss by 9.00 days, while wheat phenology reduced it by 6.36 days, giving a net increase of 2.64 days (Fig. 3b). The ratio of ensemble contributions corresponds to a 70.6% offset, with individual climate-model offsets of 63.6–80.3%. The calculation retains 5,731 valid season pairs and allocates the −2.78-day weather–phenology interaction equally between the two Shapley contributions. Its net estimate is close to the full-grid change, although the populations differ. This decomposition identifies opposing responses within the model; it does not estimate avoided yield loss or the effectiveness of changing sowing date or cultivar (Supplementary Fig. S16; Supplementary Tables S12a,b).',
        'The phenology offset also differed among sampled regions (Fig. 3c). It was 39.1% in the Boreal region, 63.6% in the Continental region and 160.4% in the Mediterranean region. Values above 100% denote a phenology contribution larger than the positive weather contribution, producing a negative net change. These regional diagnostic samples contained 14, 18 and nine draws, respectively. Alpine and Black Sea regions had no draws, and Pannonian had one; regional sampling gaps prevent a complete attribution census (Source Data).',
        'Production exposure changes regional priorities',
        f'The fixed SPAM2020 wheat-production baseline contained {production.baseline_production_tonnes/1e6:.2f} million tonnes within the study domain (Fig. 4; Table 1). Under late-century SSP5–8.5, cells with increasing ensemble-mean damage represented {production.ensemble_increasing_production_tonnes/1e6:.2f} million tonnes ({production.ensemble_increasing_share_baseline_pct:.1f}% of baseline production). Cells with increases in all three climate models represented {production.all3positive_production_tonnes/1e6:.2f} million tonnes ({production.all3positive_share_baseline_pct:.1f}%). These amounts quantify the baseline production located in exposed cells; they are neither projected production nor tonnes lost.',
        f'The Continental region contained {production_regions.loc["Continental","baseline_production_tonnes"]/1e6:.2f} million tonnes of baseline production, compared with {production_regions.loc["Boreal","baseline_production_tonnes"]/1e6:.2f} million tonnes in the Boreal region. Production in cells with unanimous projected increases was {production_regions.loc["Continental","all3positive_production_tonnes"]/1e6:.2f} and {production_regions.loc["Boreal","all3positive_production_tonnes"]/1e6:.2f} million tonnes, respectively. The region with the largest damage increase per unit canopy thus differed from the region with the greatest production exposure. Surveillance and validation priorities depend on both impact intensity and the amount of production represented, while cells with differing model signs warrant observation of the direction of change (Fig. 4a,b).',
        f'Exposure did not increase monotonically under stronger forcing (Fig. 4c). Ensemble-increase exposure was {production_low.ensemble_increasing_production_tonnes/1e6:.2f} million tonnes under SSP1–2.6 and {production.ensemble_increasing_production_tonnes/1e6:.2f} million tonnes under SSP5–8.5. In contrast, unanimous-increase exposure rose from {production_low.all3positive_production_tonnes/1e6:.2f} to {production.all3positive_production_tonnes/1e6:.2f} million tonnes, while production-weighted HAD-loss change rose from {production_low.production_weighted_change:.2f} to {production.production_weighted_change:.2f} days. The geographic extent of positive mean responses, their intensity and agreement among climate models are therefore distinct indicators; a smaller exposed footprint does not imply less damage.',
        f'Production-weighted European HAD-loss change was {production.production_weighted_change:+.2f} days, with climate-model values from {production.gcm_min:+.2f} to {production.gcm_max:+.2f} days. Fixed production weights describe the present geography of exposure under alternative climate pathways (Fig. 4c). They exclude future shifts in cropped area, yield, trade, irrigation and crop type. The imposed winter-wheat rainfed calendar applies to the all-wheat mask, so the estimates remain scenario-specific even where climate models agree. Country production exposure uses fractional source-country contributions within border cells (Supplementary Table S21; Source Data).',
        'All fourteen tested combinations of model structure, symptom detection and canopy assumptions gave increased HAD loss under late-century SSP5–8.5, with ensemble increases spanning 0.63–2.80 days. This more than fourfold variation in magnitude limits quantitative interpretation despite agreement in the direction of the European mean. Climate-model ranges, selected structural sensitivities and grouped field-evaluation intervals describe different uncertainties and cannot be combined into a single confidence interval for future grain loss (Supplementary Fig. S15; Supplementary Table S10).',
    ]
    text['climate_results.txt']=climate
    text['field_results.txt']=[];text['baseline_results.txt']=[]
    text['discussion_field_and_limits.txt']=[
        'Discussion',
        'Climate-driven changes in wheat phenology can offset much of the increase in Septoria damage attributable to weather, while leaving a positive European mean and contrasting regional responses. Earlier symptoms after sowing largely accompany earlier crop development; their shift relative to flowering is considerably smaller. Consequently, infection-favourable weather and symptom occurrence alone provide incomplete measures of the disease impact during grain filling. This mechanism remains conditional on the model structure and its observed predictive limitations. [[Chaloner2021|Pequeno2024]]',
        'Production exposure adds a decision-relevant dimension to the regional damage gradient. Boreal wheat has the largest mean canopy-damage increase, whereas the greater production represented in the Continental region increases the scale of its exposure. A surveillance network organized only by the largest per-area change would miss this distinction. Joint consideration of baseline production, damage direction and climate-model disagreement supports selection of regional monitoring and field-validation sites. It does not supply a quantitative estimate of food shortages, trade disruption or grain lost.',
        'The immediate policy implication is differentiated investment in evidence and preparedness. Regions combining substantial production with consistent projected increases are candidates for coordinated disease surveillance and testing of crop resistance and phenology. Regions with model disagreement require observations that resolve whether seasonal exposure is rising or falling. Declining Mediterranean disease pressure does not establish improved wheat productivity because heat and water stress can reduce grain yield independently. These priorities remain conditional on an all-wheat production baseline represented by a winter-wheat rainfed calendar; winter and spring wheat and irrigated systems require separate evaluation before operational targeting. [[ECVision2025]]',
        'Climate-driven phenological escape is not equivalent to an achievable adaptation benefit. Earlier crop development can change disease exposure while also changing canopy duration, pre-anthesis growth, heat exposure and water use. A useful adaptation comparison therefore requires grain yield and resource outcomes under feasible sowing dates, cultivar maturity and resistance, with each disease scenario paired to the same climate and management without disease. Baseline disease loss, future disease loss and their difference are distinct endpoints. Net benefits additionally depend on implementation costs and production variability. The 70.6% phenology offset cannot be interpreted as yield protected by an intervention. [[McDonald2022|Bancal2007|Bancal2015]]',
        'The largest evidential gap concerns the conversion from disease to harvested grain. Endpoint lesion scores, time-integrated functional canopy loss and grain yield differ in their biological meaning. The model assumes a reference upper-three-leaf canopy and a damage-to-function relationship; it lacks a complete crop carbon balance and observed senescence trajectory. Published HAD–yield coefficients concern a wider stage interval than the primary climate calculation, and the small cross-background evaluation contains predominantly mixed diseases. Additional endpoint-yield datasets increase the evidence for statistical associations but cannot reconstruct missing canopy trajectories. Independent environments with matched crop stages, repeated disease observations, functional green leaf area and grain yield are needed to test the full prediction chain. [[Parker2004|Foulkes2006|vanDenBerg2017|Bregaglio2021]]',
        'Disease prediction itself also constrains confidence in the projected magnitudes. Symptom-onset error exceeded that of the phenology benchmark, and numerical severity was underestimated. High sensitivity with low specificity is consistent with the near-universal symptom occurrence in the climate experiment. Reconstructed humidity, fixed biological and management assumptions, sparse observations of added crop stages and climate-model selection contribute further uncertainty. Emissions-pathway contrasts and regional exposure identify hypotheses and priorities for validation; they do not establish optimized sowing advice, fungicide-reduction targets or production benefits from adaptation.',
    ]
    text['methods.txt']=[
        'Methods',
        'Wheat-growing area and climate data',
        'The European SPAM2020 all-wheat registry contains 14,941 cells with positive harvested wheat area at 0.25° resolution. A fixed GGCMI winter-wheat rainfed calendar is available for 14,932 cells; nine cells have unavailable simulation outcomes. The all-wheat area mask combined with a winter-wheat rainfed calendar defines the crop-management scenario. It is not a census of observed winter-wheat management. Harvested area provides fixed weights for spatial aggregation. Supplementary Fig. S21 shows the study area, field-observation locations and environmental regions. [[SPAM2020|GGCMIPhase32021]]',
        'Daily NEX-GDDP-CMIP6v2 data represent ACCESS-CM2, MPI-ESM1-2-HR and MRI-ESM2-0 under SSP1–2.6, SSP2–4.5 and SSP5–8.5. The harvest periods are 1991–2020, 2031–2060 and 2071–2100. The 810 model–scenario–year combinations cover 12,094,920 calendar-eligible grid-seasons. Monthly adjustment coefficients align climate variables with the reference weather data, with separate historical adjustments for each SSP continuation. Daily series include the preceding calendar year to represent overwintering seasons. Input files, adjustment coefficients and model configurations are identified by checksums. [[NEXGDDPCmip6V2]]',
        'Disease calculations use daily temperature, relative humidity and rainfall. A synthetic reconstruction of humidity within each day estimates moisture exposure from daily forcing; it does not supply measured leaf wetness. Missing weather and daily mean temperatures above 40 °C produce unavailable outcomes under the model input rules.',
        'Linking wheat phenology to Septoria disease',
        'A temperature–photoperiod–vernalization model calculates wheat phenological stages from sowing to soft dough. Additional ordered developmental thresholds determine upper-leaf appearance and unfolding, and a calibrated flowering threshold defines the start of the grain-filling interval. These crop trajectories determine which leaves are available to infection and the seasonal weather experienced by each leaf. The Septoria module calculates disease establishment, progression and visible damage using weather and these leaf trajectories. Disease damage does not alter the calculated crop-development trajectory. Model equations, parameter sources and observation definitions appear in the supplementary model specification and the 84-entry parameter inventory. [[SuffertSache2011|ShawRoyle1989|LovellCanopy2004|Baccar2011|Lovell2004]]',
        'Calibrated parameters remain fixed across climate scenarios. The maximum reference LAI of the upper three leaves is one, divided equally among leaves and scaled by unfolding. Cultivar-specific canopy area and future changes in resistance are not estimated. Soft dough marks season completion. Missing crop calendars, invalid weather and failure to reach the endpoint remain separate unavailable outcomes, rather than zero disease or zero loss.',
        'Symptoms, canopy damage and healthy-area duration',
        'Symptom frequency is the fraction of complete simulated seasons with detectable flag-leaf symptoms before soft dough. First-symptom timing is measured relative to flowering or sowing and is unavailable when symptoms are not detected. Symptomatic grain-fill days count days with detectable flag-leaf symptoms between flowering and soft dough. Symptoms are visible model states following disease development; their dates are distinct from the modelled dates of initial infection.',
        'The disease-damage fraction after symptom detection is treated as the fraction of reference leaf area that has lost function. This assumption connects modelled disease to canopy damage. HAD loss integrates this fraction multiplied by daily reference leaf area across the flag leaf and two leaves below it. The primary interval is flowering to soft dough (GS65–85), with GS31–85 used for sensitivity analysis. HAD and disease-induced HAD loss have units of green leaf area index multiplied by days (GLAI-days). Normalized HAD loss divides the time-integrated functional loss by maximum reference upper-canopy LAI and expresses it as equivalent days of reference canopy function lost. With reference LAI equal to one, normalization leaves numerical values unchanged. Relative HAD loss is HAD loss divided by reference HAD, expressed as a percentage; it describes average accumulated canopy-function loss, not instantaneous lesion percentage. [[Parker2004|vanDenBerg2017]]',
        'Flowering provides a reference for grain filling rather than the start of disease simulation or a universal crop-protection threshold. Disease calculations begin during crop establishment and include upper-leaf appearance and unfolding before flowering. Stem extension and upper-leaf emergence define earlier exposure relevant to canopy protection. The GS65–85 integral describes grain-filling canopy damage; it does not quantify every effect of pre-flowering disease on grain number or assimilate reserves. [[Parker2004|Bancal2007]]',
        'Historical–future comparisons and spatial summaries',
        'Each future harvest year is paired with the corresponding position in the 30-year historical period for the same climate model and SSP. This indexing supports comparisons of period means without identifying historical and future years as the same physical event. A pair is included only when both metric values are finite. For grid i, x_i is the sum of valid paired differences divided by 30, and z_i is the number of valid pairs divided by 30. The grid mean change is x_i/z_i. Reference and future means use the same valid pairs. The valid seasons may differ among symptom timing, symptom frequency and canopy metrics.',
        'For domain indicator I_i and fixed harvested area w_i, the mean change is Σw_i I_i x_i / Σw_i I_i z_i. Separate estimates for each climate model give the reported three-model mean and range. EEA 2016 boundaries assign environmental regions from wheat-cell centroids. Country assignment uses the dominant SPAM source-country label of each cell; cross-border cells are not divided among countries. Country estimates apply only to represented wheat cells within the study domain. Source Data includes all eight named environmental regions, outside-region and unassigned cells, and all country groups. [[EEA2016]]',
        'Maps show model means at the native 0.25° grid resolution, without interpolation or filling unavailable cells. Area shares by direction of change use fixed harvested-area weights over cells with complete three-model estimates. Model ranges describe spread among three climate models and are not confidence intervals. All wheat cells are simulated, so full-grid estimates have no spatial-sampling Monte Carlo error. Other uncertainties include climate-model choice, model parameters, observations and the canopy–yield relationship. Full scenario-period maps are retained in Supplementary Fig. S25; saturated symptom-frequency and conditional yield-conversion results remain supplementary.',
        'Production exposure and common-population timing',
        'Fixed SPAM2020 production weights represent tonnes of all-wheat production in the reference geography. Quarter-degree cell identities, coordinates, positive harvested-area support and production totals are reconciled against the current climate registry. Native source-country fractions partition production in cross-border cells; environmental regions use the existing cell-centroid assignment. The same cell-specific climate response applies to each source-country fraction. Production exposure retains all reference production in its denominator, with unavailable climate responses explicit. [[SPAM2020]]',
        'For each scenario and period, ensemble-increase exposure sums baseline production in cells whose equally weighted three-model mean HAD change is positive. Unanimous-increase exposure requires positive changes in all three models; unanimous decreases, differing signs, zero responses and unavailable estimates remain distinguishable in Source Data. Production-weighted continuous HAD changes use production multiplied by the number of valid metric-specific season pairs within each model, followed by equal weighting across three model estimates. Climate-model ranges are deterministic spread. A coverage sensitivity requires at least 27 of 30 paired seasons in every model; excluded production remains in the reference denominator. Exposed tonnes describe spatial coincidence with increasing modelled damage, not tonnes of lost or future production.',
        'The timing comparison under late-century SSP5–8.5 uses complete historical–future season pairs with finite symptom, flowering and soft-dough dates in both seasons. Actual date subtraction measures elapsed days from each recorded sowing date, including leap years. Every event and relative interval uses this identical pair population. Within each climate model, fixed harvested area times the valid-pair count weights cell means; three model means then receive equal weight. Symptom timing relative to flowering equals symptom timing after sowing minus flowering after sowing exactly on this common population. Grain-fill elapsed duration excludes inclusive-day counting. The full-grid timing population differs from the sampled weather–phenology decomposition.',
        'Estimating the disease-related yield response',
        'The estimated disease-related yield change is −b times the change in HAD loss. The reference coefficient b is 0.018 t ha⁻¹ per GLAI-day, with 0.0141 and 0.0207 used as fixed alternatives from the published upper-three-leaf study. Multiplication by 1,000 converts t ha⁻¹ to kg ha⁻¹. Results are expressed per unit reference upper-canopy LAI because actual canopy area is unspecified. The source relationship began at GS31, whereas the primary climate calculation covers GS65–85; its use in this shorter interval is an unvalidated adaptation. Coefficient alternatives represent cultivar differences, not statistical confidence limits. The calculation estimates a disease-related yield component under these assumptions, without modelling the direct effects of heat, water limitation, CO₂ or other stresses on total grain yield. Yield percentages and national production tonnages require independently validated canopy area and grain yield. [[Parker2004|Foulkes2006]]',
        'Separating weather and wheat-phenology effects',
        'The decomposition and fourteen-setting sensitivity analysis use 64 harvested-area-proportional draws at 62 unique cells. Four simulations combine historical or future disease weather with historical or future wheat-phenology trajectories. Their differences separate weather and wheat-phenology contributions, with one half of their interaction allocated to each Shapley contribution. Of 5,751 finite historical–future pairs, 20 have an active day outside the accepted temperature range in a recombined trajectory and are excluded, leaving 5,731 pairs. Spatial Monte Carlo standard errors apply to this sample and are separate from full-grid climate estimates.',
        'The phenology offset is −100 times the phenology contribution divided by the weather contribution, using identical valid pairs. The ensemble percentage is the ratio of three-model mean contributions. Sensitivity settings vary model structure, symptom detection, reference canopy area and damage-to-function conversion. These calculations assess model assumptions and do not represent trials of a sowing-date or cultivar intervention.',
        'Field evaluation',
        'Disease observations from the two public field archives are pooled after exclusion of calibration records and application of geographic eligibility criteria. The evaluation contains 2,033 assessments from 188 field seasons in 140 coordinate-years and 136 symptom-onset histories from 78 field seasons in 62 coordinate-years. Onset histories concern source-defined leaves 1–3 and have observations bracketing symptom appearance. Original identifiers, units and percentage denominators remain in the evidence files. Source leaf numbers do not establish a common final-leaf rank across archives. [[Holst2022BASF|HolstDonner2022Corteva]]',
        'Evaluation weights are equal among coordinate-years, fields within coordinate-years, source leaves within fields and assessments within leaves. Symptom-onset error measures distance outside the two-sided observation interval, with the predefined penalty for missed positive observations. Severity predictions are compared with the calibration-leaf-mean benchmark; timing and detection use the phenology benchmark selected on calibration data. Model and benchmark predictions are compared on identical records. The 95% intervals use 20,000 paired bootstrap resamples of entire coordinate-year groups. They describe uncertainty in these fixed predictions on reused retrospective observations and exclude parameter-selection uncertainty. Duplicate coordinate-year identities are grouped across archives.',
        'Wheat phenological stage dates are evaluated on 40,878 matched events from German stations held out of calibration, at BBCH 10, 31, 51 and 85. Added leaf stages use pooled field observation intervals, with calibration observations reported separately. Evaluation of the canopy–yield relationship uses eight published treatment-mean contrasts across five genetic backgrounds, including STB, yellow rust and mixed disease. Leaving each background out of fitting gives backgrounds equal evaluation weight. Severity-based yield models use their specified held-out trial or year comparisons and corresponding training-mean benchmarks. [[Foulkes2006]]',
        'Additional yield-response tests retain the measurement hierarchy of each public source. Nordic assessment dates sharing a treatment yield remain in the same trial fold; eight post-harvest assessments and three rows of a pooled-control alias are excluded. Stage zero remains missing. Tunisia supplies 82 unprotected plot-season yields with two leaf assessments per outcome and 40 protected references in 2019. Flag and lower leaves were assessed on different dates. Protected-plot severity is unobserved and is not assigned zero. Whole-year transfer tests absolute yield, while mixture and replicate holdouts test relative protected-reference gaps within 2019. [[NFTS2026|BenMbarek2020|TunisiaDryad2020]]',
        'German original site files supply protection comparisons matched by location, year, cultivar, nitrogen and source-coded water regime. Unsuffixed HN/LN × NF/WF treatments enter; drought-suffixed references remain separate. Original fractional disease scores and missing values are preserved. Harvest treatment means use all eligible positive yield observations; severity means use only recorded assessments, with their replicate coverage retained. The relative response is 1 − unprotected yield / protected yield. German dry-mass yields are not pooled with other sources for absolute-yield fitting. Entire site-years or geographic sites are excluded from fitting, and forward transfer fits 2015–2017 and evaluates 2018–2019. Cultivar identities may occur in both training and evaluation; these comparisons test environmental transfer rather than prediction for unseen cultivars. [[BRIWECS2025]]',
        'All prespecified candidate models are compared with their corresponding training-mean benchmark. Weights are equal among held-out trial, year or location groups and then among outcomes within groups. Ridge models standardize predictors using training data and use a fixed penalty of 0.1. Nordic model choice uses inner training-trial validation. Paired Nordic intervals resample entire trials conditional on fixed predictions; they exclude refitting uncertainty. The nonnegative assessment-stage model is a secondary diagnostic following inspection of the stage-regression slopes. Infection dates, functional canopy trajectories and cause-specific STB losses are not validation targets of these severity-based comparisons.',
        'Additional source reconciliation preserves unique harvest units across repeated disease assessments and parallel archive copies. The Swiss and French records retain ordinal disease scores without conversion to percentage leaf area. The Swiss exploratory protocol was specified after source inspection and before fitting; it was not preregistered. Six fixed ridge models compare training means, ordinal STB categories, cultivar composition and management, and recorded co-disease ratings. Encoding, scaling and fitting use training folds only. Primary validation excludes entire Swiss locations; a secondary analysis excludes site-years. Harvest-derived predictors are excluded. Reported errors give site-years equal weight. Five-site resampling describes stability of fixed out-of-fold comparisons and excludes parameter-selection and refitting uncertainty. The single French environment supplies measurement and yield-source checks rather than an environmental-transfer test. [[SwissMixtures2023|FrenchMixtures2021]]',
        'Reproducibility',
        'Annual outputs record input-weather identities, model configurations, grid-cell order, numerical checks and output hashes. Aggregation records source hashes, counts of valid pairs and spatial coverage for each metric. Independent calculations check pooled field scores and selected full-grid regional means. Source Data contains figure and table values. The public repository regenerates documents from completed numerical evidence; a climate-driven model rerun additionally requires the external raw weather products.',
    ]
    text['supplementary_methods.txt']=[
        'Supplementary Methods',
        'Crop, disease and yield relationships',
        'Daily climate data drive wheat-phenology and Septoria-disease calculations. Wheat phenology determines leaf appearance, unfolding and the flowering-to-soft-dough interval. The disease model predicts damage on those leaves; its damage does not feed back into crop-development rates. After symptom detection, damage is mapped to an assumed loss of leaf function. Integration gives HAD loss, and a published coefficient converts HAD loss to a conditional disease-related yield estimate. This final calculation is separate from a complete crop-yield model.',
        'The reference upper-three-leaf canopy has maximum LAI of one. Disease-induced HAD loss integrates the assumed loss of functional green leaf area over time, with units of GLAI-days. Division by maximum reference LAI gives normalized HAD loss, expressed as equivalent days of reference canopy function lost. Numerical values are identical in the unit-LAI scenario. Relative HAD loss is the ratio of HAD loss to reference HAD and describes loss of assumed canopy function over the integration interval. Measured leaf-lesion percentage has a different denominator and temporal meaning.',
        'Full-grid climate estimates',
        'The experiment includes all 14,941 wheat land-use cells, with eligible calendars for 14,932 cells. Invalid seasons have unavailable outcomes. Symptom timing requires detection, while symptom frequency includes complete seasons without symptoms. Each metric has its own valid historical–future pairs. Corresponding positions in the two 30-year periods are paired within a climate model and SSP.',
        'Spatial means divide the harvested-area-weighted sum of paired changes by the harvested-area-weighted number of valid pairs. Historical and future means use these same pairs. Climate-model ranges span three independently aggregated estimates. The full-grid calculation has no spatial sampling error. Environmental regions follow EEA centroid assignment and countries follow dominant SPAM source-country labels; outside-region and unassigned cells remain explicit.',
        'Field observations and prediction scores',
        'Pooled disease evaluation excludes calibration records and combines geographically eligible records from both archives. Source identifiers and assessment definitions remain in the evidence files. Calibration and evaluation have no shared field identifiers. Coordinate-year identities define geographic bootstrap groups, with overlapping identities treated as the same group.',
        'An assessment weight is the reciprocal of the number of coordinate-years multiplied by the reciprocals of fields, source leaves and observations within successive groups. RMSE is the square root of the weighted mean squared error. Twenty thousand paired coordinate-year bootstrap resamples, with seed 20261008, give 95% percentile intervals. Every resample retains both predictions and all field, leaf and date records in a sampled group. The intervals exclude parameter-selection uncertainty and verification of independent biological-site identities.',
        'Symptom-onset comparisons use observed intervals bracketing first symptoms and specified penalties for missed positive observations. Crop-stage evaluation also uses two-sided observation intervals; plotted interval centres are display locations, not exact observed event dates. Calibration profiles and nested model selection are separate from pooled evaluation. German station observations evaluate the established phenology formulation; field support for added upper-leaf stages and soft dough remains limited.',
        'Canopy-based yield estimates',
        'Published protected and unprotected treatment means retain their leaf coverage, growth-stage interval, cultivar and disease exposure. The eight contrasts across five backgrounds include two with STB alone, two with yellow rust and four with mixed diseases. Absolute and relative yield scores describe aggregate treatment means when each genetic background is excluded from fitting. Raw plot variation and covariance are unavailable.',
        'The grid yield estimate is a linear conversion of HAD loss under the assumed upper-three-leaf canopy. Fixed coefficients and alternative GS31–85 and GS65–85 intervals assess dependence on these assumptions. The primary interval is shorter than the source coefficient interval, so the conversion requires field validation. Positive projected yield changes denote a decrease in the estimated disease-loss component; they do not establish a gain in total yield under future climate.',
        'Severity-based field yield comparisons',
        'The consolidated Tunisia/Nordic inventory contains 423 dated leaf or treatment assessments sharing 272 yield keys. Exclusion of a known control alias and post-harvest assessments leaves 412 assessments and 263 outcomes. These inventory counts do not denote independent environments. The Nordic predictive population contains 62 treated–untreated contrasts in five trials; subsets with known assessment stage and an earlier matched assessment contain 51 and 40 contrasts, respectively. Missing treated-plot stem-extension assessments remain unavailable. Growth-stage interactions use recorded ordinal GS, rather than elapsed time. The fixed stage-regression basis is severity reduction multiplied by (GS − 75)/10. The secondary nonnegative basis uses severity reduction multiplied by (85 − GS)/10. Neither basis represents observed infection timing.',
        'The Tunisian plot table contains incidence-weighted lesion area on flag and immediately lower leaves. Flag leaves were assessed at GS75 in both years; lower leaves were assessed at GS61 in 2018 and GS73 in 2019. The leaf-stage and year differences prevent separate identification of leaf-specific physiological coefficients. No same-leaf AUDPC or HAD is reconstructed. Cultivar proportions define composition predictors and shared mixture identities; treatment numbers are year-specific. Two-way whole-year transfer evaluates absolute yield on 82 outcomes. The 40 source-matched reference contrasts retain one negative response; within-year validation excludes entire mixture compositions or source replicate groups. These comparisons remain within one site-year and do not establish external environmental validity.',
        'German source harmonization preserves the original site-table precision and follows the documented source treatment coding, while excluding drought-suffixed WF references from unsuffixed NF/WF pairs. One nonnumeric severity token remains unavailable. Treatment means retain yield and severity replicate counts separately; missing protected severity is not imputed. The primary endpoint population contains 3,264 comparisons across 16 site-years and five locations. The subset with observed severity on both management groups contains 954 comparisons across seven site-years and four locations. Common-population benchmarks accompany each comparison. The primary and temporal comparisons give site-years equal weight; geographic transfer gives locations equal weight. Site-specific rating comparability and incomplete assessment timing remain limitations.',
        'The complete source inventory includes raw field observations, regional survey aggregates, published model-adjusted means, fitted curves and model inputs. Fitted response grids, duplicate archive copies and published parameter tables do not increase observational sample size. Older Nordic/Baltic yield and weather-derived recommendation tables do not provide observed severity–yield pairs. New data-source identities, eligibility, fixed protocols, held-out predictions and independent numerical checks are retained with the current source data.',
        'Weather and wheat-phenology contributions',
        'The separate decomposition uses four historical–future combinations of disease weather and wheat-phenology trajectories in the 64-draw sample. Twenty pairs exceeding the accepted temperature range in a recombined trajectory are excluded. The two Shapley contributions share the interaction equally and sum to the net change on the same valid pairs. Phenology offsets use the identical pair set in numerator and denominator. The three-model ensemble offset is a ratio of mean contributions.',
        'The main maps and regional estimates describe the completed full-grid experiment. Decomposition and structural sensitivity describe the separate sampled analysis. Field figures describe prediction errors on retrospective observations, and published yield figures describe treatment-mean contrasts. These datasets support different quantities and do not define a single overall model-accuracy percentage.',
    ]
    text['availability.txt']=[
        'Data availability',
        'Source data and numerical evidence supporting the findings are deposited at https://github.com/SmartAG-Team/paper_cc_impact_wheat_disease, with the manuscript-specific files in publication/european_wheat_stb. The repository is publicly accessible. Dataset references identify the public disease archives, the Nordic Field Trial System, Tunisian cultivar-mixture observations, German multi-environment field data, Swiss and French cultivar-mixture observations, NEX-GDDP-CMIP6v2 climate data, GGCMI calendars, SPAM2020 wheat area and EEA environmental boundaries. Source_Data.xlsx contains completed grid summaries, environmental-region and country statistics, area shares by direction of change, pooled field evaluation, published canopy–yield evidence, grouped yield-response tests, fixed-production exposure and common-population timing comparisons. Original labels and assessment definitions remain in the underlying records. [[Holst2022BASF|HolstDonner2022Corteva|NFTS2026|TunisiaDryad2020|BRIWECS2025|SwissMixtures2023|FrenchMixtures2021|NEXGDDPCmip6V2|GGCMIPhase32021|SPAM2020|EEA2016]]',
        'The repository includes completed summaries, selected diagnostic outputs, input and output hashes, and numerical evidence for document regeneration. The complete raw climate and annual-output archives are external because of their size. Model reruns require the recorded climate products and adjustment files. Raw plot observations and physiological measurements unavailable in the source studies are not reconstructed.',
        'Code availability',
        'Simulation, statistical-analysis and document-generation code are deposited in the same repository, which is publicly accessible. The repository includes evidence manifests and an executed field-yield validation notebook. REPRODUCIBILITY.txt documents regeneration and model-rerun requirements. The supplementary model specification contains 29 numbered equations, and Parameter_inventory.csv records 84 fixed, fitted and scenario quantities.',
    ]
    text['declarations.txt']=old['declarations.txt']
    return text
