"""Formal crop-response manuscript sections and supplementary methods."""
TITLE='Leaf development and healthy-area duration connect seasonal Septoria timing with wheat disease yield responses'


def refine_sections(raw):
    raw['abstract.txt']=[
        'Crop disease impact depends on upper-leaf emergence, epidemic timing and the duration of functional green-area loss. A modular winter-wheat framework couples temperature–photoperiod–vernalization development, stage-constrained leaf availability, seasonal Septoria source continuity and conditional top-three-leaf healthy-area-duration transfer. Additional BBCH32,33,37 and39 thresholds use stage observations independently of disease signs. German station test MAE for the retained development process is8.02 days; added flag-stage identification remains weak. Disease selection uses28 original calibration field seasons and three inner location folds. In reused BASF and location-disjoint Corteva validation, upper-leaf sensitivity is98.9% and96.9%, but specificity is33.0% and55.9%. Symptom interval-excess distances of5.06 and5.36 days exceed the phenology benchmark’s3.00 and2.75 days. Published crop-response evidence includes117 STB yield contrasts,25 top-three cultivar coefficients and eight paired top-five canopy–yield means spanning STB and yellow rust. Predictions for withheld genetic backgrounds have relative-loss RMSE5.16 percentage points, while absolute-loss R² is−0.432. Yellow-rust radiation comparisons and leaf-rust rank-specific results support physiological distinctions between area duration and grain response. The51,840-draw-season climate replay gives a late-century SSP5–8.5 conditional transfer increase of0.0471 t ha⁻¹ per unit nominal upper-three LAI. Different leaf scopes remain separate. Unmeasured functional area, sparse onset calibration and aggregate yield evidence constrain field-level infection and absolute-yield interpretation.'
    ]
    raw['introduction.txt'][5]=(
        'Healthy-area duration connects foliar disease with crop performance through the size and persistence of functional canopy area. STB, yellow rust and leaf rust provide complementary evidence: STB studies estimate top-three green-area response coefficients, yellow-rust studies compare area duration with absorbed radiation, and leaf-rust studies distinguish individual leaf contributions to tiller grain weight. Leaf contribution and disease tolerance depend on genotype, canopy traits and source–sink processes. These responses support a shared crop-impact framework with disease- and study-specific exposure definitions. [[Parker2004|Foulkes2006|Bryson1997|SubbaRao1989|Bancal2015|vanDenBerg2017]]')
    raw['introduction.txt'].append(
        'The mechanistic epidemic case is STB; the comparative crop-response scope also includes yellow rust and leaf rust. Phenological event dates, visible disease onset and grain response have separate observational supports. The modular representation links these supports through leaf availability and healthy-area duration while retaining distinctions between exact events, censored observations, published fitted relationships and reconstructed aggregate predictions.')
    raw['baseline_results.txt']=raw['baseline_results.txt'][:3]+[
        'Published canopy–yield evidence across wheat diseases',
        'Parker et al.’s six site-year experiments retain117 reported protected-minus-unprotected grain-yield contrasts across25 cultivars, including five negative values and33 unreported cultivar/site-year combinations. The associated top-three random-effects response predictions span0.0141–0.0207 t ha⁻¹ per GLAI-day around the retained0.0180 transfer centre. In their analysis without environment effects, the reported fitted yield-loss correlation is0.760 for random-effects healthy-area duration and0.210 for symptom area. These original fitted relationships establish empirical crop-response support, rather than independent prediction accuracy (Figures S9–S10; Table S7). [[Parker2004]]',
        'Foulkes et al. provide eight paired genotype-by-fungicide mixed-model means from four STB/yellow-rust experiments, with unbalanced site coverage. Their top-five postanthesis HAD differs from the primary top-three domain. Leaving each of five genetic backgrounds out of response fitting gives group-balanced relative yield-loss MAE4.79 and RMSE5.16 percentage points, with R²0.247. Absolute-loss MAE is0.541 t ha⁻¹ and RMSE0.617 t ha⁻¹, with R²−0.432. The descriptive all-background slopes are0.5767 for relative losses and0.03427 t ha⁻¹ per top-five GLAI-day for absolute losses. The latter is not a replacement for the top-three coefficient. Shared predicted means, a small number of backgrounds and confounded genotype/site coverage limit interpretation (Figure4b; Figure S11; Table S8). [[Foulkes2006]]',
        'Published yellow-rust experiments report grain-yield R² values of0.63 and0.73 for healthy-area duration, compared with0.80 and0.92 for radiation-weighted healthy-area absorption in1994 and1995. The corresponding treatment-combination counts are60 and52. Leaf-rust regressions using individual relative healthy-area durations report adjusted R² of0.84 and0.67 in rust-affected crops across two seasons, with0.91 and0.88 in controls. The leaf-rust outcome is tiller grain weight and includes the flag through fourth leaves. These within-study fits support radiation and leaf-position effects, while their predictor and outcome scales preclude a pooled top-three transfer coefficient (Figure S12; Tables S9–S10). [[Bryson1997|SubbaRao1989]]'
    ]
    discussion=raw['discussion_field_and_limits.txt']
    discussion[5]=(
        'The published STB yield contrasts and cultivar coefficients establish an empirical association between top-three functional green-area duration and grain loss. The withheld-background reconstruction in a separate top-five study provides a limited transfer test: relative response has modest explanatory skill, whereas the absolute response fails against the group-balanced mean. Shared mixed-model means and environmental confounding prevent treatment of these eight contrasts as independent field validation. The crop-impact connection is consequently supported, but a universal absolute disease–yield coefficient is not. [[Parker2004|Foulkes2006]]')
    discussion.insert(6,
        'The broader wheat-disease evidence strengthens the physiological interpretation without establishing shared epidemic kinetics. Yellow-rust results favour radiation-weighted healthy area over area duration alone. Leaf-rust results concern relative durations of individual leaves and tiller yield, including nonfoliar grain sources. These distinctions support explicit leaf area, radiation exposure, grain-filling duration and cultivar tolerance in crop-impact analysis. Rust evidence does not identify STB overwintering or transmission parameters, and an STB epidemic trajectory cannot serve as rust validation. [[Bryson1997|SubbaRao1989|Bancal2015|vanDenBerg2017]]')
    discussion.insert(7,
        'Matched protected/untreated yield, healthy reference area, cultivar resistance and cause-specific senescence are unavailable for the present disease trials. Simulated symptomatic and retained-damage fractions therefore remain functional-loss proxies. The published top-three relationship permits conditional comparisons of timing and exposure; it cannot establish actual field yield, percentage loss or total regional tonnes lost. Its original integration begins at GS31, whereas the flowering–BBCH85 comparison has a shorter declared window.')
    raw['methods.txt'].insert(raw['methods.txt'].index('Climate forcing and spatial estimation'),
        'Published crop-response data retain source-table identity, disease, leaf scope, integration window, units and statistical status. Parker et al.’s Table4 supplies150 cultivar/site-year cells,117 numerical yield contrasts and33 missing combinations; Table5 supplies25 random-effects slopes and21 fixed-effect estimates with standard errors. Negative contrasts remain unchanged. Foulkes et al.’s Table2 supplies eight protected/affected predicted-mean pairs. Derived absolute losses are protected-minus-affected values; relative losses divide those differences by the protected mean. The reported top-five postanthesis integration and85% grain dry matter are retained. Published yellow- and leaf-rust fit summaries remain separate from paired observations. [[Parker2004|Foulkes2006|Bryson1997|SubbaRao1989]]')
    raw['methods.txt'].insert(raw['methods.txt'].index('Climate forcing and spatial estimation'),
        'Published paired response evaluation withholds each genetic background in turn. For predictor x and response y, the nonnegative origin-constrained training slope is max[0,Σwxy/Σwx²]; each background receives equal weight, divided among its observed lines. Absolute and relative responses use separate slopes. All lines in the withheld background are excluded from its coefficient estimation. Evaluation weights sum to one across the five backgrounds, and R² is1−Σw(ŷ−y)²/Σw(y−ȳw)². Full-data descriptive slopes are separate from prediction scores. Source mean covariance and plot-level observations are unavailable, so no sampling confidence interval or raw-plot validation is identified. The top-five evaluation does not recalibrate the current top-three transfer.')
    raw['methods.txt'][-1]=raw['methods.txt'][-1].replace(
        'The full repository suite contains301 passing tests; seven pre-existing donor datetime deprecation warnings remain.',
        'The archived runtime verification contains301 passing tests with seven donor datetime deprecation warnings. Four additional response-analysis checks cover group weights, exact proportional recovery, exclusion of withheld outcomes from their fitted coefficient and invalid inputs.')
    raw['availability.txt'].insert(3,
        'Source Data retain all published STB yield contrasts, cultivar coefficients, paired canopy–yield means, genetic-background predictions and wheat-rust crop-response summaries, with source DOI and measurement-domain definitions. These transcriptions preserve treatment-mean and fitted-summary status; unavailable raw plots and covariance are not imputed.')
    raw['supplementary_methods.txt'] += [
        'Published yield evidence and measurement domains',
        'Tables S7–S10 and Figures S9–S12 preserve four distinct crop-response domains. Parker et al. provide absolute green-lamina area integrated over the top three leaves from GS31, with an unrecovered exact terminal rule. Foulkes et al. integrate the top five leaves from anthesis to complete canopy senescence. Bryson et al. compare canopy duration with radiation-weighted absorption; a fixed leaf-rank subset is unverified. Subba Rao et al. use relative duration separately for the flag, penultimate, antepenultimate and fourth leaves, with tiller grain weight as outcome. An absolute stand-area coefficient, a normalized leaf-duration coefficient and a radiation-response coefficient have different dimensions. [[Parker2004|Foulkes2006|Bryson1997|SubbaRao1989]]',
        'The Parker yield matrix contains25 cultivars and six site-years. Missing combinations remain missing, and all five negative protected-minus-unprotected differences remain numerical observations. Published treatment contrasts cannot recover plot variability or isolate disease-specific causal effects of protection. The25 cultivar slope predictions share environments. Fixed-effect uncertainty is shown only where a coefficient and its standard error were published. BLUP prediction-error variances refer to deviations from the population slope and do not identify uncertainty of complete slopes.',
        'Foulkes paired means and genotype coverage',
        'The four experiments comprise Rosemaund STB and Terrington yellow-rust site-years in1999 and2000. Mercia lines occur in the STB domain, M. Huntsman lines in the yellow-rust domain, and Hobbit, Weston and Chaucer span both. Table2 entries are mixed-model predicted genotype-by-fungicide means. Average SED is12.9 GLAI-days for HAD and0.52 t ha⁻¹ for grain yield; it is not a row-specific error bar. The eight derived contrasts therefore share model estimation and heterogeneous environmental exposure. Reported Table3 coefficients and Table4 site-year deviations remain separately available in Source Data. [[Foulkes2006]]',
        'The background registry contains Mercia, M. Huntsman, Hobbit, Weston and Chaucer. Two lines share each of the first three backgrounds; Weston and Chaucer each contribute one. In each of five folds, all lines of one background are omitted and the proportional slope uses only the other four. The training weight for a line is the reciprocal of the number of lines in its background; rescaling all training weights does not change the coefficient. Evaluation gives every background weight0.2, divided equally among its lines. The arithmetic reproduction independently reconstructs every fold slope and prediction.',
        'Relative response evaluation gives MAE4.7935 percentage points, RMSE5.1562 percentage points, bias+0.0216 percentage points and R²0.2471. Absolute response gives MAE0.5407 t ha⁻¹, RMSE0.6169 t ha⁻¹, bias−0.0091 t ha⁻¹ and R²−0.4324. The negative absolute-response R² indicates that withheld predictions underperform the weighted-mean reference. The full-data relative coefficient0.57670 and absolute coefficient0.034268 are descriptive fits in the top-five domain. Shared mean covariance, unbalanced site membership and the small number of backgrounds prevent a confidence-interval interpretation of these scores.',
        'Disease comparison and radiation response',
        'The yellow-rust summaries give separate fitted R² values for HAD and healthy-area absorption in each year. Healthy-area absorption incorporates incident radiation intercepted by functional area; its improved fit supports a radiation component in yield analysis. Leaf-rust summaries give adjusted R² for leaf-specific relative duration and tiller grain weight. R² and adjusted R² refer to different regression models and are not pooled, interpreted as independent validation or ranked as disease predictability. None of these rust summaries supplies observed STB infection dates. [[Bryson1997|SubbaRao1989]]',
        'Individual events, censoring and exposure diagnostics',
        'Figure S5 retains all40,878 common-matched German test events. Days after the recorded sowing date preserve event chronology; hexagon counts use a common logarithmic colour scale, and each stage retains its complete range. Figure S6 retains all136 two-sided upper-leaf histories for each of the seasonal and phenology models. Missing predicted symptoms carry the registered positive-event penalty. Horizontal offsets separate observations for display and leave losses unchanged. Exact station errors, field interval-excess losses and symptom penalties retain separate units and denominators.',
        'Figure S7 contains calibration-only ordered stage profiles for BBCH32,33,37 and39. The one- and two-day joint-loss tolerances describe threshold identification, rather than probability intervals. The399 candidate values per stage remain in Source Data even where the plotted vertical range is restricted. Figure S8 retains218 complete field replays and relates predicted timing to the specified functional HAD deficit. These simulation covariations do not establish observed disease-induced senescence or measured grain loss.',
        'The earlier specified timing illustration remains in Source Data: a45-day window, nominal upper-three LAI1 and functional loss increasing0.04 per day to0.8. Onsets at−10,0,15,30 and50 days relative to flowering give33.8,27.6,15.6,4.2 and0 GLAI-days of deficit. The resulting0.018-slope products are0.6084,0.4968,0.2808,0.0756 and0 t ha⁻¹ per unit LAI. These declared trajectories demonstrate window dependence; they are separate from the published yield contrasts and current field replay.'
    ]
    return raw
