"""Formal manuscript sections from frozen field and climate evidence."""
from pathlib import Path
import json
import pandas as pd
from analysis.paper_study.yield_evidence_20261007.text import refine_sections as refine_yield
from analysis.paper_study.map_restoration_20261007.text import refine_sections as refine_maps,TITLE

HERE=Path(__file__).resolve().parent
STUDY=HERE.parent


def sections():
    for group in ('phenology','disease','climate'):
        if json.loads((STUDY/group/'receipt.json').read_text())['status']!='complete':
            raise ValueError('Complete frozen study evidence is required.')
    replay=pd.read_csv(HERE/'replay/full_season_top3_timing_and_conditional_yield.csv')
    loss=float(replay['conditional_yield_loss_b0.018_t_ha_per_unit_lai'].mean())
    return refine_maps(refine_yield({
'abstract.txt':[
"Crop disease impact depends on the timing of infection relative to leaf development and the duration of functional green-area loss. A modular winter-wheat framework couples temperature–photoperiod–vernalization development, flag-stage-constrained leaf availability, local residue and living-canopy source continuity, weather-dependent primary and secondary establishment, and conditional top-three-leaf healthy-area-duration transfer. Additional BBCH32,33,37 and39 thresholds are estimated from stage observations independently of disease signs. Disease selection uses the original28 BASF2017–2018 field seasons, with three inner location folds; reused validation contains45 BASF2019 and143 location-disjoint Corteva field seasons. The seasonal model detects positive upper-leaf assessments with sensitivity98.9% and96.9%, but specificity is33.0% and55.9%. First-symptom interval-excess distances of5.06 and5.36 days exceed the independently selected phenology benchmark’s3.00 and2.75 days. A conditional European replay covers51,840 spatial draw-seasons across three climate models and three SSPs. Late-century SSP5–8.5 advances flag-leaf effective infection4.81 days relative to flowering and increases the standardized grain-fill yield-transfer scenario0.0471 t ha⁻¹ per unit nominal upper-three-leaf LAI. Sparse onset calibration, unidentified source contributions and unmeasured functional leaf area limit predictive and yield interpretation. The framework supports explicit structural testing and reproducible crop-protection research; the available evidence does not establish accurate field-level infection absence or absolute yield loss."
],
'introduction.txt':[
'Introduction',
"Plant diseases contribute to crop losses, while climatic changes alter the environmental and host-development conditions under which epidemics occur. Disease risk therefore depends on more than a terminal infection percentage. Infection of newly emerged upper leaves, subsequent disease development and the duration of green-area loss during grain filling connect epidemic timing to crop impact. [[Savary2019|Chaloner2021|Gouache2013]]",
"Septoria tritici blotch, caused by Zymoseptoria tritici, has local residue and living-host sources together with airborne inoculum arriving from outside a plot. Infected wheat debris at the soil surface can influence early epidemics, and the living autumn–winter canopy subsequently becomes an important source. This ecology supports continuity from crop establishment through winter; it does not identify an autonomous soil pathogen stock or a universal spring activation threshold. [[SuffertSache2011|ShawRoyle1989]]",
"Upper-leaf disease depends on the relative timing of inoculum availability and leaf appearance. Newly emerging leaves can encounter inoculum from earlier infected canopy layers, while their remaining lifetime determines the opportunity for subsequent cycles. Canopy architecture and developmental variation alter those contacts and exposure histories. [[ShawRoyle1993|LovellCanopy2004|Baccar2011]]",
"Stem-node stages and leaf appearance require distinct representations. BBCH31 and32 describe the first and second detectable nodes; BBCH37 indicates flag-leaf visibility and39 full unfolding. Temperature-based leaf appearance can depend on the thermal environment of the growing point and on ontogenic development. Cultivar and environmental variation preclude a universal conversion from stem-node code to absolute leaf number or from an air-temperature phyllochron to a photoperiod/vernalization-weighted coordinate. [[Jamieson1995|Abichou2018]]",
"Healthy-area duration provides a yield-relevant link between upper-canopy disease and crop performance. The contribution of a leaf depends on its green area and the duration of loss, rather than an invariant rank weight. Disease tolerance also varies with genotype, canopy traits and source–sink processes. A literature-based transfer is consequently conditional on functional-area, time-window and tolerance assumptions. [[Parker2004|Bancal2015|Foulkes2006|vanDenBerg2017]]"
],
'field_results.txt':[
'Results','Stage-constrained leaf development',
"The retained TPV process has German station-held-out evidence at BBCH10,31,51 and85. Common-event comparison across GDD, T–P and T–P–V contains18,057 calibration,38,133 validation and40,878 test events. Training comprises187 stations; the test evaluation retains1,140 of1,223 reserved stations. T–P–V test MAE is8.02 days, RMSE11.75 days and bias+0.50 days. Stage-specific test MAEs are6.03,11.59,6.85 and7.44 days for BBCH10,31,51 and85, respectively. Station separation concerns spatial holdout within1985–2015; known sowing and realized weather condition the hindcasts. This evidence concerns the retained development process, rather than the added flag stages or disease outcomes (Figure2a; Table S1).",
"The transferred TPV process retains the original BBCH10,31,51 and85 thresholds and its previous-day photoperiod and vernalization gates. BBCH31 dates are identical to the archived q=1 calculation in all28 original calibration field seasons. Ordered stage-only estimation adds developmental thresholds633.392,664.496,702.266 and807.799 for BBCH32,33,37 and39, respectively. The independent flowering proxy remains1165.926. The stage fit has27 usable calibration fields, but only1,5,6 and9 genuinely two-sided intervals for the four additions; every added threshold has weak identification.",
"Field-stage evaluation retains BBCH10,31,32,33,37,39,51,65 and85 in the original calibration, BASF2019, location-disjoint Corteva and overlapping full-source Corteva cohorts. Genuine BBCH37/39 intervals number3/4 in BASF2019 and19/30 in the strict external subset. Mean distances outside the admissible intervals are3.67/0.50 days and2.37/1.13 days, with compatibility33.3%/75.0% and63.2%/80.0%, respectively. Median interval widths are14/13.5 and22/17.5 days. BBCH10 lacks genuine two-sided field intervals; BASF2019 also lacks them at31,32 and85. Those endpoints retain their one-sided bounds and explicit coverage rather than artificial exact dates (Figure2b; Table1; Tables S2–S3).",
"Heading at BBCH51 has23 genuinely two-sided BASF2019 intervals and50 strict external intervals, with mean excess1.39/1.14 days and compatibility78.3%/68.0%. Flowering-proxy BBCH65 has35/65 intervals, with full-season mean excess1.80/1.83 days and compatibility65.7%/69.2%. None of the five informative external BBCH85 intervals contains the predicted soft-dough date; mean excess is9.00 days. The archived full-season forcing supplies later dates without moving any previously reached threshold. Both observation-horizon and complete-season scores remain separate. The full145-field Corteva transfer overlaps the143-field location-disjoint subset and is not pooled with it. Field timing errors are distances outside observation intervals, rather than exact-date errors (Figures S1–S4).",
'Seasonal sources and first-symptom prediction',
"The calibration archive contains254 all-leaf assessments and178 top-three-leaf assessments in28 field seasons. Only8 top-three first-symptom histories in6 fields have both a preceding zero and a first positive. Among144 registered settings, the selected effective primary and secondary scales are0.001 and10, with a20-reference-day latent mean,120-unit final-rank spacing and0.1 relative imported background. The training-only rainfall-duration scale is0.45 mm h⁻¹. Two settings tie on the primary inner interval-distance criterion; the secondary scale lies at the grid’s upper bound. These constraints identify a conditional timing setting rather than physical overwintering or transmission coefficients.",
"Under frozen parameters, top-three positive-assessment sensitivity is98.9% in BASF2019 and96.9% in strict Corteva validation. Zero-assessment specificity is33.0% and55.9%, giving balanced accuracy65.9% and76.4%. The independently selected phenology benchmark has lower sensitivity93.7%/87.8%, but higher specificity61.4%/81.6% and balanced accuracy77.5%/84.7%. Top-three assessment counts are252 and1310; the zero assessments number22 and174. Those zeros primarily constrain assessment timing and do not represent independently observed disease-free complete seasons (Figure3; Table2).",
"For the13 and123 genuinely two-sided onset histories, seasonal-model mean interval-excess distance is5.06 and5.36 days, compared with3.00 and2.75 days for the phenology benchmark. Interval compatibility is18.8% and49.8%, compared with50.0% and59.8%. The explicit seasonal model therefore provides greater sensitivity without improved onset accuracy. Both disease and benchmark predictions use the same stage-only thresholds, and each benchmark’s spacing and delay are selected on calibration records independently.",
"All-ordinal-leaf assessment and onset scores retain the same calibration and validation cohorts, alongside the F1–F3 endpoint. Left-, right- and two-sided histories and field/field-leaf occurrence windows remain separately reported. Earlier severity-model comparisons and French plot-leaf transfers retain their original model identities. The French records comprise383 future pycnidial assessments at one representative station across2018–2019, conditioned on initial observations; they do not supply natural field-onset validation of the current model (Table2; Tables S4–S6).",
"Same-fit pathway interventions reveal structural sensitivity without establishing source attribution. Removing the local initial source decreases validation interval distance to2.50 and3.94 days; removing secondary establishment increases it to27.00 and24.18 days. Local residue abundance, imported pressure, cultivar resistance and field management are unavailable. The primary-source scale and initial relative stock are confounded, and the local/imported contributions remain unidentified. Source-free simulations produce exactly zero infection."
],
'baseline_results.txt':[
'Top-three-leaf exposure and conditional yield transfer',
"Complete archived weather extensions produce218 full-season field replays, all reaching the flowering proxy and BBCH85. Every original observed-horizon tissue, residue and host-area trajectory is unchanged by the extension. Effective infection precedes flowering in all modeled F1,F2 andF3 trajectories, with median relative dates−28,−40 and−51 days. Median symptom dates are−12,−20 and−30 days;216 F1 trajectories become symptomatic before flowering. These dates are model events, rather than independently observed infection times.",
f"For nominal mature upper-three-leaf LAI1, distributed equally across F1–F3, the flowering–BBCH85 replay gives mean conditional transfer {loss:.4f} t ha⁻¹ per unit nominal LAI at b=0.018. The reference area scales with leaf unfolding; natural senescence and actual canopy magnitude remain unmeasured. The simulated visible affected fraction acts as a functional-loss scenario, not a measured green-area deficit or locally calibrated yield. Source data retain all218 individual trajectories and their exposure windows.",
"A separate specified45-day grain-fill illustration isolates the role of timing. Functional loss rises0.04 per day to0.8, and all trajectories reach0.8 at a later common endpoint. Onsets−10,0,15,30 and50 days relative to flowering produce healthy-area-duration deficits33.8,27.6,15.6,4.2 and0 GLAI-days, respectively. At b=0.018, conditional losses are0.6084,0.4968,0.2808,0.0756 and0 t ha⁻¹ per unit reference LAI. A terminal disease value alone cannot recover those differences (Figure4). [[Parker2004]]"
],
'climate_results.txt':[
'Conditional European climate replay',
"The registered spatial design has64 independent draw identities from16 geographical strata and62 unique0.25° cells. Eligible winter/rainfed-calendar area is54.401 million harvested hectares across14,932 cells;9 cells lack the required calendar coverage. The all-wheat harvested-area weighting represents an imposed winter/rainfed scenario and does not identify actual genotype or management proportions. Three climate models, three SSPs and90 harvest years give810 regional season runs and51,840 draw-seasons. Of these,51,813 reach BBCH85 with supported forcing,26 fail to reach it and1 encounters a daily mean above40°C before the endpoint. Invalid cases remain missing.",
"Conditional upper-leaf occurrence is almost saturated. The three-model area-weighted means for at least one top-three infection before BBCH85 range99.892–100%, and means for all three range99.742–99.956%. With relative local source1 and persistent imported background0.1, changes in occurrence provide little discriminatory signal. This saturation cannot establish infection probabilities or justify near-universal field warnings.",
"Timing relative to flowering and conditional functional-area duration carry the main scenario changes. Late-century SSP5–8.5 shifts F1,F2 andF3 effective infection−4.805,−7.846 and−14.511 days relative to flowering; F1 symptoms shift−3.662 days. Grain-fill duration changes+0.125 days on average, with individual climate models showing both shortening and lengthening. Earlier upper-leaf disease relative to the host window therefore accompanies greater conditional exposure without a consistent reduction in window length.",
"The SSP5–8.5 late-century flowering–BBCH85 healthy-area-duration deficit increases2.6166 GLAI-days per unit nominal upper-three-leaf LAI. At b=0.018, paired conditional yield transfer increases0.04710 t ha⁻¹ per unit LAI, from0.11706 to0.16416 on common coverage. The climate-model range is0.02310–0.07906 and spatial Monte Carlo standard error0.00589. The cultivar-slope scenario gives0.03690–0.05416; neither the climate range nor slope range is a confidence interval. Late-century mean changes under SSP1–2.6 andSSP2–4.5 are0.02494 and0.02698, with the SSP1–2.6 climate-model range crossing zero. Common valid grain-fill area-time coverage exceeds99.866% for every comparison (Figure5; Table3)."
],
'discussion_field_and_limits.txt':[
'Discussion',
"Leaf emergence, infection establishment, symptom detection and yield-relevant functional loss are distinct endpoints. Stage observations constrain crop development, while disease signs constrain visible expression. The explicit seasonal source structure retains autumn and winter states and allows later infections to depend on infectious earlier canopy tissue. This representation is consistent with published epidemic ecology, but its additional biological states are not individually validated by the present observations. [[SuffertSache2011|ShawRoyle1993|Lovell2004]]",
"The independent phenology benchmark has better first-symptom timing and balanced detection in both reused validation sets. Greater mechanistic detail therefore does not establish greater predictive accuracy. Only8 calibration histories genuinely bracket upper-leaf onset, whereas136 evaluation histories do so. Sparse calibration, a boundary-selected secondary scale and improved timing when the assumed local source is removed indicate weak identification. Reliable infection-absence prediction requires disease-free complete-season records and independently observed local or imported source status; true infection dates require observations beyond first visible symptoms. [[Pietravalle2003]]",
"German station holdouts support the retained developmental formulation within their known-sowing and realized-weather domain. They do not validate additional flag-stage thresholds, local European crop calendars or disease outcomes. Few genuine early-stage intervals and the five incompatible external soft-dough intervals constrain transfer of the flowering–BBCH85 exposure window. Stage coverage, temporal resolution and missing predictions therefore qualify each endpoint separately, rather than supplying a single pooled crop–disease accuracy score.",
"The conditional climate replay advances upper-leaf disease relative to flowering and increases a model-proxy healthy-area-duration deficit. Its interpretation is constrained by the field benchmark failure, imposed inoculum presence and unvalidated host transfer. Near-saturated occurrence reflects those conditions. The numerical changes quantify responses of the specified model rather than forecasts of realized European disease or grain losses. Spatial sampling errors, between-model climate ranges and cultivar-transfer ranges represent different uncertainties. Ecological-parameter, sowing, resistance, natural-senescence and functional-conversion uncertainties remain additional.",
"Functional green-area loss and crop tolerance determine yield consequences. The literature transfer applies to absolute top-three green lamina area, without fixed rank weights, but genotype and crop physiology alter the yield response. Protected reference area, cultivar resistance and matched untreated/protected yield are absent in the trial archives. The modeled symptomatic and retained-damage fraction is therefore an explicit functional-loss proxy, and the standardized transfer cannot establish actual crop yield loss or total regional tonnes lost. [[Parker2004|Bancal2015|vanDenBerg2017]]",
"The object architecture separates scientific hypotheses from the calibration workflow. Pure simulation components own parameters, states and rate proposals; external calibration utilities prepare observations, select fits and construct explicit runtime cases. The daily engine provides deterministic stepping, instance ownership, crop masking and configuration-checked restart. Scientific scope remains a wheat/STB and conditional HAD framework; soil water, nitrogen, carbon assimilation, source–sink grain formation and cultivar-specific leaf-number development are not represented. Architectural similarity to established crop simulators does not imply equivalent physiological scope or validation. [[Holzworth2018APSIM|deWit2019WOFOST]]"
],
'methods.txt':[
'Methods','Field evidence and partitioning',
"Archived German winter-wheat phenology evaluation uses187 training stations,1,222 validation stations and1,223 reserved test stations, of which1,140 satisfy the inherited scoring eligibility rule. The83 excluded test stations remain outside fitting. Station identities are disjoint, while every cohort contains observations in1985–2015. Exact station/sowing-cycle/BBCH keys match first predicted daily threshold crossings to recorded events at10,31,51 and85. Sowing is a management anchor and contributes no physiological date error. GDD, T–P and T–P–V comparisons use common matched events; individual-model coverage and missing predictions remain separate. Retained event tables contain430,440 model-event rows and reproduce270 MAE, RMSE and bias values. The frozen donor parameters agree with the original training registry.",
"Source assessments derive from the public BASF and Corteva wheat Septoria archives. The combined development collection has218 field seasons and2305 numeric disease assessments. The original BASF2017–2018 registry defines28 calibration fields and254 assessments; BASF2019 defines45 reused validation fields and330 assessments. The location-disjoint Corteva subset defines143 fields and1703 assessments, excluding locations shared with the original archive. Field grouping, ordinal-leaf identities, duplicate handling and source calendar assumptions are preserved. Earlier development has exposed these archives; all reported validation is retrospective development validation. [[Holst2022BASF|HolstDonner2022Corteva]]",
"Recorded disease magnitudes contribute only their zero/positive signs to the primary fit. Last preceding zero and first positive define an onset interval with an open lower and closed upper bound. First-positive-only histories are left censored and zero-only histories right censored. Later returns to zero remain reported persistence violations. Primary onset metrics use two-sided top-three histories, with equal coordinate-year, field-within-coordinate-year and leaf-within-field weighting. Distance is measured outside the admissible interval; missing positive events receive at least30 days of loss. Assessment sensitivity and specificity use the same hierarchy."
,'Development and leaf availability',
"The frozen donor process accumulates temperature-weighted development with photoperiod and vernalization modifiers. Previous-day unadjusted thermal accumulation gates photoperiod; previous-day temperature–photoperiod accumulation gates vernalization. Model input comprises consecutive weather, latitude and a scenario sowing date. Actual sowing and genotype are absent in the main trial sources, so the winter/rainfed crop calendar supplies an explicit management scenario. Field forcing is the archived ERA5-derived daily series; realized-weather simulations are hindcasts. [[Hersbach2020ERA5|GGCMIPhase32021]]",
"Additional stage thresholds are estimated using stage columns alone. Same-field/date stage ranges are intersected; contradictory, reversed and temporally inconsistent ranges are quarantined. Event intervals retain inclusive upper and exclusive lower endpoints. The BBCH32,33,37 and39 thresholds are jointly ordered on a399-point developmental grid between frozen BBCH31 and51, using equal-field/event censored loss. Profiles within0,1 and2 days of the minimum describe weak identification and are not confidence intervals. No disease signs or reused-validation stages determine those thresholds. The independent stage-only BBCH65 threshold defines a flowering proxy; BBCH85 is soft dough, rather than harvest.",
"Field evaluation applies the same normalized observations to every retained stage at10,31,32,33,37,39,51,65 and85. Two-sided and one-sided constraints remain distinct. The primary complete-season comparison uses archived weather extensions and unchanged stage parameters; all1,721 threshold dates previously reached within the original forcing horizon agree exactly. Observation-horizon scores retain their missing-event lower-bound interpretation. The full145-field Corteva transfer includes the two fields excluded by location overlap; its observations and metrics remain separate from the strict subset. Calibration evidence, unavailable intervals and rejected stage records retain their cohort labels.",
"For final rank r=0,…,6, tip appearance is max(C10,C37−r·p) and full unfolding occurs C39−C37 developmental units later. Effective spacing p takes registered80,120 or160-unit scenarios; it is not a measured thermal phyllochron. Prior-day visibility gates infection availability, while end-of-day capacity increases linearly through unfolding. Growth dilutes affected tissue. Earlier clipped ranks are unresolved lower-canopy approximations. The juvenile aggregate renews on the retained300-positive-degree-day scale and hands over normalized area as J=clip[(C39−A)/(C39−C31),0,1]; it is absent by39. This stage-based handover does not estimate measured natural senescence or absolute total leaf number. [[Jamieson1995|Abichou2018]]"
,'Seasonal disease states and weather',
"Each active leaf capacity contains susceptible tissue, three latent compartments, visible noninfectious tissue, infectious tissue and retained visible damage. Establishment depletes susceptible capacity. Latent and infectious transitions depend on the positive-temperature reference clock; existing states persist through cold intervals without a spring reset. Inactive leaves cannot receive or export infection. Tissue fractions conserve unit capacity; shrinking juvenile source area changes its donor weight rather than creating newly unfolded contact area. Latency constants are effective model settings, not independently measured infection-to-symptom durations for these fields. [[Shaw1990|Lovell2004]]",
"Local residue has relative unready and competent states. Weather-weighted development transfers potential between them, with a common thermal ageing rate conserving their analytic total decay. Initial local source1, readiness0.5,30-reference-day competence scale and90-reference-day ageing scale are declared hypotheses. Imported forcing is a separate relative background. These states do not estimate sexual spore maturation, measured winter survival or spore abundance. Local/imported primary establishment is weather dependent; secondary establishment also requires area-weighted infectious donor capacity. A rank-distance kernel represents rain-mediated transfer and a separate neighboring-leaf contact hypothesis acts during unfolding. Juvenile withdrawal cannot activate contact reception."
,"A duration-based daily wetness proxy uses mean/max temperature, mean relative humidity and precipitation. A24-bin reconstructed humidity cycle and effective rainfall duration generate dimensionless exposure. Training-only positive-rain weather determines the median precipitation/rain-hour scale,0.45 mm h⁻¹ for the final original-calibration fit. It is not independent measured canopy leaf wetness. Daily states use four equal substeps. The selected step is part of the frozen fit; smaller-step checks assess numerical convergence rather than silently recalibrating the setting."
,'Disease selection and sensitivity',
"The finite grid fixed and archived before fitting crosses4 primary scales,3 secondary scales,2 latent means,3 effective leaf spacings and2 imported backgrounds, giving144 settings. Three location-disjoint inner folds of the original28 calibration fields select minimum pooled top-three two-sided interval distance, with balanced assessment error and fixed enumeration resolving ties. Stage thresholds use the complete original-calibration stage set outside disease-inner folds; reused evaluation stages are excluded. A six-setting phenology-only benchmark independently selects spacing and delay. Final fits and preprocessing are frozen before reused validation scoring; prediction objects contain redacted disease values. Positive-magnitude perturbations leave signs and selection evidence unchanged.",
"Same-fit sensitivities remove local or imported source, remove secondary establishment or contact, alter initial readiness and ageing, vary effective spacing, retain the juvenile source, or withdraw juvenile/lower-rank capacity at declared stages. Observation cutoffs0.0001 and0.01 accompany the primary0.001 normalized-fraction cutoff. Effective first infection is the first total nonsusceptible-capacity crossing; symptoms use visible/infectious/retained capacity. These are observation-model conventions, not physiological infection thresholds or validated true infection dates. Sensitivities retain the frozen fit and do not select new parameters on evaluation outcomes."
,'Yield relevance',
"For daily disease-free reference leaf area L0,l and functional-loss fraction dl, the top-three deficit is HADloss,3=ΣdaysΣl=1…3 L0,l·dl, in GLAI-days. Conditional yield transfer is ΔY=b·HADloss,3. Parker et al.’s top-three sequential green-lamina assessments support a central slope0.0180 and cultivar range0.0141–0.0207 t ha⁻¹ per GLAI-day. Their assessments begin at GS31, use trapezoidal integration and have an unrecovered exact endpoint. The restricted flowering–BBCH85 daily rectangular window is an explicit adaptation. Both that window and a broaderGS31–85 sensitivity are retained. Foulkes et al.’s top-five coefficients are not substituted for top-three coefficients. [[Parker2004|Foulkes2006]]",
"The software accepts externally supplied reference LAI and functional loss; yield tracking is disabled without an explicit mode. The standardized replay specifies nominal upper-three LAI1, equal mature leaf areas and unfolding-dependent capacity, using simulated visible affected fractions as functional loss. The climate replay applies the declared detection gate before functional transfer. Actual healthy canopy area, senescence and local yields are not inferred. Percentage loss requires an independently supplied reference yield. Missing window endpoints produce missing conditional loss; excess over an independently supplied yield is flagged rather than clipped."
,'Climate forcing and spatial estimation',
"Daily NEX-GDDP-CMIP6v2 inputs cover ACCESS-CM2, MPI-ESM1-2-HR and MRI-ESM2-0 for SSP1–2.6,2–4.5 and5–8.5, with historical forcing followed by each SSP. Historical-only monthly temperature offsets, humidity-logit offsets and precipitation ratios align forcing to the reference archive. The study periods are1991–2020,2031–2060 and2071–2100. Calendar sowing and the first predicted85 crossing define each crop window. Leading pre-sowing and trailing post-endpoint weather cannot age source states or advance crop/disease dynamics. Unreached endpoints and unsupported forcing remain missing. [[NEXGDDPCmip6V2|Hersbach2020ERA5|GGCMIPhase32021]]",
"SPAM2020 all-wheat harvested area supplies geographical weights under the imposed winter/rainfed-calendar scenario. Four independent area-proportional draws with replacement per nonempty geographical stratum give64 draw identities in16 strata. Duplicate selected cells retain separate independent draw IDs. Annual/period estimates are ratios over valid area-time coverage. Future changes pair the same draw, climate model/SSP and relative-year index on common valid metric coverage. Stratified influence-function variance gives spatial Monte Carlo error; shared draws retain covariance when climate-model means are averaged. Three-model extrema describe climate spread, without probability weights or bootstrap parameter intervals. [[SPAM2020]]"
,'Software and reproducibility',
"The runtime contains object components for forcing, phenology, canopy, coupled seasonal sources/disease and conditional yield diagnostics. Immutable typed configurations supply every stage/process value. All rates are proposed before integration; instance/epoch ownership rejects foreign or stale proposals. Failed integration is transactional. Restart validates model/source version, parameter identity, consumed weather prefix, component epochs, physical clock order and terminal-output/state consistency before replacing live state. The fresh forcing series must include sowing; crop-mask exclusions freeze disease and residue.",
"Calibration, source preparation, observation mapping, benchmark selection and fitted-file conversion reside outside model/. The installable wheel contains model Python code and distribution metadata only. Independent comparisons cover24 combinations of latent-stage count, integration step and juvenile policy, yielding exact batch/daily state, pathway, event-date and prefix-restart agreement. The full repository suite contains301 passing tests; seven pre-existing donor datetime deprecation warnings remain. These checks establish numerical/software behavior rather than predictive accuracy. [[Holzworth2018APSIM|deWit2019WOFOST]]"
],
'availability.txt':[
'Data availability',
"Public trial archives, climate products and crop-calendar/area sources are identified in the reference list and input manifests. Source_Data.xlsx and the supplied CSV/Parquet tables retain stage constraints, sign/onset predictions, structural sensitivities, full-season replays, paired climate changes, coverage and sampling errors. Original source snapshots and earlier model outputs retain their separate version identities.",
"The retained German process-only validation archive includes all three cohorts and all GDD, T–P and T–P–V event predictions. French transfer tables, initial-conditioning definitions and earlier severity-model outcomes retain their original provenance. ERA5-derived forcing was retrieved through the Open-Meteo historical interface; interface URLs, download receipts and input hashes remain in the weather archive.",
'Code availability',
"The source package includes the pure object-oriented runtime, external calibration utilities, explicit example configuration/weather, frozen fits, evaluation tables and verification receipts. WHEAT_STB_ENGINE.md specifies interfaces, units, chronology and restart behavior. The model-only wheel executes with an explicit configuration and forcing file; no calibration archive is searched by the runtime. Full climate reruns require the checksum-identified input products or registered sampled-weather cache."
],
'supplementary_methods.txt':[
'Supplementary Information','Complete validation evidence',
"German station calibration, validation and testing retain all four original BBCH stages and both own-matched and common-event denominators. The full field-stage registry retains every original and additional threshold, all observation-censoring classes, the strict and overlapping full-source Corteva cohorts and both forcing horizons. The retained model-event, field-stage and coverage tables identify unavailable predictions and absent two-sided evidence. German phenology results, current disease outcomes and archived French transfers describe different targets and are not pooled.",
'Phenological identification',
"Ordered stage profiles, all normalized stage bounds and rejected conflicts accompany the stage-only calibration. Left-only observations provide compatibility without determining exact dates. Profiles at minimum loss and within1/2 days expose broad admissible thresholds. Leaf-rank status at BBCH31,32,33,37 and39 is supplied separately for80/120/160-unit spacing scenarios. It represents final-rank model capacity, not observed main-stem total leaf count.",
'Disease censoring and source uncertainty',
"All candidate scores, inner memberships and training-only meteorological preprocessing are retained. Left-, right- and two-sided histories remain separate. Secondary-off and source-off interventions are same-fit model changes, not identified causal treatment effects. The local source improvement in reused validation and upper-bound secondary setting remain part of the evidence. Occurrence specificity from a few zero-only field windows is weakly supported; zeros on early assessment dates constrain timing.",
'Conditional functional-area transfer',
"The reference canopy and affected-to-functional conversion are explicit scenario inputs. Daily leaf areas, modeled fractions, integration windows and every cultivar-slope product accompany the replay. The broaderGS31–85 and restricted65–85 climate tables permit time-window sensitivity. Literature tolerance ranges are not predictive intervals. Matched protected/untreated yields, measured healthy area and cause-specific senescence are absent in the present BASF/Corteva disease trials.",
'Climate coverage and sampling',
"All810 annual outputs retain64 distinct spatial draw IDs. Source weather has62 unique selected cells, with all687 annual input hashes verified. The registered eligible area excludes9 cells lacking calendar coverage. Period means and changes retain metric-specific missingness; event-time means are conditional on detected events. Unreached85 cases and the unsupported warm case are distinct from disease absence. Shared-draw ensemble Monte Carlo variance includes cross-model covariance.",
'Independent software and arithmetic verification',
"The biological kernel conserves tissue capacity and the two residue compartments follow their common analytic ageing relation. Cold intervals retain existing states; absent sources produce no infections; unavailable leaves cannot participate in transmission. The juvenile handover and contact-recipient exclusion have behavioral checks. Independent stage, onset, pathway, ratio, paired-coverage and Monte Carlo calculations agree with the frozen outputs. Snapshot and relocation addenda preserve original scientific evidence while documenting byte-identical runtime mathematics and the external calibration boundary."
]}))
