"""Nature Food manuscript text supported by the frozen current-model evidence."""
from pathlib import Path
from analysis.paper_study.nature_food_fix_20261007.sections import sections as previous_sections

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
TITLE = 'Wheat development moderates simulated climate effects on Septoria damage in Europe'
AUTHOR = 'Gang Zhao'
AFFILIATION = ('College of Soil and Water Conservation Science and Engineering '
               '(Institute of Soil and Water Conservation), Northwest A&F University, '
               'Yangling, Shaanxi, China')
EMAIL = 'gang.zhao@nwafu.edu.cn'


def sections():
    text = previous_sections()
    text['abstract.txt'] = [
        'Climate-related crop disease threatens the stability of European wheat production. How wheat development modifies the magnitude and spatial distribution of climate effects on Septoria damage remains poorly quantified. We coupled wheat and Septoria simulations across 62 sampled European cells, three climate models and three emissions pathways, alongside field benchmarks and published canopy–yield evidence. Under SSP5–8.5 in 2071–2100 relative to 1991–2020, host development offset 71% of the weather contribution, leaving a net increase of +2.64 healthy-area-duration deficit days per reference leaf area. Regional canopy changes ranged from −2.05 days in the Mediterranean to +9.27 days in the Boreal region, despite a positive European mean. Epidemic predictions generally underperformed benchmarks, and absolute yield effects remained unvalidated. These opposing regional responses identify crop–disease timing as a priority for evaluating climate adaptation and wheat-production resilience.'
    ]
    text['introduction.txt'] = [
        'Securing wheat production under climate change requires distinguishing changes in crop potential from the biotic stresses that prevent that potential being realized. European evidence links wheat yield trends to interacting genetic, climatic and agronomic drivers, while pathogens and pests account for substantial losses across major food crops. These production pathways are connected: a developmental shift that changes the crop’s exposure to weather also changes the timing of disease damage relative to grain filling. [[Silva2026|Savary2019]]',
        'Climate-based assessments of pathogen exposure and coupled crop–disease simulations demonstrate the relevance of infection to future crop production. Their interpretation depends on both disease-favouring weather and host development. The same future weather can accelerate crop development, alter the leaves available to disease and move grain filling into a different part of the season. The magnitude of a disease-related production effect therefore cannot be inferred from favourable infection conditions alone. [[Chaloner2021|Pequeno2024]]',
        'Septoria tritici blotch, caused by Zymoseptoria tritici, provides a relevant foliar-disease case for European wheat. Seasonal disease reflects local and imported sources, weather-dependent establishment, leaf appearance and transfer within the canopy. Temperature affects development of the crop and disease; humidity and precipitation affect exposure. Host architecture and developmental timing determine which leaves become available and when upper-canopy damage occurs. [[SuffertSache2011|ShawRoyle1989|LovellCanopy2004|Baccar2011|Lovell2004]]',
        'Healthy-area duration integrates the amount and persistence of functional green canopy. It is closer to the physiological link to grain production than a disease percentage integrated over time, but its relationship with yield depends on genotype, leaf scope and the integration window. Crop-calendar and genotype choices can consequently change both exposure and the production consequence of disease. Compatible observations of development, leaf function and harvest response are needed to evaluate those choices. [[Parker2004|Foulkes2006|vanDenBerg2017|McDonald2022]]',
        'The central hypothesis is that climate-driven changes in wheat development moderate weather-driven increases in cumulative upper-leaf damage. A paired European climate analysis separates the weather and host contributions, while field benchmarks and independent crop-response evidence establish the limits of production inference. The analysis distinguishes a mechanism within a coupled model from demonstrated disease-prediction skill and validated yield response. European wheat area defines the production context (Fig. 1); the crop–disease–canopy pathway is specified in Supplementary Fig. S17.'
    ]
    text['climate_results.txt'] = [
        'Results', 'European wheat area and the paired climate comparison',
        'The European domain contains 14,941 wheat cells, with 54.401 million harvested hectares having the imposed winter/rainfed crop calendar. All-wheat harvested area supplies fixed sampling weights; the domain is a crop-management scenario rather than a census of actual winter-wheat production. Four area-proportional draws in each of 16 strata produce 64 draw identities at 62 unique cells. Comparisons span three climate models and three emissions pathways, with 1991–2020, 2031–2060 and 2071–2100 harvest periods. The 51,840 draw-seasons include 51,813 completed seasons under supported forcing, 26 without a soft-dough endpoint and one with unsupported temperature. Fig. 1 retains the computed cell locations and their spatial context.',
        'Host development offsets much of the weather contribution',
        'Under late-century SSP5–8.5, modeled flag-leaf symptoms occur 3.66 days earlier relative to flowering than in the reference period; the three-climate-model range is −6.24 to −1.82 days. The upper-three-leaf healthy-area-duration (HAD) deficit rises from 6.50 to 9.12 days per unit nominal reference leaf area, a 2.62-day increase with a climate-model range of 1.28–4.39 days and spatial Monte Carlo standard error of 0.33 days. Mean flowering-to-soft-dough duration changes by only +0.12 days. Greater modeled damage therefore accompanies a change in disease–crop alignment rather than a consistent shortening of grain filling (Fig. 2a,b; Supplementary Table S9c).',
        'A four-combination decomposition separates weather and host-development contributions on the same supported-forcing population. The weather contribution is +9.00 HAD days and the host contribution −6.36 days per unit reference leaf area, giving a +2.64-day net change. The host term offsets 70.6% of the weather term, with individual climate-model fractions of 63.6–80.3%. All three models retain a positive weather contribution, a negative host contribution and a positive net change. The full weather–host interaction is −2.78 days and is allocated equally between the two contributions (Fig. 2c,d; Supplementary Tables S13a,b). These terms describe response to modeled forcing combinations, not causal effects of a tested management intervention.',
        'The decomposition excludes 20 of 5,751 finite draw-year pairs because an active hybrid forcing day exceeds the supported temperature range. Its 5,731 common pairs yield the 2.64-day net change; the baseline comparison on its original population yields 2.62 days. Host flowering and soft dough advance by 26.77 and 26.64 days after sowing, respectively. The offset therefore reflects the combined effects of development, leaf availability and crop-window placement. It cannot be attributed to grain-fill shortening alone.',
        'Scenario direction is stable within the selected model',
        'Fourteen settings vary source assumptions, effective rank spacing, added stage profiles, symptom detection, reference-canopy decline and functional conversion. Their 161,280 draw-seasons include seven disease–host integrations and fourteen reporting settings. On common pairs, every setting and climate model retains earlier flag-leaf symptoms and greater HAD deficit under late-century SSP5–8.5. Mean symptom changes span −5.46 to −1.54 days and deficit increases 0.63–2.80 days per unit reference leaf area. Timing coverage is 88.31–95.30%, conditional on symptoms being detected in both periods; HAD coverage is 99.972–100%. One individual setting/model combination gives a small positive effective-infection-date change, +0.014 days (Supplementary Fig. S15; Supplementary Table S11a).',
        'Lower-emissions comparisons give smaller ensemble canopy changes, but the climate models do not agree on every sign. Late-century HAD changes are +1.39, +1.50 and +2.62 days for SSP1–2.6, SSP2–4.5 and SSP5–8.5, respectively. The SSP1–2.6 climate-model range crosses zero. These are paired model comparisons under fixed crop-area and management assumptions, not quantified mitigation benefits. The single-year full-grid replay contains 14,772 completed seasons for the 2001 harvest and reproduces sampled outputs at matching cells; it does not establish a completed multi-period census (Supplementary Fig. S14).'
    ]
    spatial_results = [
        'Spatial contrasts across emissions pathways and environmental regions',
        'The positive European mean masks opposing sampled-cell responses across the six scenario–period comparisons (Fig. 3). In late-century SSP5–8.5, positive three-model ensemble canopy changes represent an estimated 75.0% of reference wheat area; the spatial Monte Carlo standard error is 6.0 percentage points. All three climate models show positive changes on an estimated 65.7% of area and negative changes on 20.8%, with non-unanimous signs on 13.5%. Under SSP1–2.6, the corresponding positive ensemble share is 98.2%, but unanimous positive agreement covers only 41.1%, while mixed signs cover 57.9%. The larger high-emissions European mean therefore accompanies stronger concentration of modeled damage, rather than a uniformly positive response across the wheat domain (Supplementary Table S14d).',
        'Exploratory environmental-domain ratios retain the original sampling weights within independently delineated EEA biogeographical regions. The Atlantic, Continental, Boreal, Mediterranean and Steppic regions contain 9, 18, 14, 9 and 12 registered draws, respectively. Under late-century SSP5–8.5, their HAD-deficit changes are +4.55, +3.63, +9.27, −2.05 and −0.06 days per unit reference leaf area. Boreal changes remain positive in all three climate models, spanning +6.33 to +13.58 days; Mediterranean changes remain negative, spanning −2.47 to −1.44 days. The Steppic model range crosses zero. Boreal means increase from +3.30 under SSP1–2.6 to +4.45 under SSP2–4.5 and +9.27 under SSP5–8.5, whereas Mediterranean means are approximately zero under the two lower pathways. Sparse and unrepresented regions retain explicit coverage without precise regional inference (Supplementary Fig. S19a,b; Supplementary Tables S14a,b).',
        'Disease–crop timing and the supported-forcing decomposition distinguish these opposing regional responses. Under late-century SSP5–8.5, Boreal symptoms advance by 8.53 days relative to flowering, while Mediterranean symptoms shift 4.51 days later; both signs persist across the three regional climate-model means. The supported Boreal weather contribution is +15.21 HAD days and the host contribution −5.94 days, an offset of 39.1%. Mediterranean contributions are +3.40 and −5.44 days, giving a 160.4% offset and a negative net change. Atlantic and Continental offsets are 62.6% and 63.6%; the Steppic offset is approximately 101%, with a near-zero net. These contrasts describe model-response components on region-specific supported populations, not observed geographic disease trends or tested adaptation benefits (Supplementary Fig. S19c,d; Supplementary Tables S14c,e).'
    ]
    text['climate_results.txt'].extend(spatial_results)
    text['field_results.txt'] = [
        'Crop-development evaluation and disease benchmarks',
        'The retained temperature–photoperiod–vernalization module has German station-held-out test MAE 8.02 days, RMSE 11.75 days and bias +0.50 days across 40,878 matched dates at BBCH 10, 31, 51 and 85. This evaluation uses known sowing and realized weather during 1985–2015. It supports the retained crop-development formulation without validating the subsequently added leaf stages or epidemic response (Supplementary Fig. S18; Supplementary Tables S1–S3).',
        'Added BBCH 32, 33, 37 and 39 thresholds have only 1, 5, 6 and 9 two-sided calibration intervals. Retrospective BASF 2019 flag-visibility and unfolding evidence comprises 3 and 4 intervals with median widths of 14 and 13.5 days; location-disjoint Corteva contributes 19 and 30 intervals with widths of 22 and 17.5 days. Flowering-proxy interval-excess error is 1.80 and 1.83 days in the two datasets. None of the five informative external BBCH 85 intervals contains the predicted soft-dough date; mean excess is 9.00 days. These sparse observations constrain the leaf and grain-fill windows used in the climate calculation (Supplementary Tables S3b–d and S9a).',
        'Disease calibration contains 28 field seasons, 254 assessments and eight two-sided source-leaf 1–3 onset histories in six fields. Fully nested selection re-estimates added stages, the flowering proxy and weather preprocessing within each training fold and retains the original disease and phenology-benchmark settings. Their pooled calibration onset losses are 1.00 and 0.17 days. Three disease settings share the minimum, while one training fold has no two-sided BBCH 32 interval. Correct nesting therefore preserves the selected model without resolving weak identification of its added developmental stages (Supplementary Table S10c).',
        'Retrospective epidemic prediction generally performs worse than simpler benchmarks. Onset interval-excess errors are 5.06 and 5.36 days in BASF 2019 and location-disjoint Corteva, compared with 3.00 and 2.75 days for the phenology benchmark. Paired differences are +2.06 days (95% grouped-bootstrap interval −2.75 to 6.31; eight coordinate-years) and +2.61 days (1.17–4.07; 54 coordinate-years). BASF timing differences remain poorly resolved; the Corteva comparison supports greater seasonal-model error on this population (Fig. 4a; Supplementary Table S10a).',
        'All-assessment severity RMSE is 26.63 and 32.63 percentage points, with biases of −14.73 and −18.55 and negative R². Calibration-leaf-mean RMSE is 22.99 and 31.86 percentage points. Paired RMSE differences are +3.64 (95% interval 1.18–6.04) and +0.76 (−1.10 to 2.51) percentage points (Fig. 4b,c; Supplementary Tables S8a and S10a). BASF explicitly identifies the flag leaf, whereas Corteva leaf 1 retains unresolved final-rank identity. Its timing result persists under alternative observation-population restrictions (Supplementary Table S10b). These evaluations qualify the future model response; they do not establish that present-day errors cancel under future climates.'
    ]
    text['baseline_results.txt'] = [
        'Canopy–yield evidence defines the production boundary',
        'Published STB experiments provide 117 protected-minus-unprotected yield contrasts across 25 cultivars and six site-years. Fitted upper-three-leaf green-area coefficients span 0.0141–0.0207 t ha⁻¹ per GLAI-day. The measured-area window begins at GS31, whereas the primary climate calculation integrates flowering to soft dough. These differences in temporal scope prevent the published coefficient from serving as direct validation of the modeled canopy deficit (Supplementary Tables S5a,b). [[Parker2004]]',
        'A separate top-five-leaf study provides eight aggregate contrasts across five genetic backgrounds. Two contrasts are STB-specific, two yellow-rust-specific and four have mixed disease exposure. All eight remain in the five-background holdout. Relative-yield RMSE is 5.16 percentage points and R² 0.247; absolute-yield RMSE is 0.617 t ha⁻¹ and R² −0.432. The mixed-disease treatment means inform the physiological canopy–yield relationship rather than validate the current STB model or its nominal upper-three-leaf area (Fig. 5a; Supplementary Tables S6a–c and S7). [[Foulkes2006]]',
        'Severity-based response models also fail to improve on training-mean predictions in the retained transfer comparisons. Nordic endpoint models use 67 contrasts across five trial environments and have relative-yield RMSE 4.16–4.17 versus 3.88 percentage points. The common-date window-integral models use 50 contrasts across five environments and give 5.54–5.56 versus 3.98. BASF transfer to 2019 gives 5.04–5.23 versus 3.60 percentage points across 12 contrasts in 11 fields (Fig. 5b). Severity percentage-days are not measured healthy-area duration, and management-associated yield contrasts do not isolate cause-specific crop loss (Supplementary Table S8b).',
        'At the reference coefficient 0.018, the baseline late-century SSP5–8.5 HAD increase gives a conditional yield-effect proxy of +0.047 t ha⁻¹ per unit nominal upper-three-leaf area. Across the settings and three fixed coefficients, ensemble changes span 0.009–0.058 t ha⁻¹ per unit reference area. Extending the integration window to GS31–85 gives 0.057 t ha⁻¹, 22% above the flowering-to-soft-dough value. These products describe dependence on canopy-function and transfer assumptions; they do not identify actual yield loss or total European production change. Table 1 separates supported endpoints from those conditional production quantities.'
    ]
    text['discussion_field_and_limits.txt'] = [
        'Discussion',
        'The European climate comparison identifies a compensating host-development contribution within the coupled wheat–Septoria model. Under late-century SSP5–8.5, that contribution offsets approximately 71% of the weather contribution to upper-leaf HAD deficit. The net remains positive in all three climate models. This result concerns the seasonal alignment of crop and disease: predicted flowering and soft dough advance together, while mean grain-fill duration changes little. Weather-only interpretation of disease-favouring conditions would therefore miss a substantial modeled host contribution.',
        'The distinction matters for production assessment because crop timing changes more than the calendar date of grain filling. It changes available leaf tissue and the weather encountered during the period when canopy function supplies grain growth. Previous climate–pathogen and coupled crop–disease assessments establish the relevance of this pathway; the present decomposition identifies its opposing components within a European wheat scenario. Recent European yield research likewise separates climatic, genetic and agronomic contributions rather than assigning observed production trends to a single driver. The current disease calculation adds a conditional biotic pathway, not a replacement for validated crop-growth and yield assessment. [[Chaloner2021|Pequeno2024|Silva2026]]',
        'Sensitivity agreement is evidence about the selected model, not comprehensive uncertainty about future epidemics. The fourteen settings retain earlier symptoms and increased canopy deficit, but unmeasured source abundance, cultivar resistance and source-to-leaf transmission remain weakly identified. Synthetic humidity reconstruction approximates exposure from daily weather and does not observe leaf wetness. The analysis does not include future pathogen adaptation, changing crop-area distributions or a validated coupling of carbon dioxide, resource stress, canopy function and yield. Current epidemic predictions generally fail to outperform simple benchmarks, and the added developmental endpoints have limited interval evidence. These limitations leave the magnitude of the real-world climate response unresolved.',
        'The production inference is further constrained by the measurement domain. A severity percentage can represent lesions and associated senescence without quantifying surviving photosynthetic area. Published HAD–yield relations retain genotype, leaf-scope and integration-window dependencies, and the mixed-disease dataset evaluates aggregate treatment means. Equal nominal leaf areas, assumed functional conversion and fixed yield coefficients are therefore scenario operators. Failure of severity-based yield transfer does not invalidate the physiological importance of healthy canopy; it establishes that the available scores cannot verify the simulated absolute-yield effects. [[Parker2004|Foulkes2006|vanDenBerg2017]]',
        'The policy-relevant implication is to evaluate calendar adjustment and disease resistance or tolerance as connected production choices. An earlier crop window can change weather–disease overlap, while resistance changes damage and tolerance changes the yield response to that damage. A host contribution generated by climate-driven development is not an achieved benefit of deliberately changing sowing or cultivar. Production-oriented evaluation requires development dates, disease assessments, reference and functional green area, and harvested yield on compatible observational units and windows. These endpoints distinguish exposure avoidance from tolerance and other treatment responses (Table 1). [[McDonald2022|Silva2026]]',
        'For European adaptation programmes, the evidence supports coordinated phenology–canopy–harvest monitoring in cultivar and calendar evaluations, common reporting of canopy-area and severity units, and independent validation across contrasting seasons and locations. This investment priority is consistent with the resilience and sustainable-production objectives of the European Vision for Agriculture and Food. The present continental sample does not rank country-level interventions, identify an optimal crop-protection practice or quantify avoided tonnes. Food-security relevance is restricted to the crop-production pathway; household access, utilization and market effects are outside the analysis. [[ECVision2025]]'
    ]
    text['discussion_field_and_limits.txt'].insert(3,
        'Spatial contrasts refine the continental interpretation. Stronger modeled weather contributions in the Boreal region exceed the compensating host contribution, whereas Mediterranean host development more than offsets the positive weather term. A European mean therefore combines opposing environmental responses, and an ensemble-mean map can conceal substantial climate-model disagreement under lower emissions. These exploratory contrasts identify environmental strata for joint crop-development, canopy and harvest validation. Regional calendar and cultivar choices require evidence that the simulated shifts translate into functional-canopy retention and yield stability; the current sample does not establish intervention rankings.')
    text['methods.txt'] = [
        p.replace('Table S13', 'Supplementary Table S13a')
        .replace('Four paired trajectories combine', 'Four paired model trajectories combine')
        .replace('registered disease grid', 'prespecified disease grid')
        .replace('registered SSP5–8.5 robustness ensemble', 'prespecified SSP5–8.5 sensitivity ensemble')
        .replace('their placeholder status is not inferred', 'the exclusions do not establish that zero records were placeholders')
        for p in text['methods.txt']
    ]
    text['methods.txt'] = [
        ('HAD deficit is the daily sum across the flag leaf and two leaves below it of reference green area multiplied by the assumed functional-loss fraction, in GLAI-days. The conditional grain product is the fixed crop-response coefficient multiplied by that deficit. Nominal mature upper-three-leaf LAI is one, divided equally among ranks and scaled by unfolding. The field replay uses simulated visible, infectious and retained fractions directly; the climate replay additionally gates their contribution by first symptom detection. Latent fractions are excluded. These reporting operators remain distinct from measured functional canopy loss.')
        if p.startswith('For reference green area') else p for p in text['methods.txt']]
    ix = text['methods.txt'].index('Weather–host decomposition')
    text['methods.txt'].insert(ix + 2,
        'The host offset is −100 times the host contribution divided by the weather contribution, using the same supported-forcing population. The ensemble offset is the ratio of the three-model mean contributions, not the mean of model-specific percentages. Individual-model extrema are deterministic spread, not a confidence interval. This ratio describes a contribution within the model and is not the efficacy of a management intervention (Supplementary Table S13b).')
    text['methods.txt'].insert(text['methods.txt'].index('Software and independent calculation checks'),
        'Spatial displays use arithmetic three-climate-model means of paired changes at the actual sampled cells. Duplicate draw locations are collapsed for display only; both identities remain in the area-weighted estimates. The wheat-area layer defines geographic weighting, not observed disease prevalence or a completed multi-period disease census. The current design has four draws per stratum and does not establish sampling convergence for national or subregional estimates.')
    insertion = text['methods.txt'].index('Software and independent calculation checks')
    text['methods.txt'][insertion:insertion] = [
        'Environmental-domain and spatial-sign summaries',
        'Independent EEA 2016 biogeographical boundaries assign environmental regions by intersection with each 0.25° wheat-cell centroid. Unmatched centroids and areas outside the delineated regions retain separate categories, with no nearest-region reassignment. Region-area totals use cells with an eligible imposed winter/rainfed calendar. The five named regions represented by at least four registered draws form the principal regional comparison; sparse and unsampled domains remain explicit. These domain analyses are exploratory and the boundaries are independent of simulated response. [[EEA2016]]',
        'For each climate model, environmental changes are ratios of design-weighted paired-change numerators to valid area-time denominators, multiplied by the fixed region indicator. Three-model means average the model-specific domain ratios. Stratified ratio-influence variance uses all four original draws per stratum, retaining zero contributions from other regions and covariance across shared GCM draws. Domain MCSE is withheld below four sampled draws. GCM extrema and sample MCSE retain distinct meanings and exclude biological and fitting uncertainty. Supported weather–host domain terms retain the same four-corner validity mask and high-temperature exclusions as the continental decomposition; regional host offset is the ratio of ensemble component means.',
        'Spatial-sign summaries classify the paired mean change at each sampled cell for each GCM and SSP-period combination. The original design weights estimate the reference-area shares with a positive ensemble mean, positive or negative changes in all three GCMs, and mixed signs. Duplicate sampled cells retain both draw identities. Sign fractions describe the sampled model-response distribution; they do not establish observed affected hectares or probabilities of future disease. Three-GCM completeness and valid-year coverage accompany each displayed cell.'
    ]
    text['availability.txt'] = [
        'Data availability',
        'Public BASF and Corteva disease archives, NEX-GDDP-CMIP6v2 forcing, the GGCMI crop calendar, SPAM2020 harvested area and EEA environmental boundaries are identified by persistent dataset references. Source_Data.xlsx contains the numerical evidence for the retained figures and tables, including the full disease-labelled published crop-response contrasts, weather–host contributions, sampled-cell scenario changes, environmental-region statistics and spatial-sign area shares. Individual predictions, paired populations, forcing identities and source checksums accompany Software_and_Evidence.zip. [[Holst2022BASF|HolstDonner2022Corteva|NEXGDDPCmip6V2|GGCMIPhase32021|SPAM2020|EEA2016]]',
        'Raw whole-domain climate products and sampled-weather caches remain external. Their manifests identify source products, versions and checksums; publication regeneration uses the included completed numerical evidence. A forcing-based rerun additionally requires those climate inputs. Published crop-response transcriptions retain source tables, units, leaf scope, disease exposure and aggregate/fitted status. Unavailable plot observations, covariance and measured functional-area trajectories are not reconstructed.',
        'Code availability',
        'The accompanying archive contains the frozen simulation runtime, calibration and evaluation code, publication sources, complete numerical evidence required for document regeneration, and synthetic example forcing. REPRODUCIBILITY.txt specifies environment dependencies and separate commands for publication regeneration and runtime execution. PACKAGE_MANIFEST.json records member checksums. Supplementary_Model_Specification.docx and Supplementary_Model_Specification.pdf contain 29 numbered equations; Parameter_inventory.csv records 84 fixed, fitted and scenario quantities.',
        'Author contributions',
        'G.Z. takes responsibility for the design, analysis, interpretation and reporting of the study.',
        'Funding',
        'This study received no external funding.',
        'Competing interests',
        'The author declares no competing interests.'
    ]
    si = text['supplementary_methods.txt']
    si = [p.replace('A separate published top-five dataset contains eight aggregate contrasts across five genetic backgrounds and is evaluated by leaving each background out of coefficient fitting.',
                    'A separate published top-five dataset contains eight aggregate contrasts across five genetic backgrounds: two STB-only, two yellow-rust-only and four mixed-exposure contrasts. All eight are retained in the published-data holdout; one background is omitted from fitting at a time. The dataset supplies broader physiological evidence, not STB-specific epidemic validation.')
            for p in si]
    j = si.index('Conditional canopy and yield operators')
    si.insert(j, 'The host-offset percentage is −100 times the host Shapley contribution divided by the weather Shapley contribution on the supported-forcing population. Model-specific percentages and the ratio of ensemble contributions are reported separately in Supplementary Table S13b. Both terms use the same unit reference area, so the ratio is dimensionless. It is a descriptive decomposition ratio rather than an adaptation-effect estimate.')
    si.extend([
        'Exploratory environmental-domain comparisons',
        'Official EEA 2016 biogeographical polygons intersect the centroid of each reference wheat cell; unmatched cells retain an Unassigned label and the source Outside class remains separate. The 62 simulated cells correspond to 64 draw identities; both duplicate identities remain in statistical estimation. Environmental reference areas are exact sums of eligible registry cells, while estimated sample-domain weights are separate quantities. Alpine, Black Sea and outside-region domains have no sampled response estimates; Pannonian and Unassigned domains each have one draw and no reported regional MCSE. All domains and both future periods remain in source data. [[EEA2016]]',
        'For draw i, GCM m and region r, x contains the average paired change with invalid years set to zero, z the fraction of valid paired years, and I the fixed region indicator. The region estimate is ΣwIx/ΣwIz. Its influence is I(x−μz)/(ΣwIz). Stratum variance is the sum of squared stratum weights multiplied by within-stratum influence variance divided by four. Ensemble variance applies this rule to the mean GCM influence vector, preserving shared spatial-sample covariance. Region means are not recombined using external area totals because that would change the original sampling estimator.',
        'Supported weather–host regional contributions use all four frozen corner trajectories and exclude the same unsupported hybrid draw-year pairs as Table S13a. Their denominator is identical within a region and GCM, ensuring that weather plus host equals the net. Regional host-offset percentages use the ratio of ensemble component means; values above 100% identify a host contribution exceeding a positive weather term. Such values describe a negative net canopy response within the model, rather than intervention efficacy. Baseline and supported populations can differ, including the Continental changes of +3.63 and +3.68 HAD days.',
        'Area-sign estimates apply the original 64 draw weights to cell-level three-GCM completeness and sign indicators. All plotted HAD cells have complete three-GCM period means. Positive ensemble fraction and unanimous positive fraction answer different questions; mixed-sign cells can have a positive ensemble mean. Projected spatial coverage remains restricted to the 62 simulated cells. Spatial Monte Carlo standard errors exclude GCM selection, ecological-parameter and yield-transfer uncertainty (Supplementary Tables S14a–e).'
    ])
    text['supplementary_methods.txt'] = si
    declarations=text['availability.txt'].index('Author contributions')
    text['declarations.txt']=text['availability.txt'][declarations:]
    text['availability.txt']=text['availability.txt'][:declarations]
    return text
