"""Results-led article text with explicit spatial and validation scope."""


TITLE='Climate-sensitive leaf development links wheat disease timing and yield exposure'


def refine_sections(raw):
    raw['abstract.txt']=[
        'Climate-driven changes in wheat disease can affect grain production through the timing and duration of upper-leaf damage. A seasonal Septoria model links leaf development, source continuity and weather to top-three-leaf exposure, with crop–yield relationships evaluated separately. Field stages and symptoms constrain the model; public treatment–yield contrasts test crop-response transfer. Reused BASF and Corteva validation gives symptom interval-excess losses of5.06 and5.36 days, exceeding a phenology benchmark. A European stratified replay comprises51,840draw-seasons across three climate models and three SSPs. Late-century SSP5–8.5 advances modeled flag-leaf infection4.81 days relative to flowering and increases nominal-LAI yield transfer0.0471 t ha⁻¹. Poor severity prediction and failed public-trial response transfer prevent interpreting these conditional changes as validated grain losses. Spatial maps retain coverage, crop-area assumptions and the distinction between current sampled results and earlier full-grid simulations.'
    ]
    raw['introduction.txt']=raw['introduction.txt'][1:]
    raw['introduction.txt'][-1] += ' The linked crop, disease and yield framework has separate evidence requirements at each scale (Figure1).'
    raw['methods.txt'].insert(2,'BASF source labels explicitly identify the flag leaf. Corteva INFECT is documented as disease severity, while the deposited ordinal-leaf convention does not independently establish final flag-leaf identity. Source-numbered and modeled final-rank endpoints therefore retain distinct interpretations; unavailable contemporaneous observed stages do not prove leaf emergence.')
    f=raw['field_results.txt']
    f[2]=('The retained crop-development formulation has German station-held-out test MAE8.02 days, RMSE11.75 days and bias+0.50 days across40,878 matched events. '
        'The station split uses known sowing and realized weather, while the added flag stages use separately normalized field observations. '
        'This distinction preserves the evidence supporting crop development without transferring phenology accuracy to disease outcomes (Figure2a; Table S1).')
    f.append('Numerical leaf-severity trajectories provide an additional epidemic check. Under the frozen model, hierarchy-weighted all-assessment RMSE is26.63 percentage points in BASF2019 and32.63 in strict Corteva. Final observed-leaf RMSE is32.54 and45.44 percentage points, with biases−20.09 and−32.09; weighted R² is negative. On comparable observed-stage-covered records, a calibration-only stage/time baseline has lower error. The seasonal model therefore supports conditional process comparisons, while its current magnitude and timing errors constrain grain-loss interpretation. Observed-stage baselines describe a different information setting and are not substituted for future predicted stages (Supplementary Table S12a).')
    raw['baseline_results.txt'].append(
        'Separate public-trial crop-response models use signed relative treatment response1−Yuntreated/Ytreated and whole-trial holdouts. In67 Nordic contrasts across five environments with the recorded non-target diseases measured as zero, endpoint models have RMSE4.16–4.17 percentage points, compared with3.88 for the training-mean baseline. A50-contrast observed-window severity-integral analysis also fails that baseline. Corresponding BASF top-three severity-window models trained in2017–2018 do not improve2019 transfer over the training mean. These measured severity integrals are percentage-days and cannot be relabelled as HAD. The tested public-data models do not establish a general absolute yield-loss function (Supplementary Table S12b).')
    raw['climate_results.txt'].append(
        'Geographical evidence preserves three distinct spatial supports. Fixed harvested area covers14,941 reference wheat cells; current three-model period diagnostics use64 area-proportional draws at62 unique locations. These sampled values are shown at their actual coordinates, without interpolating uncomputed cells (Figure6; Figures S13–S14). Earlier full-grid baseline, climate-change and production-exposure maps retain their seasonal-v1 identity (Figures S15–S18). A completed current-model2001 replay reaches all14,941 registered cells and reproduces the sampled outputs at matching locations, but one harvest year does not constitute completed baseline and future-period censuses (Figure S19).')
    discussion=raw['discussion_field_and_limits.txt']
    for index,paragraph in enumerate(discussion):
        if paragraph.startswith('Matched protected/untreated yield,'):
            discussion[index]=paragraph.replace(
                'Matched protected/untreated yield, healthy reference area, cultivar resistance and cause-specific senescence are unavailable for the present disease trials.',
                'Treatment-associated relative harvest yields are recovered for a BASF subset, while matched healthy reference area, cultivar resistance and cause-specific senescence remain unavailable.')
    discussion[-1]=('A food-production interpretation requires independently supported epidemic trajectories, geographical crop exposure and a crop-response model measured on compatible leaves and time windows. '
        'Current numerical severity error and public-trial yield-transfer failure limit that chain. Source/canopy assumptions, coarse weather, cultivar resistance, spring–winter crop-area allocation and future management add uncertainty. '
        'The continental diagnostics quantify responses of specified crop-protection scenarios; they do not identify realized European grain losses. Separate crop-development and physiological frameworks provide broader process scope, but cannot replace the missing disease–yield validation. [[Holzworth2018APSIM|deWit2019WOFOST]]')
    methods=raw['methods.txt']
    i=methods.index('Software and reproducibility')
    technical=methods[i+1:]
    raw['supplementary_methods.txt']+=['Software implementation and numerical verification',*technical]
    raw['methods.txt']=methods[:i]+['Reproducibility',
        'The simulation runtime, external fitting utilities, frozen configuration records and observation/evaluation tables are supplied with source hashes. Numerical equivalence checks are separate from field predictive validation. Software interfaces and restart verification are retained in Supplementary Information.']
    raw['supplementary_methods.txt'] += [
        'Spatial evidence and map coverage',
        'Figure6 retains the full reference crop-area map alongside point-based current-model diagnostics. Figures S13–S14 show every SSP and both future periods on common signed colour scales. The area-proportional sample contains64 independently registered draws at62 unique cells; coincident draw locations collapse only for plotting, while every draw retains its identity in regional estimators. Exact cell/GCM/year coverage accompanies each mapped metric. Grey land is cartographic context and does not establish absence of wheat or disease.',
        'Figures S15–S18 reproduce the earlier domain, ERA5 baseline, climate-change and production-exposure figures without changing their source definitions. Their seasonal-v1 process, severity mappings, calendar sensitivities and full-grid masks differ from the current seasonal-source model. The archived map values remain separate from current-model validation and from empirical crop-response fits.',
        'Figure S19 uses the completed2001 full-grid replay of the unchanged current kernel. There are14,941 registered cells,14,932 valid winter/rainfed calendars,14,772 completed seasons,160 unreached soft-dough endpoints and9 missing calendars. Exact sample-to-grid comparison covers58 numerical and10 date metrics. This computational check validates spatial bookkeeping for one year, without identifying epidemic biology or providing a completed30-year climate contrast.',
        'Public-trial crop-response validation',
        'The Nordic analysis preserves recorded disease-free controls, signed severity differences and negative yield responses. The five-environment endpoint population has67 contrasts, while a50-contrast subset supplies common observed-date severity integrals. All arms sharing an untreated control stay in the same trial holdout. Trials receive equal total metric weights. An origin-constrained linear model and an exponential log-yield-ratio model are independently fitted on each training subset; neither improves the complete-population training-mean benchmark. A positive-STB-only subset and a small cultivar/year transfer challenge retain separate roles.',
        'A four-disease complete-covariate domain contains131 contrasts across eight environments. Unmeasured diseases are not set to zero. Null and weakly supported covariates make transfer unstable, and the source records include an additional co-occurring leaf-spot disease. The exponential link bounds positive response by construction, but does not recover predictive skill. The observed target remains management-associated relative yield response, with residual control disease and unresolved effects of other stresses. It is not disease-free potential yield.',
        'BASF source harvest ratios independently reproduce the published MCALCR identity without assuming missing mass units. Eight predeclared upper-leaf linear/exponential crop-response candidates retain a2017–2018 training and2019 transfer split. All-three per-leaf window integrals comprise12 training contrasts in8 fields and12 transfer contrasts in11 fields; their leaf-specific windows can differ. The stronger requirement of simultaneous complete top-three scores has only9 training contrasts in5 fields and4 transfer contrasts in4 fields. These limitations preclude a universal top-three HAD conversion.']
    raw['supplementary_methods.txt']=[paragraph.replace(
        'Matched protected/untreated yields, measured healthy area and cause-specific senescence are absent in the present BASF/Corteva disease trials.',
        'Treatment-associated harvest ratios are available for a BASF subset. Corresponding measured healthy-reference area and cause-specific senescence remain absent; the Corteva yield-to-leaf measurement linkage is not established.')
        for paragraph in raw['supplementary_methods.txt']]
    for name in ['field_results.txt','climate_results.txt']:
        raw[name]=[p.replace('Table1','Table S11a').replace('Table2','Table S11b').replace('Table3','Table S11c') for p in raw[name]]
    return raw
