"""Measured BASF disease/treatment-relative-yield links; no response or biological model fitting."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
import numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parents[4];OUT=Path(__file__).resolve().parent;SOURCE=ROOT/'data/basf-wheat-diseases.txt'
LEAVES={'LEAF, 1ST / FLAG LEAF':1,'LEAF, 2ND':2,'LEAF, 3RD':3}

def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 OUT.mkdir(parents=True,exist_ok=True);sourcehash=sha(SOURCE);b=pd.read_csv(SOURCE,sep='\t');b['source_row']=np.arange(2,len(b)+2);b['season_year']=b.Date.str[:4].astype(int);b['leaf_rank']=b.PlantPart.map(LEAVES);b['coordinate_year']=b.Latitude.map(lambda x:f'{x:.6f}')+','+b.Longitude.map(lambda x:f'{x:.6f}')+'|'+b.season_year.astype(str)
 membership=pd.read_csv(ROOT/'analysis/paper_study/seasonal_calibration_v1/field_season_membership.csv',dtype={'source_unit':str});mp=membership.set_index('source_unit').partition.to_dict()
 y=b.loc[b.Parameter.eq('ERTRNE')&b.Method.eq('MWCGS')&b.PlantPart.eq('GRAIN')];r=b.loc[b.Parameter.eq('ERTRNE')&b.Method.eq('MCALCR')&b.PlantPart.eq('GRAIN')].set_index(['TrialId','Treatment']);u=y.loc[y.Treatment.eq('Untreated')].set_index('TrialId');contrasts=[]
 for z in y.loc[~y.Treatment.eq('Untreated')].itertuples():
  if z.TrialId not in u.index:continue
  utc=u.loc[z.TrialId];tr=r.loc[(z.TrialId,z.Treatment)];ur=r.loc[(z.TrialId,'Untreated')];cid=f'BASF|{z.TrialId}|{z.season_year}|{z.Treatment}';ratio=float(tr.Value/ur.Value);error=float(tr.Value-100*z.Value/utc.Value);assert abs(error)<1e-5 and utc.NumSprays==0 and ur.Value==100 and z.season_year==utc.season_year
  contrasts.append(dict(contrast_id=cid,TrialId=z.TrialId,season_year=z.season_year,country=z.Country,latitude=z.Latitude,longitude=z.Longitude,coordinate_year=z.coordinate_year,untreated_label='Untreated',matched_treatment_label=z.Treatment,untreated_num_sprays=int(utc.NumSprays),treated_num_sprays=int(z.NumSprays),source_MCALCR_untreated=float(ur.Value),source_MCALCR_treated=float(tr.Value),measured_relative_yield_ratio=ratio,measured_relative_yield_gain_percent=float(tr.Value-ur.Value),untreated_harvest_date=utc.Date,treated_harvest_date=z.Date,same_harvest_date=bool(utc.Date==z.Date),relative_identity_error_pp=error,untreated_MWCGS_source_row=int(utc.source_row),treated_MWCGS_source_row=int(z.source_row),untreated_MCALCR_source_row=int(ur.source_row),treated_MCALCR_source_row=int(tr.source_row),source_area_unit='HA',source_mass_unit='unreported',yield_component_membership='development_2017_2018' if z.season_year<2019 else 'held_out_2019_no_response_fit_in_this_audit',existing_epidemic_membership=mp.get(str(z.TrialId),'outside_original_ordinal_epidemic_membership'),prior_epidemic_outcome_reuse=True,fully_disease_free_control_identified=False,product_or_biological_plot_identity_identified=False))
 c=pd.DataFrame(contrasts);assert len(c)==87 and c.TrialId.nunique()==71;c.to_csv(OUT/'source_yield_contrasts.csv',index=False)
 disease=b.loc[b.Organism.eq('SEPTTR')&b.Parameter.eq('INFECT')&b.Method.eq('P%INF')&b.leaf_rank.notna()].copy();disease['score_eligible']=disease.Value.between(0,100)&disease.Clarifier.ne('CROP INJURY');assert disease.groupby(['TrialId','Treatment','Date','PlantPart']).size().max()==1
 pairs=[];outer=[];availability=[];integrals=[];top3=[];native_other=[];other_context=[]
 for z in c.itertuples():
  one=disease.loc[disease.TrialId.eq(z.TrialId)&disease.Treatment.isin(['Untreated',z.matched_treatment_label])];eligible=one.loc[one.score_eligible];utc=eligible.loc[eligible.Treatment.eq('Untreated')];trt=eligible.loc[eligible.Treatment.eq(z.matched_treatment_label)];a=utc.merge(trt,on=['TrialId','Date','PlantPart','leaf_rank'],how='outer',suffixes=('_untreated','_treated'),indicator=True,validate='one_to_one');a['contrast_id']=z.contrast_id
  spray_u=one.loc[one.Treatment.eq('Untreated'),'NumSprays'].dropna().unique();spray_t=one.loc[one.Treatment.eq(z.matched_treatment_label),'NumSprays'].dropna().unique();consistent=bool(len(spray_u)<=1 and len(spray_t)<=1 and (not len(spray_u) or spray_u[0]==z.untreated_num_sprays) and (not len(spray_t) or spray_t[0]==z.treated_num_sprays));matched=a.loc[a._merge.eq('both')].copy();counts=matched.groupby('leaf_rank').Date.nunique().to_dict();complete=matched.groupby('Date').leaf_rank.nunique();complete_dates=complete.loc[complete.eq(3)].index.tolist()
  oth=b.loc[b.TrialId.eq(z.TrialId)&b.Treatment.isin(['Untreated',z.matched_treatment_label])&b.Parameter.eq('INFECT')&~b.Organism.isin(['SEPTTR','NNNNN'])].copy();codes=sorted(oth.Organism.unique());raw_stb_u_dates=sorted(utc.Date.unique());raw_stb_t_dates=sorted(trt.Date.unique());availability.append(dict(contrast_id=z.contrast_id,TrialId=z.TrialId,season_year=z.season_year,matched_treatment_label=z.matched_treatment_label,coordinate_year=z.coordinate_year,yield_component_membership=z.yield_component_membership,existing_epidemic_membership=z.existing_epidemic_membership,source_treatment_spray_history_consistent=consistent,duplicate_field_treatment_date_leaf_keys=False,n_untreated_top3_rows=len(utc),n_treated_top3_rows=len(trt),n_common_date_leaf_rows=len(matched),n_common_F1_dates=int(counts.get(1,0)),n_common_F2_dates=int(counts.get(2,0)),n_common_F3_dates=int(counts.get(3,0)),any_leaf_common_ge2=bool(any(v>=2 for v in counts.values())),F1_common_ge2=bool(counts.get(1,0)>=2),F2_common_ge2=bool(counts.get(2,0)>=2),F3_common_ge2=bool(counts.get(3,0)>=2),all3_leaves_each_common_ge2=bool(all(counts.get(k,0)>=2 for k in [1,2,3])),n_complete_top3_common_dates=len(complete_dates),complete_top3_common_ge2=bool(len(complete_dates)>=2),first_any_common_date='' if matched.empty else matched.Date.min(),last_any_common_date='' if matched.empty else matched.Date.max(),untreated_only_date_leaf_rows=int(a._merge.eq('left_only').sum()),treated_only_date_leaf_rows=int(a._merge.eq('right_only').sum()),crop_injury_annotation_rows_excluded=int(one.Clarifier.eq('CROP INJURY').sum()),other_codes_ever_recorded=';'.join(codes),native_other_disease_rows=len(oth),other_code_missing_is_zero=False))
  for row in a.itertuples():
   # Outer rows are a completeness audit; missing scores remain missing.
   outer.append(dict(contrast_id=z.contrast_id,TrialId=z.TrialId,season_year=z.season_year,matched_treatment_label=z.matched_treatment_label,date=row.Date,source_leaf_label=row.PlantPart,leaf_rank=int(row.leaf_rank),untreated_score=row.Value_untreated,treated_score=row.Value_treated,both_scores_available=bool(pd.notna(row.Value_untreated) and pd.notna(row.Value_treated)),untreated_source_row=row.source_row_untreated,treated_source_row=row.source_row_treated))
  for row in matched.itertuples():
   rec=dict(contrast_id=z.contrast_id,TrialId=z.TrialId,season_year=z.season_year,country=z.country,coordinate_year=z.coordinate_year,matched_treatment_label=z.matched_treatment_label,date=row.Date,source_leaf_label=row.PlantPart,leaf_rank=int(row.leaf_rank),untreated_severity_percent=float(row.Value_untreated),treated_severity_percent=float(row.Value_treated),measured_severity_reduction_pp=float(row.Value_untreated-row.Value_treated),untreated_GsFrom=row.GsFrom_untreated,untreated_GsTo=row.GsTo_untreated,treated_GsFrom=row.GsFrom_treated,treated_GsTo=row.GsTo_treated,untreated_Daft=int(row.Daft_untreated),treated_Daft=int(row.Daft_treated),untreated_num_sprays=int(row.NumSprays_untreated),treated_num_sprays=int(row.NumSprays_treated),source_treatment_spray_history_consistent=consistent,untreated_source_row=int(row.source_row_untreated),treated_source_row=int(row.source_row_treated),untreated_Clarifier=row.Clarifier_untreated,treated_Clarifier=row.Clarifier_treated,untreated_SampleUnit=row.SampleUnit_untreated,treated_SampleUnit=row.SampleUnit_treated,source_method='P%INF',source_parameter='INFECT',unit='percentage_points',measured_relative_yield_ratio=z.measured_relative_yield_ratio,measured_relative_yield_gain_percent=z.measured_relative_yield_gain_percent,source_MCALCR_treated=z.source_MCALCR_treated,treated_MCALCR_source_row=z.treated_MCALCR_source_row,yield_component_membership=z.yield_component_membership,existing_epidemic_membership=z.existing_epidemic_membership,prior_epidemic_data_reuse=True,native_other_codes_ever_recorded=';'.join(codes),fully_protected_control=False,absolute_leaf_area_observed=False)
   pairs.append(rec)
   for code in codes:
    k=oth.loc[oth.Organism.eq(code)&oth.Date.eq(row.Date)&oth.PlantPart.eq(row.PlantPart)];ku=k.loc[k.Treatment.eq('Untreated')];kt=k.loc[k.Treatment.eq(z.matched_treatment_label)];assert len(ku)<=1 and len(kt)<=1
    other_context.append(dict(contrast_id=z.contrast_id,TrialId=z.TrialId,season_year=z.season_year,date=row.Date,source_leaf_label=row.PlantPart,leaf_rank=int(row.leaf_rank),other_source_code=code,untreated_other_score=np.nan if ku.empty else float(ku.Value.iloc[0]),treated_other_score=np.nan if kt.empty else float(kt.Value.iloc[0]),untreated_other_source_row='' if ku.empty else int(ku.source_row.iloc[0]),treated_other_source_row='' if kt.empty else int(kt.source_row.iloc[0]),untreated_record_present=not ku.empty,treated_record_present=not kt.empty,source_organ_scope='exact same leaf and actual date',missing_disease_record_is_zero=False))
  for leaf,g in matched.groupby('leaf_rank'):
   g=g.sort_values('Date');days=pd.to_datetime(g.Date);span=int((days.max()-days.min()).days)
   if len(g)>=2 and span>0:
    t=(days-days.min()).dt.days.to_numpy();iu=float(np.trapezoid(g.Value_untreated,t));it=float(np.trapezoid(g.Value_treated,t));integrals.append(dict(contrast_id=z.contrast_id,TrialId=z.TrialId,season_year=z.season_year,coordinate_year=z.coordinate_year,matched_treatment_label=z.matched_treatment_label,leaf_rank=int(leaf),source_leaf_label=g.PlantPart.iloc[0],n_common_assessment_dates=len(g),window_start=g.Date.iloc[0],window_end=g.Date.iloc[-1],window_days=span,untreated_severity_integral_percent_days=iu,treated_severity_integral_percent_days=it,measured_severity_integral_reduction_pp_days=iu-it,window_mean_severity_reduction_pp=(iu-it)/span,first_untreated_GsFrom=g.GsFrom_untreated.iloc[0],first_untreated_GsTo=g.GsTo_untreated.iloc[0],last_untreated_GsFrom=g.GsFrom_untreated.iloc[-1],last_untreated_GsTo=g.GsTo_untreated.iloc[-1],first_treated_GsFrom=g.GsFrom_treated.iloc[0],last_treated_GsFrom=g.GsFrom_treated.iloc[-1],n_reversed_untreated_stage_ranges=int(g.GsFrom_untreated.gt(g.GsTo_untreated).sum()),n_reversed_treated_stage_ranges=int(g.GsFrom_treated.gt(g.GsTo_treated).sum()),untreated_source_rows=';'.join(map(str,g.source_row_untreated.astype(int))),treated_source_rows=';'.join(map(str,g.source_row_treated.astype(int))),observed_date_interpolation='trapezoidal between common measured scores only; no extrapolation',integral_is_HAD_or_absolute_leaf_area=False,measured_relative_yield_ratio=z.measured_relative_yield_ratio,measured_relative_yield_gain_percent=z.measured_relative_yield_gain_percent,yield_component_membership=z.yield_component_membership,source_treatment_spray_history_consistent=consistent))
  for date in complete_dates:
   g=matched.loc[matched.Date.eq(date)].set_index('leaf_rank');top=dict(contrast_id=z.contrast_id,TrialId=z.TrialId,season_year=z.season_year,matched_treatment_label=z.matched_treatment_label,date=date,yield_component_membership=z.yield_component_membership)
   for leaf in [1,2,3]:top[f'F{leaf}_untreated_score']=float(g.loc[leaf,'Value_untreated']);top[f'F{leaf}_treated_score']=float(g.loc[leaf,'Value_treated']);top[f'F{leaf}_measured_reduction_pp']=float(g.loc[leaf,'Value_untreated']-g.loc[leaf,'Value_treated'])
   top3.append(top)
  for rr in oth.itertuples():native_other.append(dict(source_row=int(rr.source_row),TrialId=rr.TrialId,season_year=rr.season_year,date=rr.Date,Treatment=rr.Treatment,NumSprays=int(rr.NumSprays),Organism=rr.Organism,PlantPart=rr.PlantPart,Parameter=rr.Parameter,Method=rr.Method,Clarifier=rr.Clarifier,SampleUnit=rr.SampleUnit,GsFrom=rr.GsFrom,GsTo=rr.GsTo,Value=float(rr.Value),source_file=str(SOURCE.relative_to(ROOT)),zero_is_recorded=bool(rr.Value==0),record_is_not_imputed=True))
 av=pd.DataFrame(availability);long=pd.DataFrame(pairs);win=pd.DataFrame(integrals);native=pd.DataFrame(native_other).drop_duplicates('source_row');tables={'contrast_disease_availability.csv':av,'paired_STB_common_date_long.csv':long,'paired_STB_outer_date_audit.csv':pd.DataFrame(outer),'paired_STB_leaf_window_integrals.csv':win,'complete_top3_common_date_scores.csv':pd.DataFrame(top3),'native_other_disease_records.csv':native,'paired_other_disease_same_date_context.csv':pd.DataFrame(other_context)}
 for name,table in tables.items():table.to_csv(OUT/name,index=False)
 # One contrast row supplies future response modelling keys without fitting a component.
 wide=c.merge(av.drop(columns=['TrialId','season_year','matched_treatment_label','coordinate_year','yield_component_membership','existing_epidemic_membership']),on='contrast_id',validate='one_to_one')
 for leaf in [1,2,3]:
  w=win.loc[win.leaf_rank.eq(leaf),['contrast_id','n_common_assessment_dates','window_start','window_end','window_days','untreated_severity_integral_percent_days','treated_severity_integral_percent_days','measured_severity_integral_reduction_pp_days']].copy();w=w.rename(columns={k:f'F{leaf}_{k}' for k in w.columns if k!='contrast_id'});wide=wide.merge(w,on='contrast_id',how='left',validate='one_to_one')
 wide.to_csv(OUT/'response_component_candidate_contrasts.csv',index=False)
 summary=[]
 for label,g in [('all_source_yield_contrasts',av),*list(av.groupby('yield_component_membership'))]:
  for requirement,mask in [('any_common_upper3_score',g.n_common_date_leaf_rows.gt(0)),('any_upper3_leaf_ge2_common_dates',g.any_leaf_common_ge2),('flag_ge2_common_dates',g.F1_common_ge2),('penultimate_ge2_common_dates',g.F2_common_ge2),('third_ge2_common_dates',g.F3_common_ge2),('all3leaves_each_ge2_common_dates',g.all3_leaves_each_common_ge2),('all3leaves_simultaneous_ge2_common_dates',g.complete_top3_common_ge2)]:
   q=g.loc[mask];summary.append(dict(membership=label,requirement=requirement,contrasts=len(q),fields=q.TrialId.nunique(),coordinate_years=q.coordinate_year.nunique(),shared_untreated_fields_are_not_independent_contrasts=True))
 sm=pd.DataFrame(summary);sm.to_csv(OUT/'paired_yield_linkage_counts.csv',index=False)
 assert sha(SOURCE)==sourcehash and len(long)==long[['contrast_id','date','leaf_rank']].drop_duplicates().shape[0]
 for z in long.itertuples():assert b.loc[b.source_row.eq(z.untreated_source_row),'Value'].iloc[0]==z.untreated_severity_percent and b.loc[b.source_row.eq(z.treated_source_row),'Value'].iloc[0]==z.treated_severity_percent
 receipt=dict(created_utc=datetime.now(timezone.utc).isoformat(),source_file=str(SOURCE.relative_to(ROOT)),source_sha256=sourcehash,source_MD5=hashlib.md5(SOURCE.read_bytes()).hexdigest(),source_doi='https://doi.org/10.5281/zenodo.6521175',grain_harvest_fields=c.TrialId.nunique(),verified_relative_yield_contrasts=len(c),common_date_score_rows=len(long),eligible_leaf_window_integrals=len(win),ambiguous_spray_history_contrasts=int((~av.source_treatment_spray_history_consistent).sum()),duplicate_date_leaf_keys=0,source_treatment_identity='anonymous BASF TreatmentA–D label with consistent source NumSprays; product/plot/replicate/application chronology unreported; related Corteva TreatmentCode denotes latest application and is not substituted as a BASF plot identity',measurement_semantics='measured source P%INF percentage score reductions at matching actual dates; sampled-window trapezoidal percentage-days only; no leaf-area or disease-free-control interpretation',target='source MCALCR_treated/MCALCR_untreated; source untreated MCALCR100; ratio algebra verified against within-trial MWCGS without mass-unit inference',response_model_fitted=False,biological_model_fitted=False,new_2019_response_target_used_for_fitting=False,global_untouched_2019_test_claimed=False,epidemic_data_reuse_declared=True,native_other_records_missing_is_zero=False,confidence_intervals_invented=False,artifact_rows={name:len(table) for name,table in tables.items()},checks=dict(all_common_date_scores_recomputed_from_raw_rows=True,source_unchanged=True,relative_yield_identity_max_error_pp=float(c.relative_identity_error_pp.abs().max()),common_keys_unique=True),limitations=['Trial-level anonymous source-treatment series are identifiable; individual biological plots and replicate IDs are not.','All common-date reductions remain signed; worse disease in treated arms is not suppressed.','Scores missing on either treatment/date/leaf are not filled or treated as zero.','Other disease observations are retained with original codes and organs; missing disease codes do not establish absence.','Yield2019 is excluded from fitting any new response component in this audit; archive-wide prior exposure is not certified absent.','Leaf integrals use different measured windows where source histories differ; only complete-top3 dates share all three leaf histories simultaneously.'])
 receipt['artifact_rows']['source_yield_contrasts.csv']=len(c);receipt['artifact_rows']['response_component_candidate_contrasts.csv']=len(wide);receipt['artifact_rows']['paired_yield_linkage_counts.csv']=len(sm);receipt['audit_code_sha256']=sha(Path(__file__));(OUT/'linkage_audit_receipt.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False)+'\n');print(sm.to_string(index=False));print('Other native records',len(native),'common matched scores',len(long),'leaf integrals',len(win),'ambiguous sprays',receipt['ambiguous_spray_history_contrasts']);print('Year yield totals',c.groupby('season_year').agg(contrasts=('contrast_id','size'),fields=('TrialId','nunique'),coordinate_years=('coordinate_year','nunique')).to_string())

if __name__=='__main__':main()
