"""Generate formal local Methods and research-design documents."""
from pathlib import Path
import json
from docx import Document
from docx.shared import Inches,Pt

ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'analysis/septoria'
sections=[
('Data sources and study population',
'''The disease archive combines BASF wheat trials and six additional public data collections. The original BASF dataset contains 2,276 records from 76 trial identifiers, 56 rounded coordinate pairs and 65 coordinate-years across 12 country labels during 2017–2019. Disease observations use source percentage-infection codes; treatment, assessment date and plant-part labels are retained. Septoria tritici blotch, caused by Zymoseptoria tritici, has 1,162 records and occurs in all 76 trials. The archive also contains rusts, tan spot, powdery mildew and several incompletely resolved fungal categories. Yield records are ancillary outcomes rather than disease states [1].

Public repositories supplied 39 files with verified repository MD5 and local SHA256 checksums. The Swiss collection contains 21,420 scanned leaves from two destructive collections. The main controlled-inoculation panel contains 4,684 seedling records challenged with three isolates and 50,395 valid damage or pycnidial scores; additional transgenic and mutant sheets remain separate experimental designs. The French field collection contains 2,400 plant-assessment records, 7,774 numeric leaf scores and 2,366 senescence markers. Its greenhouse population-phenotyping tables contain 39,024 plant–leaf scores and classifications of 3,035 field-origin isolates. The Tunisian source contains 3,004 deposited leaf scans, rather than the 3,074 scans stated in its repository abstract. Scans condition on pycnidia-positive leaves. Thermal mortality, germination and in-vitro growth measurements provide process information; Nordic–Baltic management and yield data cover mixed leaf-blotch pathogens and are ancillary [2–6].

The ETH high-frequency leaf-image archive and a separate rain-splash dataset were identified but their raw observations were not downloaded. Associated rain-splash analysis code is archived without being counted as a measurement dataset. No unavailable records contribute to numerical summaries.'''),
('Harmonization and quality control',
'''A common 29-column long schema represents each scientific measurement cell. EPPO scientific names and country labels are normalized, while original taxon codes and country labels remain in source files and a crosswalk. Fields identify the dataset, original file, table, row and column; source record and plot; location; calendar date or days after inoculation; host and pathogen information; treatment, replicate and leaf category; metric, unit, numeric value, raw value, quality state and measurement role. The scientific study partition contains 604,861 cells. Hourly ERA5, daily ERA5 and phenology simulations retain the same schema in separate Parquet partitions. Observation counts represent cells, not independent biological replicates. A separate cell archive preserves 1,422,177 cells or packed weather records from all collected spreadsheet and CSV tables, including headers, derived views and fitted candidates. Original byte files remain authoritative for provenance and formatting.

Dates are stored as ISO calendar dates; controlled challenges retain days after inoculation without fabricated field coordinates. Different percentages retain different denominators. Necrosis, pycnidial coverage, incidence, percentage infection with an unspecified basis, and percentage-of-control yield are distinct metrics. Relative Tunisian indices remain derived views and are not labelled absolute percentages. Percentage-of-control yield is allowed above 100. The 2019 Tunisian weather workbook repeats the previous season’s dates; its original values remain available with a calendar-quality flag and are excluded from dated joins. BASF absolute-yield units remain unspecified, and heterogeneous magnitudes are not rescaled.

The French S sentinel identifies senescent leaves and is represented as a leaf state, rather than zero infection. Missing and unresolved scores remain distinct from true zeros. Invalid area percentages and undefined pycnidia density on zero lesion area retain their source values with missing normalized values. Repeated source labels are not automatically deduplicated when their numerical measurements differ. Original source growth-stage inconsistencies and assessment metadata remain in the cell archive and quality tables. Plant or leaf labels do not establish the longitudinal identity of the same physical leaf.'''),
('ERA5 acquisition and weather alignment',
'''Hourly ERA5 forcing was obtained through the Open-Meteo historical-weather API, explicitly selecting models=era5, UTC, the nearest grid cell and elevation=nan. These settings retain ERA5 selection without default model blending or elevation adjustment. Each request includes 2-m air temperature, relative humidity and dew-point temperature; precipitation and liquid rain; 10-m wind speed; and surface shortwave radiation. Requests, native units, retrieval times, requested and returned grid coordinates, raw JSON responses and hashes are archived. ERA5’s regridded atmospheric product has a 0.25° grid [7,8].

The point archive covers 72 coordinate-seasons at 59 requested locations and 54 distinct ERA5 grid cells, comprising 676,128 unique hourly records and 28,172 complete UTC daily records. Every expected timestamp is present and each day has 24 records. Overlapping September windows share weather rows, which are deduplicated by location and timestamp. Requested-to-grid distances are retained. The French coordinate represents the research station; exact plot coordinates are unavailable.

Daily mean and extreme temperature, mean humidity and wind, precipitation and liquid-rain totals, rainy hours above 0.1 mm, and hours at relative humidity of at least 90% are calculated from hourly values. Integrated radiation is the sum of hourly mean W m−2 multiplied by 3,600 s and divided by 10⁶, yielding MJ m−2. Precipitation and rain refer to the preceding hour and are assigned to the UTC date of the returned interval-ending timestamp. Humidity exposure does not measure leaf wetness or canopy saturation.

Fixed coverage intervals extend from 1 September of the preceding year to 30 September of the observation year. Their 395 or 396 days include post-assessment weather and are used only for descriptive context. Disease-exposure summaries use the 30 completed UTC days strictly before each assessment. The untreated Septoria archive contains 609 rows; six injury annotations remain flagged. Eligible disease observations correspond to 279 coordinate-date windows and 275 distinct ERA5 grid-cell/date windows. Every exposure window contains 30 complete days and 720 hourly records. Retrospective realized weather supports a conditional hindcast and does not test operational weather forecasts.'''),
('T–P–V phenology implementation and evaluation',
'''Host development uses the schema-2 known-sowing process model from the AGC-Transformer archive. All copied runtime function bodies retain identical syntax trees; import adaptations, source hashes and frozen parameters are recorded. Supplied daily GDD is authoritative. An explicit temperature-forcing reconstruction matches all 11,862,724 original daily records: effective development is zero below 0°C, equals mean temperature from 0 to 20°C, remains 20°C d through 30°C, and declines as 20−2(Tmean−30) above 30°C. Only 48 original records directly represent that declining branch, up to 30.867°C; warmer transfer cases extrapolate its slope. The original forcing-generator code is unavailable.

Daylength derives from latitude and solar declination using the source’s fixed 365-day denominator. The photoperiod factor is clipped 1−0.09(16−daylength), active between previous-day thermal sums of 142.01 and 1,426.78°C d. Vernalization responds piecewise linearly to −4, 0, 10 and 16°C with relative rates 0, 1, 1 and 0. Sensitivity begins at a previous-day T–P sum of 142.01°C d and ends at 582.80°C d. The vernalization modifier is 0.3+0.7 min(CUMVER/40,1), with the original high-temperature devernalization rule retained. Daily T–P–V accumulation is GDD multiplied by the photoperiod and vernalization modifiers.

Frozen stage thresholds are 142.01, 542.30, 986.65 and 1,760.39 effective°C d for BBCH10, 31, 51 and 85. BBCH85 denotes soft dough. Anthesis, intermediate leaf emergence and canopy architecture are not supplied by this core. Parameters are pooled training medians from 187 German winter-wheat stations and contain no cultivar identity. Explicit sowing dates supply five Swiss, French and Tunisian transfer cases with 1,478 daily simulations. BASF sowing dates are absent and are not inferred.

Archived process-model evaluation reserves 1,223 German test stations; 83 stations are excluded from scoring because the original complete-feature filter lacks a valid consecutive 150-day window. The scored cohort contains 1,140 stations. Training, validation and test cohorts all contain 1985–2015; the split tests station transfer rather than future-year prediction. Metrics are calculated on the shared matched event set for GDD, T–P and T–P–V, with unmatched events reported separately. The shared test set contains 40,878 of 43,177 observed events. Independent replay reproduces 270 numerical metrics from 430,440 retained event rows. German phenology evaluation does not establish European disease-model performance.'''),
('Conditional disease benchmark and validation design',
'''The initial disease benchmark includes untreated SEPTTR records with valid 0–100 percentages and excludes CROP INJURY annotations. A sequence requires at least three dates at the same explicit leaf rank within a trial, with one record per date. The selected panel contains 46 trials, 91 series and 315 observations across 42 coordinate-years and 37 rounded coordinates. Relative leaf categories are preserved; repeated rank labels do not establish the same physical leaf.

Each test sequence is conditioned only on its first observed disease proportion y₀: S₀=1−y₀, E₀=0, I₀=y₀ and R₀=0. The observation proxy is y=1−S. This initialization and the mapping from visible percentage infection to compartment fractions are working assumptions rather than measured infectious or latent areas. Subsequent test outcomes are unavailable to parameter fitting or state initialization.

The comparator contains secondary transmission with primary infection force fixed to zero. Daily weather modulation is f=exp[−0.5((T−18)/8)²]×[1−exp(−P/2)]×H/24, where T is daily mean air temperature, P is liquid rain in mm and H is hours with RH≥90%. Thermal optima, the rainfall scale and multiplicative structure are uncalibrated working functions. Daily transfers are S[1−exp(−βIf)], E[1−exp(−max(T,0)/(18L))] and I[1−exp(−1/14)]. Synchronous updates retain non-negative states and total mass of one. The reference latent period L is 20 days at 18°C; 10 and 30 days are separately refitted sensitivities. The infectious period of 14 days is fixed. These durations are assumptions and are not assigned a literature-derived interpretation.

The global β coefficient is fitted only to training disease responses, initially within 0–1 d−1. Forward-fold sensitivities allow upper bounds of 5 and 10 d−1 with unchanged training data. Persistence predicts y₀ at all later dates. A trained global logit trend predicts logistic[logit(clip(y₀,0.005,0.995))+rt], with r estimated only from training outcomes.

Forward validation trains on 2017 for 2018 and on 2017–2018 for 2019, removing test coordinates from training. Separate leave-country-out folds assess spatial transfer using all available years in the remaining countries. No random observation-level split is used. Retrospective daily weather is truncated to the day preceding each predicted assessment. RMSE, MAE and bias are expressed in percentage points, giving equal weight to coordinate-years, then series within each coordinate-year, and subsequent dates within each series. Conditioning observations are excluded from scoring. All baselines use identical test records and weights. Fixed-parameter sensitivities do not represent predictive confidence intervals.

The model cannot initiate infection in the 25 sequences with y₀=0 because primary, cross-leaf and latent initial sources are absent. These sequences remain in evaluation. The 3 declines among 224 consecutive same-rank assessments are retained without monotonic correction. The benchmark tests post-observation progression and does not identify primary-infection onset or independently estimate primary and secondary contributions.'''),
('Descriptive process analysis and mapping',
'''Controlled pycnidia sequences are classified as interval-, left- or right-censored, or unobserved, using only valid score cells. Positive fractions and median coverage are calculated separately by isolate and observation day, retaining changing denominators. Persistent zero scores can indicate resistance or failed establishment and are not treated as arbitrarily long latent periods.

Necrotic area and pycnidia density are averaged within plot and collection date before descriptive rank correlations are calculated. Swiss and Tunisian observations retain separate populations. Tunisian conditional leaf sampling and repeated plot-incidence values are not interpreted as independent whole-canopy samples. French upper-leaf scores are averaged within plot, cultivar, date and leaf rank, followed by unweighted averaging over observed plots; senescent leaves are excluded from numeric disease averages and retained as states.

Geographic maps use archived Natural Earth public-domain boundaries and ETRS89 / LAEA Europe, EPSG:3035 [9]. BASF rounded points are not jittered into invented field positions. The French station marker is distinguished from exact field coordinates. Trial coverage, repeated same-rank assessments and weather context are separate map attributes. A shared precipitation colour scale supports comparison of fixed coverage intervals. Standalone PNG and PDF figures retain complete captions, source credit and numeric companion tables.'''),
('European application and conditional climate extension',
'''The main disease-application target is winter bread wheat. Current continental preparation consists of genuine ERA5 exposure layers and a separate hourly-forcing extraction pipeline. The initial geographic mask contains 40 European-country polygons including Cyprus, within 25°W–65°E and 34–72°N, with Russia clipped at 60°E. The United Kingdom and non-EU countries are included; European Turkey is excluded from this initial mask. The masked monthly climate product contains 22,140 selected native-grid centres for the fixed 2017–2019 intervals. Its registration differs from the hourly product; each native transform is retained. Monthly climatology does not substitute for daily epidemic forcing. A separate continental extraction for 1 May 2019 contains 24 hours and 22,198 grid centres. At 32 shared point-archive grid cells, temperature differs by up to 0.035°C and precipitation by 0.428 mm; humidity and rain thresholds differ by up to two and four hours. Provider precision and feature definitions require compatibility checks before model transfer.

Europe-wide disease application additionally requires a wheat-specific area product, regional sowing calendars, resistance or cultivar scenarios, leaf emergence and canopy transport, and a calibrated observation model. Accessible WorldCereal winter-cereal layers combine wheat, barley and rye and are not wheat-specific. The initial disease comparator does not validate these components or continental infection probabilities.

A leaf-resolved development formulation separates λₗ(t)=λprimary,ₗ(t)+Σₘβₗₘ(t)Iₘ(t). Primary inoculum and transmission from other leaf layers both contribute to new E infections; temperature-dependent development transfers E to I, and tissue senescence or exhausted reproduction contributes to removal. Host emergence changes susceptible area. T–P–V supplies developmental gates, with additional parameters required for leaf appearance and canopy architecture. Mechanistic separation of these terms does not establish statistical identification from sparse visible-disease observations.

The core paper question concerns independent predictive skill and transfer across sites, seasons and climates. Regional outcomes include stage-specific exposure, onset timing, secondary cycles, peak disease, seasonal burden, uncertainty and extrapolation beyond observed environmental support. Parameter estimation, inoculum, phenology and forcing uncertainty require separate accounting. Country or regional summaries require wheat-area weighting; land-cell averages are climate summaries rather than wheat disease burdens.

The climate extension is conditional on an unresolved scientific question after independent evaluation and historical regional application. It requires a bias-adjusted multi-model climate ensemble, explicit historical and future periods, and documented emissions pathways. Paired simulations with fixed and responsive phenology separate direct pathogen-weather responses from changes in host development; inoculum and resistance scenarios identify additional assumptions. ERA5 historical layers and uniform warming perturbations are not future climate projections. Additional scenario maps cannot resolve inadequate predictive validation or unidentifiable primary-infection mechanisms.''')]
references=[
'1. Holst et al. Data from56 fungicide trials in wheat fields across Europe2017–2019. Repository archive10.5281/zenodo.6521175. https://doi.org/10.5281/zenodo.6521175',
'2. Karisto et al. Ranking Quantitative Resistance to Septoria tritici Blotch in Elite Wheat Cultivars Using Automated Image Analysis. Phytopathology,10.1094/PHYTO-04-17-0163-R. Data mirror: https://zenodo.org/records/4933099; original data: https://doi.org/10.5061/dryad.171q4',
'3. Hafeez et al. Septoria tritici blotch resistance gene Stb15 encodes a lectin receptor-like kinase. Nature Plants,10.1038/s41477-025-01920-2. https://doi.org/10.1038/s41477-025-01920-2; data: https://doi.org/10.5281/zenodo.14515753',
'4. Orellana-Torrejon et al. Annual dynamics of Zymoseptoria tritici populations in wheat cultivar mixtures: A compromise between the efficacy and durability of a recently broken-down resistance gene? Plant Pathology,10.1111/ppa.13458. https://doi.org/10.1111/ppa.13458; data: https://doi.org/10.15454/4MAAI0',
'5. Ben M’Barek et al. Improved control of septoria tritici blotch in durum wheat using cultivar mixtures. Plant Pathology,10.1111/ppa.13247. https://doi.org/10.1111/ppa.13247; data: https://doi.org/10.5281/zenodo.3979476',
'6. Chaloner et al. A new mechanistic model of weather-dependent Septoria tritici blotch disease risk. Philosophical Transactions of the Royal Society B,10.1098/rstb.2018.0266. https://doi.org/10.1098/rstb.2018.0266; data: https://doi.org/10.6084/m9.figshare.7937516. Nordic–Baltic ancillary repository: https://doi.org/10.6084/m9.figshare.19203377.v4',
'7. Copernicus Climate Change Service. ERA5 hourly data on single levels. https://doi.org/10.24381/cds.adbb2d47',
'8. Open-Meteo. Historical Weather API documentation. https://open-meteo.com/en/docs/historical-weather-api; Earth Engine ERA5 Monthly catalogue: https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_MONTHLY',
'9. Natural Earth. Public-domain national boundaries and terms of use. https://www.naturalearthdata.com/about/terms-of-use/'
]
text='Data and methods for Septoria model evaluation and European application\n\n'+'\n\n'.join(h+'\n\n'+p for h,p in sections)+'\n\nReferences\n\n'+'\n\n'.join(references)+'\n'
assert not any(x in text.lower() for x in ['this report will','according to the user','writing plan','we will'])
(OUT/'Methods.txt').write_text(text)
doc=Document();sec=doc.sections[0];sec.top_margin=sec.bottom_margin=Inches(.8)
doc.styles['Normal'].font.name='Times New Roman';doc.styles['Normal'].font.size=Pt(11)
doc.add_heading('Data and methods for Septoria model evaluation and European application',0)
for h,p in sections:
    doc.add_heading(h,1)
    for paragraph in p.split('\n\n'):doc.add_paragraph(paragraph)
doc.add_heading('References',1)
for r in references:doc.add_paragraph(r)
doc.save(OUT/'Methods.docx')
protocol='''Cross-scale evaluation of a weather-driven Septoria model in European winter wheat

Primary research question

Predictive skill across independent seasons and locations, and its transfer to wheat-growing regions, constitute the core study. Climate-change impacts are a conditional extension. Disease data volume alone does not establish primary–secondary process identifiability or geographical validity.

Model evaluation

Component tests distinguish host phenology, establishment and latent development, visible damage, reproductive development and transmission. Full infection-force evaluation requires external inoculum or defensible process constraints and a calibrated observation model. Same-rank disease series require plot-level clustering. Forward-year and country or spatial-block holdouts compare predictions against persistence, epidemic trend and mechanism ablations. Disease-onset errors, severity RMSE/MAE, seasonal burden and calibrated interval coverage provide complementary outcomes where their observations exist. Primary onset and airborne inoculum are currently unobserved in most BASF trials.

Current evidence

The initial conditional secondary-only SEIR yields forward-year RMSE34.58 and32.43 percentage points for2018 and2019; the global logit trend yields24.70 and20.10. Releasing the transmission bound improves some errors but does not remove that gap. Twenty-five sequences begin with zero disease, requiring a hidden, external or cross-leaf infection source. German T–P–V test MAE8.023days supports its original station-transfer domain, with no independent disease validation. These findings support revision of the compartment observation mapping and canopy inoculum terms before continental disease application.

European application

A wheat-specific harvested-area layer, regional sowing calendar, cultivar or resistance scenarios, daily weather and leaf-layer transport define the regional simulation domain. Supported outcomes are spatial distributions of infection timing, stage-specific risk, epidemic burden and uncertainty. Wheat-area weighting is required for regional burden; WorldCereal winter cereals are a host-context layer rather than a wheat mask. Environmental extrapolation maps identify regions without validation support. Europe-region ERA5 exposure rasters and a verified hourly extraction path are available; validated continental disease maps are not yet generated.

Conditional climate extension

Climate scenarios address a remaining question about direct pathogen-weather effects, altered host phenology or regional shifts after model evaluation. Bias-adjusted multi-model ensembles and baseline/future periods retain forcing uncertainty. Fixed-host and responsive-host comparisons separate phenological mediation; inoculum, resistance and sowing scenarios expose management assumptions. Historical ERA5 and simple temperature perturbations do not constitute future climate projections. Climate extension is not a substitute for predictive skill.
'''
(OUT/'European_study_protocol.txt').write_text(protocol)
print('Methods.docx, Methods.txt and European_study_protocol.txt generated.')
