"""Crop-production manuscript grounded in completed infection and yield evidence."""
from pathlib import Path
import json
from analysis.paper_study.overwinter_leaf_model_20261006.manuscript.sections import sections as archived_sections

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
TITLE = 'Climate change advances wheat Septoria symptoms and increases modeled yield-relevant canopy damage'


def sections():
    original = archived_sections()
    required = [HERE/'validation/final_verification.json', HERE/'climate/independent_verification.json',
                HERE/'specification/equation_verification.json']
    if not all(path.is_file() for path in required):
        raise ValueError('Completed statistical, climate and mathematical evidence is required.')
    return {
        'abstract.txt': [
            'Warming can alter the overlap between wheat development and Septoria tritici blotch, but the consequences for functional canopy and grain production remain uncertain. We coupled a seasonal infection model to wheat phenology and evaluated it against field observations, published crop-response data and climate projections. Retrospective validation showed substantial uncertainty in disease timing and severity, limiting yield attribution. Under late-century SSP5–8.5, simulated flag-leaf symptoms advanced by 3.66 days relative to flowering, while the upper-three-leaf healthy-area-duration deficit increased by 2.62 days per unit nominal leaf area. This net response reflected opposing modeled contributions from disease weather (+9.00 days) and host development (−6.36 days). The direction of symptom timing and canopy deficit persisted across 14 structural and canopy settings, whereas estimated yield effects remained conditional on unvalidated canopy-function and yield-response assumptions. These results identify crop development and functional-canopy measurements as priorities for evaluating climate adaptation in wheat production.'
        ],
        'introduction.txt': [
            'Wheat production responds to climate through crop development, resource availability and infection by plant pathogens. Disease-induced loss of photosynthetically active tissue creates a production pathway that differs from direct heat or water effects. Climate-dependent pathogen pressure has been compared with crop yields, and coupled wheat–disease simulations have assessed infection-related production impacts. The production consequence of a foliar infection also depends on which leaves are affected and when their function is lost. [[Savary2019|Chaloner2021|Pequeno2024]]',
            'Septoria tritici blotch, caused by Zymoseptoria tritici, links autumn–winter sources, weather-dependent establishment and later disease on the upper canopy. Local residue, infected living leaves and imported inoculum can contribute to the seasonal sequence. Leaf appearance changes the receiving tissue available to infection, while canopy architecture affects subsequent contact and splash transfer. Temperature influences crop development and disease progression; humidity and precipitation influence the effective exposure supporting establishment. The resulting damage cannot be interpreted from a terminal severity measurement alone. [[SuffertSache2011|ShawRoyle1989|LovellCanopy2004|Baccar2011|Lovell2004]]',
            'Healthy-area duration integrates the size and persistence of functional canopy area. Its relationship with yield depends on leaf scope, radiation, genotype and source–sink balance. Measurements of green area consequently support a different production inference from a disease percentage integrated over time. Wheat adaptation studies demonstrate the importance of crop calendars, while infection can change the consequences of developmental shifts during grain filling. Resolving this interaction can improve the evidence used to target crop protection and climate adaptation toward stable grain production. [[Parker2004|Foulkes2006|vanDenBerg2017|McDonald2022]]',
            'The central hypothesis is that climate-driven changes in the alignment of leaf development and infection alter cumulative upper-leaf damage during grain filling, even where occurrence and grain-fill duration change little. A coupled seasonal representation separates crop development, infection establishment, visible damage and conditional yield response (Figure1). Field stages and disease histories evaluate the developmental and epidemic components; public crop-response data test transfer to yield. European climate comparisons and structural sensitivities distinguish the direction of simulated effects from uncertainty in their production magnitude.'
        ],
        'field_results.txt': [
            'Results', 'Crop development and leaf availability',
            'The retained temperature–photoperiod–vernalization formulation has German station-held-out test MAE8.02 days, RMSE11.75 days and bias+0.50 days across40,878 matched events at BBCH10,31,51 and85. This spatial holdout uses known sowing and realized weather during1985–2015. Added BBCH32,33,37 and39 thresholds use stage observations from the original calibration fields; their genuinely two-sided interval counts are only1,5,6 and9. Their identification is therefore substantially weaker than the pooled German event evidence (Figure2; Tables S1–S3 and S9a).',
            'In BASF2019, genuinely bracketed flag visibility and unfolding have3 and4 intervals, median widths14 and13.5 days, and mean distances outside the intervals3.67 and0.50 days. Corresponding location-disjoint Corteva values are19/30 intervals,22/17.5-day widths and2.37/1.13-day excesses. Flowering-proxy excess is1.80/1.83 days across35/65 intervals. None of the five informative external BBCH85 intervals contains the predicted soft-dough date; mean excess is9.00 days. These endpoints constrain the crop window over which infection-related damage is integrated (Tables S3b–d and S9a).',
            'Fully nested original-calibration selection re-estimates added stages, the flowering proxy and weather preprocessing within each disease-training fold. It selects the same disease and phenology-benchmark settings as the original conditional selection, with pooled onset losses1.00 and0.17 days. Three disease settings share the nested primary minimum. One training fold has no bracketed BBCH32 observation;116 exact-minimum threshold values span543.41–671.16 development units. Correct nesting preserves the chosen setting while exposing weak stage identification (Table S10c).',
            'Weather-dependent infection and visible disease',
            'The original disease calibration contains28 field seasons,254 assessments and only8 genuinely bracketed source-leaf1–3 onset histories in6 fields. Its selected effective setting has a20-reference-day latent mean,120-unit rank spacing and imported background0.1; the secondary establishment scale lies at the grid upper bound. Initial local source abundance, imported pressure and cultivar resistance are unmeasured, so these coefficients describe a conditional seasonal trajectory rather than separately identified biological source contributions (Tables S4a–e and S9b).',
            'The seasonal model has onset interval-excess losses5.06 and5.36 days in BASF2019 and strict Corteva, compared with3.00 and2.75 days for the phenology benchmark. Paired model-minus-benchmark differences are2.06 days (95% grouped-bootstrap interval−2.75 to6.31;8 coordinate-years) and2.61 days (1.17–4.07;54 coordinate-years). Balanced assessment accuracy is lower by11.60 and8.33 percentage points. The Corteva comparison supports poorer timing under the specified grouping; the smaller BASF timing comparison remains uncertain (Figure3a; Table S10a).',
            'BASF explicitly identifies source leaf1 as the flag leaf. Its four bracketed flag-leaf histories give a timing difference−2.50 days (−9.00 to1.50). Corteva source leaf1 has54 histories and a difference+3.06 days (1.55–4.61), but its final-rank identity is unresolved. Restriction to complete same-day observed stages and exclusion scenarios for preflag zero assessments retain the poorer Corteva timing result. Source-numbered Corteva leaves are consequently distinct from confirmed final-rank observations (Table S10b).',
            'All-assessment severity RMSE is26.63 percentage points in BASF2019 and32.63 in Corteva, with biases−14.73 and−18.55 and negative R². Calibration-leaf-mean errors are22.99 and31.86 percentage points. The paired RMSE differences are3.64 (95% interval1.18–6.04) and0.76 (−1.10 to2.51). An observed-stage/time comparator has lower error on its shared population, although it uses contemporaneous metadata unavailable to future simulations. Greater process detail therefore does not establish greater epidemic accuracy (Figure3b–c; Table S10b).'
        ],
        'baseline_results.txt': [
            'Infection-related canopy damage and grain-yield response',
            'Complete weather extensions give218 full-source field replays, including the two Corteva fields excluded from strict transfer. Modeled effective infection precedes flowering in all F1–F3 trajectories, with median relative dates−28,−40 and−51 days; symptoms occur at−12,−20 and−30 days. The flowering–BBCH85 mean conditional yield product is0.118 t ha⁻¹ per unit nominal upper-three LAI at coefficient0.018. These event dates and functional-loss fractions are simulated; actual green-area deficit and field yield are not recovered from them.',
            'Published STB experiments provide117 protected-minus-unprotected yield contrasts across25 cultivars and six site-years. Their fitted top-three green-area coefficients span0.0141–0.0207 t ha⁻¹ per GLAI-day. The original measured-area integration begins at GS31, whereas the current flowering–BBCH85 window is a restricted adaptation. Across a separate eight-contrast, five-background top-five study, withheld-background relative-yield RMSE is5.16 percentage points and R²0.247; absolute-yield RMSE is0.617 t ha⁻¹ and R²−0.432. These aggregate treatment means support the canopy–yield connection but do not validate the current simulated top-three losses (Tables S5a,b, S6a–c and S7). [[Parker2004|Foulkes2006]]',
            'Independent-trial response models in67 Nordic treatment contrasts across five trial environments have relative-yield RMSE4.16–4.17 percentage points, compared with3.88 for the training-mean benchmark. Common-date endpoint predictors in67 contrasts give5.54–5.56 versus3.98. BASF top-three severity-window transfer from2017–2018 to2019 gives5.04–5.23 versus3.60 percentage points across12 evaluation contrasts in11 fields (Figure4). The Nordic endpoint predictors are percentage points; the common-date integral and BASF severity-window predictors are percentage-days. None measures HAD. These management-associated yield contrasts constrain production inference without directly testing the published green-area relationship (Tables S6b,c, S7 and S8b).',

        ],
        'climate_results.txt': [
            'Climate effects on infection, damage and conditional yield',
            'European comparisons use three climate models, three SSPs and64 area-proportional draws at62 unique cells. A fixed all-wheat harvested-area registry supplies54.401 million hectares with available winter/rainfed calendars; this is an imposed crop-management scenario. The original90-year-period design contains51,840 draw-seasons:51,813 reach BBCH85 with supported forcing,26 do not reach it and one encounters an unsupported daily mean above40°C. Missing cases remain excluded from their metric-specific numerators and denominators.',
            'Under late-century SSP5–8.5, baseline F1,F2 andF3 effective-infection dates shift−4.81,−7.85 and−14.51 days relative to flowering; F1 symptoms shift−3.66 days, with a three-model range−6.24 to−1.82. Mean flowering–BBCH85 duration changes only+0.12 days, with both shorter and longer model-specific windows. Upper-three-leaf HAD deficit increases from6.50 to9.12 days per unit nominal LAI: a2.62-day change, model range1.28–4.39 and spatial Monte Carlo standard error0.33 (Figure5a–b). The greater deficit therefore accompanies earlier disease relative to grain filling without a consistent shortening of that window.',
            'A registered fourteen-setting ensemble comprises161,280 draw-season records, retaining alternative source assumptions, effective rank spacings, stage profiles, detection conventions, reference-canopy decline and functional-conversion factors. Every setting and climate model gives earlier modeled F1 symptoms and increased HAD deficit. On identical pairs across settings, mean symptom shifts range−5.46 to−1.54 days and HAD increases0.63–2.80 days per unit nominal LAI. Timing coverage is88.31–95.30%, conditional on detection in both periods; HAD coverage is99.972–100%. Earlier effective infection is less uniform: one late-stage-profile/model combination changes+0.014 days (Figure5d; Table S11a).',
            'A four-combination weather–host decomposition attributes +9.00 HAD days per unit nominal LAI to the disease-weather contribution and −6.36 days to host development (supported-forcing GCM ranges6.53–12.22 and−7.77 to−5.24). Their sum is a +2.64-day net change, with an interaction of−2.78 days allocated equally between contributions; signs are consistent across all three GCMs. The opposing host contribution reflects crop development, while mean grain-fill duration increases only0.12 days rather than shortening. This decomposition partitions the model response to paired forcing bundles and does not identify physical causal effects (Figure5c; Table S13).',
            'At coefficient0.018, the baseline conditional yield-effect increase is0.047 t ha⁻¹ per unit nominal upper-three LAI, with a climate-model range0.023–0.079 and spatial Monte Carlo standard error0.006. Across structural settings and the three fixed cultivar coefficients, mean effects span0.009–0.058 t ha⁻¹ per unit LAI. The broader GS31–85 baseline window gives0.057 t ha⁻¹,22% above the flowering–BBCH85 value. SSP1–2.6 andSSP2–4.5 baseline late-century changes are0.025 and0.027; the SSP1–2.6 model range crosses zero. These products express modeled functional-area dependence, not observed grain losses or a probability interval (Table S9c).',
            'The spatial pattern combines fixed harvested area with current sampled-cell symptoms and conditional yield effects (Figure6). Point values remain at their actual coordinates without interpolation. A current-model2001 calculation processes14,941 registered cells: 14,772 seasons complete,160 fail to reach BBCH85 and nine lack calendars. It reproduces sampled outputs at matching cells, but does not supply a completed multi-period census. The current single-year full-grid result is shown in Figure S14.'
        ],
        'discussion_field_and_limits.txt': [
            'Discussion',
            'Climate and weather affect infection-mediated wheat production through the interaction of epidemic development and host development. The supported-forcing decomposition attributes +9.00 HAD days per unit nominal LAI to disease-weather forcing and −6.36 days to host development, yielding a +2.64-day net change. Earlier symptoms and increased upper-leaf deficit persist across the fourteen declared structural and canopy settings, although infection-date direction varies for one individual climate-model setting. The decomposition helps locate where improved crop-development representation can inform resilient production; its grain-yield magnitude remains conditional on functional-area and crop-response assumptions.',
            'The field comparisons qualify this mechanism at each scale. German station holdouts support retained development under known sowing and realized weather. Broad flag-stage intervals and sparse soft-dough evidence constrain the additional leaf and grain-fill windows. Fully nested selection removes shared nuisance estimation from disease-inner evaluation without improving the chosen setting or resolving weak identification. Grouped uncertainty distinguishes the poorly resolved BASF timing comparison from the poorer Corteva source-numbered-leaf result. Ambiguous leaf identity and retrospective reuse remain observation limitations; they cannot be repaired by interpreting simulated infection dates as measured events.',
            'The physiological distinction between symptoms and functional green-area loss is decisive for grain production. A percentage score can combine lesions, associated senescence and source-specific assessment conventions without measuring the surviving canopy area. Equal nominal upper-leaf areas, prescribed senescence and fixed conversion factors demonstrate how the production consequence changes under explicit assumptions. The22% window sensitivity and0.009–0.058 t ha⁻¹ range indicate that a single coefficient-times-deficit estimate conceals substantial dependence on leaf function and temporal scope. The public severity–yield transfer failures concern a different measurement domain and do not establish failure of HAD physiology. They do establish that current disease scores cannot independently validate the simulated absolute-yield effects. [[Parker2004|vanDenBerg2017]]',
            'Climate-adaptive crop production consequently requires compatible observations of development, infection-related damage, reference green area and grain response. Developmental adjustment changes the tissue exposed to weather and infection; tolerance changes how that damage affects assimilate supply and yield. Changes in sowing or cultivar cannot be assigned a production benefit from the present fixed-management comparison. Their assessment requires crop calendars and genotype-specific canopy responses measured alongside yield, with infection-attributable and other treatment effects distinguished. Radiation absorption and source–sink buffering provide relevant crop-process extensions, rather than a universal conversion from affected leaf percentage. [[McDonald2022|Foulkes2006]]',
            'For agricultural policy, the production evidence supports investment in linked crop-development, leaf-function and harvest measurements within cultivar and management trials. Such evidence can connect climate adaptation and crop protection to stable grain production and food security. The European Vision for Agriculture and Food places resilience and sustainable production among its objectives; infection-related adaptation assessment can contribute through transparent comparison of production effects under specified crop and weather conditions. Economic returns, avoided tonnes and benefits of altered protection practices require additional crop-response evidence. [[ECVision2025]]'
        ],
        'methods.txt': _methods(),
        'availability.txt': [
            'Data availability',
            'Public BASF and Corteva disease archives, NEX-GDDP-CMIP6v2 forcing, the GGCMI crop calendar and SPAM2020 harvested area are identified by persistent dataset references. Source_Data.xlsx contains the numerical stage, disease, crop-response and climate tables used in the current analysis, with source paths and checksums. Individual predictions, resampling memberships, paired populations, forcing manifests and input/output hashes accompany Software_and_Evidence.zip. Raw whole-domain climate products and sampled-weather caches remain external and are identified by their checksums and source manifests. [[Holst2022BASF|HolstDonner2022Corteva|NEXGDDPCmip6V2|GGCMIPhase32021|SPAM2020]]',
            'Published crop-response transcriptions retain source-table identity, units, leaf scope, integration window and aggregate/fitted status. Unavailable plot observations, covariance and measured functional-area trajectories remain unavailable. All original observation and older-model records retain their original provenance.',
            'Code availability',
            'The versioned package contains the parameterized simulation runtime, external calibration and evaluation utilities, revision analyses, synthetic example forcing and the complete publication entry point. REPRODUCIBILITY.txt defines the single document/figure regeneration command and separately identifies forcing-based reruns. Supplementary_Model_Specification.docx and.pdf contain29 numbered equations; Parameter_inventory.csv identifies84 fixed, fitted and scenario quantities. Numerical verification establishes calculation equivalence and source identity, while the reported field and crop-response comparisons determine predictive interpretation.'
        ],
        'supplementary_methods.txt': _supplement(original['supplementary_methods.txt'])
    }


def _methods():
    return [
        'Methods', 'Observations and study populations',
        'The strict disease population contains216 field seasons and2,287 numerical assessments:28 BASF2017–2018 calibration fields with254 assessments,45 BASF2019 fields with330, and143 location-disjoint Corteva fields with1,703. The overlapping full Corteva population adds two fields and18 assessments, giving218 fields and2,305 assessments for full-source replay. BASF explicitly names the flag leaf; Corteva source leaves1–3 remain source-numbered. INFECT is source-defined severity, not an independently measured infection event. Rounded coordinate-year, field and source-leaf keys retain their identities through evaluation. [[Holst2022BASF|HolstDonner2022Corteva]]',
        'Last preceding zero and first positive define an onset interval with open lower and closed upper bounds. First-positive-only histories are left censored and zero-only histories right censored; later zero returns are persistence violations. Interval loss is calendar distance outside the admissible daily dates. A missing modeled event with an observed positive receives at least30 days of loss. Stage observations undergo ordered-range normalization, with contradictory and temporally reversed records quarantined rather than converted to exact dates.',
        'Crop development and seasonal disease',
        'Temperature-weighted development uses prior-day thermal accumulation to gate photoperiod and prior-day temperature–photoperiod accumulation to gate vernalization; its vernalization response uses the current updated vernalization state. Frozen donor thresholds define BBCH10,31,51 and85. Stage-only estimation jointly orders BBCH32,33,37 and39 on399 candidates between BBCH31 and51. The independently stage-fitted flowering proxy defines BBCH65; BBCH85 represents soft dough. Profiles within one or two days of minimum censored loss describe identification rather than confidence intervals.',
        'Final-rank tip appearance is max(C10,C37−rΔ), r=0,…,6, and unfolding spans C39−C37 development units. Prior-day visibility gates disease availability; proposed end-day development determines current leaf capacity. Expansion dilutes nonsusceptible tissue. Juvenile capacity withdraws between BBCH31 and39, with effective thermal renewal; this handover does not estimate natural senescence. Individual leaves contain susceptible tissue, three latent compartments, visible noninfectious tissue, infectious tissue and retained damage. Unit normalized tissue is conserved through four equal daily substeps.',
        'Local source has unready and competent relative states with weather-dependent transfer and common thermal ageing. Imported relative pressure is separate. Primary establishment depends on source and weather exposure; secondary establishment additionally depends on area-weighted infectious tissue, a rank-distance rainfall kernel and a declared unfolding-contact term. Nonpositive temperature stops thermal disease progression and source ageing, but does not automatically eliminate establishment hazards. The full equations, numerical chronology and parameter roles are supplied in Supplementary Model Specification and Table S12.',
        'Exposure uses daily mean/maximum temperature, mean humidity and precipitation to reconstruct24 synthetic humidity bins and effective rain duration. Positive-rain training weather estimates the precipitation/rain-hour scale; the final value is0.45 mm h⁻¹. This operator approximates daily exposure and does not measure leaf wetness. Model infection and symptom dates are the first end-day crossings of total nonsusceptible and visible/infectious/retained fractions, respectively, at detection fraction0.001. [[Hersbach2020ERA5|Lovell2004|Shaw1990]]',
        'Nested selection and paired statistical evaluation',
        'The registered disease grid contains144 settings; a separate six-setting phenology benchmark selects spacing and delay. Fully nested inner evaluation re-estimates added stages, the flowering proxy and meteorological preprocessing from each of three original-only training memberships. The German donor parameters remain fixed. Pooled genuinely bracketed source-leaf1–3 onset loss determines the primary choice; balanced assessment error and fixed enumeration resolve ties. Final original-only nuisance fits reproduce the frozen values. Reused BASF2019 and Corteva outcomes do not enter this nested selection. Prior development exposure means subsequent transfer remains retrospective, rather than an untouched confirmatory test.',
        'Metric weights give equal mass to coordinate-years, then fields, represented source leaves and assessments within leaves. Paired comparisons use20,000 intact coordinate-year bootstrap resamples with identical groups for both predictors. Reported95% percentile intervals condition on frozen predictions and the stated observation population; missing observed classes yield unavailable class-conditional replicates. They exclude fitting/selection uncertainty and unresolved biological site identity. Same-day complete-stage restrictions and exclusions of recorded preflag zero observations are declared sensitivities; their placeholder status is not inferred.',
        'Functional canopy and grain response',
        'For reference green area L0,l,d and assumed functional-loss fraction fl,d, HADloss,3=ΣdΣl=1…3L0,l,dfl,d, in GLAI-days. The conditional grain product is ΔY=bHADloss,3. Nominal mature upper-three LAI1 is divided equally among F1–F3 and scaled by unfolding. The field replay uses simulated visible/infectious/retained fractions directly; the climate replay additionally gates their contribution by first symptom detection. Latent fractions are excluded. These reporting operators are explicit and distinct from measured functional canopy loss.',
        'Parker’s top-three coefficients0.0141,0.018 and0.0207 t ha⁻¹ per GLAI-day define fixed cultivar scenarios. Their measured green-area integration begins at GS31 and uses trapezoidal integration; the exact original terminal rule is unrecovered. Current windows65–85 and31–85 use daily rectangular integration. Reference decline to0.5 or zero at85 and functional-conversion multipliers0.5/0.75 are declared canopy scenarios without probability distributions. Missing endpoints produce missing products. Actual field yield, percentage loss and total production loss are not inferred. [[Parker2004]]',
        'Published paired means retain disease, genotype, leaf scope and source-table identity. Five-background holdouts fit nonnegative proportional slopes using only the other backgrounds, with equal background weights. Public Nordic models use signed relative treatment response1−Yuntreated/Ytreated; all arms sharing a control remain in a trial holdout. BASF candidates train on2017–2018 and transfer to2019. Severity integrals retain percentage-day units and are not relabelled as HAD. [[Foulkes2006]]',
        'Climate forcing, paired spatial estimation and robustness',
        'Daily NEX-GDDP-CMIP6v2 forcing covers ACCESS-CM2,MPI-ESM1-2-HR and MRI-ESM2-0 under SSP1–2.6,2–4.5 and5–8.5. Historical-only monthly temperature offsets, humidity-logit offsets and precipitation ratios align forcing to the ERA5-derived reference. Harvest periods are1991–2020,2031–2060 and2071–2100. Sowing uses the winter/rainfed calendar; the first85 crossing ends the crop window. Forcing outside that window cannot advance crop or disease states. [[NEXGDDPCmip6V2|Hersbach2020ERA5|GGCMIPhase32021]]',
        'SPAM2020 all-wheat harvested area supplies fixed weights. Four independent draws with replacement in each of16 geographical strata give64 draw identities at62 unique cells; duplicates remain distinct in estimation. Annual and period means are ratios on metric-specific valid area-time support. Historical–future changes pair the same draw, climate model and relative-year index. Spatial Monte Carlo error uses stratified ratio-influence variance; averaging climate-model influence vectors retains shared-draw covariance. Climate-model extrema and structural scenario ranges have no confidence-interval interpretation. [[SPAM2020]]',
        'The registered SSP5–8.5 robustness ensemble compares1991–2020 with2071–2100 across all original draws and three climate models. Seven disease–host integrations support fourteen reporting settings: baseline, primary-objective-tied runner-up, local-source-off, rank spacings80/160, jointly admissible early/late stage profiles, detection thresholds0.0001/0.01, reference-canopy decline and functional-conversion scenarios. Stage paths remain strictly ordered within one day of minimum original stage loss. Each setting has11,520 draw-seasons. Cross-setting summaries use the intersection of valid historical–future pairs separately for each metric; detected-event timing and complete-window HAD retain different coverage. Source states, daily histories and every conditional coefficient product remain inspectable.',
        'Weather–host decomposition',
        'Four paired trajectories combine historical or future disease-weather forcing with historical or future host development for each GCM, year and spatial draw. Disease-weather forcing contains daily temperature, humidity and precipitation; host forcing contains crop development, leaf availability, unfolding, renewal, crop masking and the HAD window. Shapley contributions split the weather–host interaction equally and sum to the paired net HAD change. Twenty of5,751 finite draw-year pairs are excluded when any active hybrid mean temperature exceeds40 °C; the supported-forcing population retains5,731 pairs and weighted coverage of99.20–99.86%. This is a decomposition of model response to forcing bundles, not physical causal attribution. Host anthesis advances26.77 days after sowing and BBCH85 advances26.64 days; simulated grain-fill duration changes by+0.12 days. The independent temperature limit applies to the supported forcing range; model equations do not impose this biological bound.',
        'Software and independent calculation checks',
        'The model runtime accepts explicit forcing and immutable configuration, with calibration and observation preparation external to it. Independent checks reconstruct grouped comparison metrics, nested memberships, stage estimates, tissue/source conservation, paired climate ratios, common coverage and shared-draw Monte Carlo variance. Numerical equality supports reproducibility of the calculation; it does not establish biological predictive accuracy. Figures, native documents and the source workbook use the same completed evidence and citation registry.'
    ]


def _supplement(paragraphs):
    """Current-model methods and evidence selected for the crop-production question."""
    return [
        'Supplementary Methods',
        'Study populations and observations',
        'The strict evaluation set contains216 field seasons and2,287 numeric disease assessments: BASF2017–2018 calibration (28 fields,254 assessments), BASF2019 retrospective validation (45 fields,330 assessments) and location-disjoint Corteva evaluation (143 fields,1,703 assessments). The broader full-source replay includes two additional overlapping Corteva fields and18 assessments. BASF source leaf1 is explicitly the flag leaf. Corteva leaves1–3 retain source numbering because correspondence with final rank is unresolved. INFECT values are source-defined severity scores rather than independently observed infection events. Coordinate-year, field and source-leaf keys remain intact throughout evaluation. [[Holst2022BASF|HolstDonner2022Corteva]]',
        'Disease assessments were ordered within field and source leaf. First-positive-only and zero-only series were treated as left- and right-censored, respectively. A two-sided onset interval spans the day after the last observed zero through the first positive assessment. Predictions were scored by calendar distance outside this interval; they were not compared with imputed exact dates. Contradictory or temporally reversed assessment records were quarantined. The date of first visible symptom does not identify infection date.',
        'Crop-stage calibration and nested selection',
        'Temperature, photoperiod and vernalization drive a retained development coordinate. Added BBCH32,33,37 and39 thresholds were jointly ordered between BBCH31 and51. The flowering proxy was fitted separately from development-stage observations; BBCH85 represents soft dough. Full nested evaluation re-estimated stage, flowering and weather preprocessing within each of three original-calibration training folds. The German donor stage parameters remained fixed. Retrospective BASF2019 and Corteva outcomes were not used to choose the final settings. One inner fold contains no genuine two-sided BBCH32 interval and has116 exact-minimum threshold values spanning543.41–671.16 development units; these values describe weak identification rather than an uncertainty interval.',
        'Grouped validation and uncertainty',
        'Evaluation weights give equal mass to coordinate-years, then fields, represented source leaves and observations within leaves. Paired comparisons resample20,000 intact coordinate-year groups, preserving the paired predictions and all nested field and leaf histories. Percentile intervals condition on frozen predictions and the specified observation population; they exclude parameter-fitting uncertainty and unresolved site identity. Metrics based on different populations, including onset histories, numeric severity scores and assessment detection, are reported separately. Preflag-zero exclusions are sensitivity definitions and do not infer placeholder assessment labels.',
        'Canopy-function and crop-response evidence',
        'Published Septoria experiments supply117 protected-minus-unprotected yield contrasts across25 cultivars and six site-years. Their reported top-three green-area coefficients are0.0141,0.018 and0.0207 t ha−1 per GLAI-day. The measured-area window begins at GS31 and differs from the climate simulation’s flowering–BBCH85 window. A separate published top-five dataset contains eight aggregate contrasts across five genetic backgrounds and is evaluated by leaving each background out of coefficient fitting. Public Nordic and BASF trial contrasts use management-associated yield responses. Severity percentages and percentage-day integrals are not measured healthy-area duration. BASF archives contain87 treated–untreated yield contrasts across11 fields, but plot pairing and fully protected-reference status remain unresolved; measured healthy area and cause-specific senescence are unavailable. These trial records do not validate current absolute disease-attributable yield effects. [[Parker2004|Foulkes2006]]',
        'Climate forcing and spatial estimation',
        'Daily NEX-GDDP-CMIP6v2 inputs cover ACCESS-CM2, MPI-ESM1-2-HR and MRI-ESM2-0 under SSP1–2.6, SSP2–4.5 and SSP5–8.5. Historical-only monthly temperature offsets, humidity-logit offsets and precipitation ratios align forcing to the ERA5-derived reference. Comparisons use1991–2020,2031–2060 and2071–2100. Winter/rainfed crop calendars and SPAM2020 all-wheat harvested area define the imposed management and weights. Sixty-four registered area-proportional draws occupy62 unique cells in16 strata; duplicated draw identities remain distinct. Annual and period means use metric-specific valid area-time support, and changes pair the same draw, GCM and relative-year index. GCM ranges are deterministic model spread; spatial Monte Carlo errors quantify the registered draws. [[NEXGDDPCmip6V2|Hersbach2020ERA5|GGCMIPhase32021|SPAM2020]]',
        'Weather–host decomposition and sensitivity',
        'Four paired trajectories combine reference or future disease-weather forcing with reference or future host development. Weather forcing includes temperature, humidity and precipitation; host forcing includes stage progression, leaf availability, unfolding, renewal, crop mask and HAD window. The interaction is I=Y11−Y10−Y01+Y00. Weather and host Shapley contributions are (Y10−Y00)+I/2 and (Y01−Y00)+I/2; their sum is the paired net change. Twenty of5,751 finite draw-year pairs are excluded because at least one active hybrid disease-weather mean temperature exceeds40 °C; all supported-forcing components use the same5,731 pairs. The hybrid terms partition current-model response to forcing bundles and do not establish physical causal effects. Fourteen registered sensitivities vary source, rank spacing, stage profile, detection, reference-canopy decline and functional conversion; their scenario ranges are not probability intervals.',
        'Conditional canopy and yield operators',
        'Upper-three-leaf HAD proxy loss is the sum over days and F1–F3 of nominal reference leaf area multiplied by the modeled functional-loss fraction, in GLAI-days. The conditional yield product is ΔY=b×HADloss,3. Nominal mature upper-three-leaf LAI is one, divided equally among ranks and scaled by unfolding. The climate operator additionally gates contribution on first modeled symptom detection; the field replay uses its specified visible/infectious/retained fractions directly. Latent fractions are excluded. The reference canopy, functional conversion, grain-fill window and transfer coefficient are assumptions. No absolute yield loss, avoided tonnage or total production change is inferred.',
        'Mathematical specification and parameters',
        'Supplementary_Model_Specification.docx and.pdf provide the complete model chronology and29 numbered equations. Table S12 and Parameter_inventory.csv list84 fitted, fixed and scenario quantities with units, roles and provenance. Crop development, leaf capacity, tissue and source transitions, daily exposure, detection conventions, HAD integration and conditional yield conversion retain their explicit definitions. At nonpositive temperature, thermal disease progression and source ageing stop; establishment can still occur. Inactive leaves reset during inactive-crop days, while states outside the crop window remain frozen. Climate HAD symptom gating and field/public daily functional-loss integration are distinct reporting operators.'
    ]
